 adc a,ixh              ; Error
 adc a,ixl              ; Error
 adc a,iyh              ; Error
 adc a,iyl              ; Error
 adc ixh                ; Error
 adc ixl                ; Error
 adc iyh                ; Error
 adc iyl                ; Error
 add a,ixh              ; Error
 add a,ixl              ; Error
 add a,iyh              ; Error
 add a,iyl              ; Error
 add ixh                ; Error
 add ixl                ; Error
 add iyh                ; Error
 add iyl                ; Error
 altd res -1,a          ; Error
 altd res -1,b          ; Error
 altd res -1,c          ; Error
 altd res -1,d          ; Error
 altd res -1,e          ; Error
 altd res -1,h          ; Error
 altd res -1,l          ; Error
 altd res 8,a           ; Error
 altd res 8,b           ; Error
 altd res 8,c           ; Error
 altd res 8,d           ; Error
 altd res 8,e           ; Error
 altd res 8,h           ; Error
 altd res 8,l           ; Error
 altd set -1,a          ; Error
 altd set -1,b          ; Error
 altd set -1,c          ; Error
 altd set -1,d          ; Error
 altd set -1,e          ; Error
 altd set -1,h          ; Error
 altd set -1,l          ; Error
 altd set 8,a           ; Error
 altd set 8,b           ; Error
 altd set 8,c           ; Error
 altd set 8,d           ; Error
 altd set 8,e           ; Error
 altd set 8,h           ; Error
 altd set 8,l           ; Error
 and a,ixh              ; Error
 and a,ixl              ; Error
 and a,iyh              ; Error
 and a,iyl              ; Error
 and ixh                ; Error
 and ixl                ; Error
 and iyh                ; Error
 and iyl                ; Error
 bit -1,(hl)            ; Error
 bit -1,(ix)            ; Error
 bit -1,(ix+DIS)        ; Error
 bit -1,(iy)            ; Error
 bit -1,(iy+DIS)        ; Error
 bit -1,a               ; Error
 bit -1,b               ; Error
 bit -1,c               ; Error
 bit -1,d               ; Error
 bit -1,e               ; Error
 bit -1,h               ; Error
 bit -1,l               ; Error
 bit 8,(hl)             ; Error
 bit 8,(ix)             ; Error
 bit 8,(ix+DIS)         ; Error
 bit 8,(iy)             ; Error
 bit 8,(iy+DIS)         ; Error
 bit 8,a                ; Error
 bit 8,b                ; Error
 bit 8,c                ; Error
 bit 8,d                ; Error
 bit 8,e                ; Error
 bit 8,h                ; Error
 bit 8,l                ; Error
 cp a,ixh               ; Error
 cp a,ixl               ; Error
 cp a,iyh               ; Error
 cp a,iyl               ; Error
 cp ixh                 ; Error
 cp ixl                 ; Error
 cp iyh                 ; Error
 cp iyl                 ; Error
 cpd                    ; Error
 cpdr                   ; Error
 cpi                    ; Error
 cpir                   ; Error
 daa                    ; Error
 dec ixh                ; Error
 dec ixl                ; Error
 dec iyh                ; Error
 dec iyl                ; Error
 di                     ; Error
 ei                     ; Error
 halt                   ; Error
 im -1                  ; Error
 im 0                   ; Error
 im 1                   ; Error
 im 2                   ; Error
 im 3                   ; Error
 in a,(N)               ; Error
 in a,(c)               ; Error
 in b,(c)               ; Error
 in c,(c)               ; Error
 in d,(c)               ; Error
 in e,(c)               ; Error
 in f,(c)               ; Error
 in h,(c)               ; Error
 in l,(c)               ; Error
 in0 a,(N)              ; Error
 in0 b,(N)              ; Error
 in0 c,(N)              ; Error
 in0 d,(N)              ; Error
 in0 e,(N)              ; Error
 in0 f,(N)              ; Error
 in0 h,(N)              ; Error
 in0 l,(N)              ; Error
 inc ixh                ; Error
 inc ixl                ; Error
 inc iyh                ; Error
 inc iyl                ; Error
 ind                    ; Error
 indr                   ; Error
 ini                    ; Error
 inir                   ; Error
 ipset -1               ; Error
 ipset 4                ; Error
 ld a,i                 ; Error
 ld a,ixh               ; Error
 ld a,ixl               ; Error
 ld a,iyh               ; Error
 ld a,iyl               ; Error
 ld a,r                 ; Error
 ld b,ixh               ; Error
 ld b,ixl               ; Error
 ld b,iyh               ; Error
 ld b,iyl               ; Error
 ld c,ixh               ; Error
 ld c,ixl               ; Error
 ld c,iyh               ; Error
 ld c,iyl               ; Error
 ld d,ixh               ; Error
 ld d,ixl               ; Error
 ld d,iyh               ; Error
 ld d,iyl               ; Error
 ld e,ixh               ; Error
 ld e,ixl               ; Error
 ld e,iyh               ; Error
 ld e,iyl               ; Error
 ld i,a                 ; Error
 ld ixh,N               ; Error
 ld ixh,a               ; Error
 ld ixh,b               ; Error
 ld ixh,c               ; Error
 ld ixh,d               ; Error
 ld ixh,e               ; Error
 ld ixh,ixh             ; Error
 ld ixh,ixl             ; Error
 ld ixl,N               ; Error
 ld ixl,a               ; Error
 ld ixl,b               ; Error
 ld ixl,c               ; Error
 ld ixl,d               ; Error
 ld ixl,e               ; Error
 ld ixl,ixh             ; Error
 ld ixl,ixl             ; Error
 ld iyh,N               ; Error
 ld iyh,a               ; Error
 ld iyh,b               ; Error
 ld iyh,c               ; Error
 ld iyh,d               ; Error
 ld iyh,e               ; Error
 ld iyh,iyh             ; Error
 ld iyh,iyl             ; Error
 ld iyl,N               ; Error
 ld iyl,a               ; Error
 ld iyl,b               ; Error
 ld iyl,c               ; Error
 ld iyl,d               ; Error
 ld iyl,e               ; Error
 ld iyl,iyh             ; Error
 ld iyl,iyl             ; Error
 ld r,a                 ; Error
 mlt sp                 ; Error
 or a,ixh               ; Error
 or a,ixl               ; Error
 or a,iyh               ; Error
 or a,iyl               ; Error
 or ixh                 ; Error
 or ixl                 ; Error
 or iyh                 ; Error
 or iyl                 ; Error
 otdm                   ; Error
 otdmr                  ; Error
 otdr                   ; Error
 otim                   ; Error
 otimr                  ; Error
 otir                   ; Error
 out (N),a              ; Error
 out (c),-1             ; Error
 out (c),0              ; Error
 out (c),1              ; Error
 out (c),a              ; Error
 out (c),b              ; Error
 out (c),c              ; Error
 out (c),d              ; Error
 out (c),e              ; Error
 out (c),h              ; Error
 out (c),l              ; Error
 out0 (N),a             ; Error
 out0 (N),b             ; Error
 out0 (N),c             ; Error
 out0 (N),d             ; Error
 out0 (N),e             ; Error
 out0 (N),h             ; Error
 out0 (N),l             ; Error
 outd                   ; Error
 outi                   ; Error
 res -1,(hl)            ; Error
 res -1,(ix)            ; Error
 res -1,(ix+DIS)        ; Error
 res -1,(iy)            ; Error
 res -1,(iy+DIS)        ; Error
 res -1,a               ; Error
 res -1,a'              ; Error
 res -1,b               ; Error
 res -1,b'              ; Error
 res -1,c               ; Error
 res -1,c'              ; Error
 res -1,d               ; Error
 res -1,d'              ; Error
 res -1,e               ; Error
 res -1,e'              ; Error
 res -1,h               ; Error
 res -1,h'              ; Error
 res -1,l               ; Error
 res -1,l'              ; Error
 res 8,(hl)             ; Error
 res 8,(ix)             ; Error
 res 8,(ix+DIS)         ; Error
 res 8,(iy)             ; Error
 res 8,(iy+DIS)         ; Error
 res 8,a                ; Error
 res 8,a'               ; Error
 res 8,b                ; Error
 res 8,b'               ; Error
 res 8,c                ; Error
 res 8,c'               ; Error
 res 8,d                ; Error
 res 8,d'               ; Error
 res 8,e                ; Error
 res 8,e'               ; Error
 res 8,h                ; Error
 res 8,h'               ; Error
 res 8,l                ; Error
 res 8,l'               ; Error
 retn                   ; Error
 rl (ix),a              ; Error
 rl (ix),b              ; Error
 rl (ix),c              ; Error
 rl (ix),d              ; Error
 rl (ix),e              ; Error
 rl (ix),h              ; Error
 rl (ix),l              ; Error
 rl (ix+DIS),a          ; Error
 rl (ix+DIS),b          ; Error
 rl (ix+DIS),c          ; Error
 rl (ix+DIS),d          ; Error
 rl (ix+DIS),e          ; Error
 rl (ix+DIS),h          ; Error
 rl (ix+DIS),l          ; Error
 rl (iy),a              ; Error
 rl (iy),b              ; Error
 rl (iy),c              ; Error
 rl (iy),d              ; Error
 rl (iy),e              ; Error
 rl (iy),h              ; Error
 rl (iy),l              ; Error
 rl (iy+DIS),a          ; Error
 rl (iy+DIS),b          ; Error
 rl (iy+DIS),c          ; Error
 rl (iy+DIS),d          ; Error
 rl (iy+DIS),e          ; Error
 rl (iy+DIS),h          ; Error
 rl (iy+DIS),l          ; Error
 rlc (ix),a             ; Error
 rlc (ix),b             ; Error
 rlc (ix),c             ; Error
 rlc (ix),d             ; Error
 rlc (ix),e             ; Error
 rlc (ix),h             ; Error
 rlc (ix),l             ; Error
 rlc (ix+DIS),a         ; Error
 rlc (ix+DIS),b         ; Error
 rlc (ix+DIS),c         ; Error
 rlc (ix+DIS),d         ; Error
 rlc (ix+DIS),e         ; Error
 rlc (ix+DIS),h         ; Error
 rlc (ix+DIS),l         ; Error
 rlc (iy),a             ; Error
 rlc (iy),b             ; Error
 rlc (iy),c             ; Error
 rlc (iy),d             ; Error
 rlc (iy),e             ; Error
 rlc (iy),h             ; Error
 rlc (iy),l             ; Error
 rlc (iy+DIS),a         ; Error
 rlc (iy+DIS),b         ; Error
 rlc (iy+DIS),c         ; Error
 rlc (iy+DIS),d         ; Error
 rlc (iy+DIS),e         ; Error
 rlc (iy+DIS),h         ; Error
 rlc (iy+DIS),l         ; Error
 rld                    ; Error
 rr (ix),a              ; Error
 rr (ix),b              ; Error
 rr (ix),c              ; Error
 rr (ix),d              ; Error
 rr (ix),e              ; Error
 rr (ix),h              ; Error
 rr (ix),l              ; Error
 rr (ix+DIS),a          ; Error
 rr (ix+DIS),b          ; Error
 rr (ix+DIS),c          ; Error
 rr (ix+DIS),d          ; Error
 rr (ix+DIS),e          ; Error
 rr (ix+DIS),h          ; Error
 rr (ix+DIS),l          ; Error
 rr (iy),a              ; Error
 rr (iy),b              ; Error
 rr (iy),c              ; Error
 rr (iy),d              ; Error
 rr (iy),e              ; Error
 rr (iy),h              ; Error
 rr (iy),l              ; Error
 rr (iy+DIS),a          ; Error
 rr (iy+DIS),b          ; Error
 rr (iy+DIS),c          ; Error
 rr (iy+DIS),d          ; Error
 rr (iy+DIS),e          ; Error
 rr (iy+DIS),h          ; Error
 rr (iy+DIS),l          ; Error
 rrc (ix),a             ; Error
 rrc (ix),b             ; Error
 rrc (ix),c             ; Error
 rrc (ix),d             ; Error
 rrc (ix),e             ; Error
 rrc (ix),h             ; Error
 rrc (ix),l             ; Error
 rrc (ix+DIS),a         ; Error
 rrc (ix+DIS),b         ; Error
 rrc (ix+DIS),c         ; Error
 rrc (ix+DIS),d         ; Error
 rrc (ix+DIS),e         ; Error
 rrc (ix+DIS),h         ; Error
 rrc (ix+DIS),l         ; Error
 rrc (iy),a             ; Error
 rrc (iy),b             ; Error
 rrc (iy),c             ; Error
 rrc (iy),d             ; Error
 rrc (iy),e             ; Error
 rrc (iy),h             ; Error
 rrc (iy),l             ; Error
 rrc (iy+DIS),a         ; Error
 rrc (iy+DIS),b         ; Error
 rrc (iy+DIS),c         ; Error
 rrc (iy+DIS),d         ; Error
 rrc (iy+DIS),e         ; Error
 rrc (iy+DIS),h         ; Error
 rrc (iy+DIS),l         ; Error
 rrd                    ; Error
 rst -1                 ; Error
 rst 0                  ; Error
 rst 48                 ; Error
 rst 49                 ; Error
 rst 57                 ; Error
 rst 8                  ; Error
 sbc a,ixh              ; Error
 sbc a,ixl              ; Error
 sbc a,iyh              ; Error
 sbc a,iyl              ; Error
 sbc ixh                ; Error
 sbc ixl                ; Error
 sbc iyh                ; Error
 sbc iyl                ; Error
 set -1,(hl)            ; Error
 set -1,(ix)            ; Error
 set -1,(ix+DIS)        ; Error
 set -1,(iy)            ; Error
 set -1,(iy+DIS)        ; Error
 set -1,a               ; Error
 set -1,a'              ; Error
 set -1,b               ; Error
 set -1,b'              ; Error
 set -1,c               ; Error
 set -1,c'              ; Error
 set -1,d               ; Error
 set -1,d'              ; Error
 set -1,e               ; Error
 set -1,e'              ; Error
 set -1,h               ; Error
 set -1,h'              ; Error
 set -1,l               ; Error
 set -1,l'              ; Error
 set 8,(hl)             ; Error
 set 8,(ix)             ; Error
 set 8,(ix+DIS)         ; Error
 set 8,(iy)             ; Error
 set 8,(iy+DIS)         ; Error
 set 8,a                ; Error
 set 8,a'               ; Error
 set 8,b                ; Error
 set 8,b'               ; Error
 set 8,c                ; Error
 set 8,c'               ; Error
 set 8,d                ; Error
 set 8,d'               ; Error
 set 8,e                ; Error
 set 8,e'               ; Error
 set 8,h                ; Error
 set 8,h'               ; Error
 set 8,l                ; Error
 set 8,l'               ; Error
 sla (ix),a             ; Error
 sla (ix),b             ; Error
 sla (ix),c             ; Error
 sla (ix),d             ; Error
 sla (ix),e             ; Error
 sla (ix),h             ; Error
 sla (ix),l             ; Error
 sla (ix+DIS),a         ; Error
 sla (ix+DIS),b         ; Error
 sla (ix+DIS),c         ; Error
 sla (ix+DIS),d         ; Error
 sla (ix+DIS),e         ; Error
 sla (ix+DIS),h         ; Error
 sla (ix+DIS),l         ; Error
 sla (iy),a             ; Error
 sla (iy),b             ; Error
 sla (iy),c             ; Error
 sla (iy),d             ; Error
 sla (iy),e             ; Error
 sla (iy),h             ; Error
 sla (iy),l             ; Error
 sla (iy+DIS),a         ; Error
 sla (iy+DIS),b         ; Error
 sla (iy+DIS),c         ; Error
 sla (iy+DIS),d         ; Error
 sla (iy+DIS),e         ; Error
 sla (iy+DIS),h         ; Error
 sla (iy+DIS),l         ; Error
 sli (hl)               ; Error
 sli (ix)               ; Error
 sli (ix),a             ; Error
 sli (ix),b             ; Error
 sli (ix),c             ; Error
 sli (ix),d             ; Error
 sli (ix),e             ; Error
 sli (ix),h             ; Error
 sli (ix),l             ; Error
 sli (ix+DIS)           ; Error
 sli (ix+DIS),a         ; Error
 sli (ix+DIS),b         ; Error
 sli (ix+DIS),c         ; Error
 sli (ix+DIS),d         ; Error
 sli (ix+DIS),e         ; Error
 sli (ix+DIS),h         ; Error
 sli (ix+DIS),l         ; Error
 sli (iy)               ; Error
 sli (iy),a             ; Error
 sli (iy),b             ; Error
 sli (iy),c             ; Error
 sli (iy),d             ; Error
 sli (iy),e             ; Error
 sli (iy),h             ; Error
 sli (iy),l             ; Error
 sli (iy+DIS)           ; Error
 sli (iy+DIS),a         ; Error
 sli (iy+DIS),b         ; Error
 sli (iy+DIS),c         ; Error
 sli (iy+DIS),d         ; Error
 sli (iy+DIS),e         ; Error
 sli (iy+DIS),h         ; Error
 sli (iy+DIS),l         ; Error
 sli a                  ; Error
 sli b                  ; Error
 sli c                  ; Error
 sli d                  ; Error
 sli e                  ; Error
 sli h                  ; Error
 sli l                  ; Error
 sll (hl)               ; Error
 sll (ix)               ; Error
 sll (ix),a             ; Error
 sll (ix),b             ; Error
 sll (ix),c             ; Error
 sll (ix),d             ; Error
 sll (ix),e             ; Error
 sll (ix),h             ; Error
 sll (ix),l             ; Error
 sll (ix+DIS)           ; Error
 sll (ix+DIS),a         ; Error
 sll (ix+DIS),b         ; Error
 sll (ix+DIS),c         ; Error
 sll (ix+DIS),d         ; Error
 sll (ix+DIS),e         ; Error
 sll (ix+DIS),h         ; Error
 sll (ix+DIS),l         ; Error
 sll (iy)               ; Error
 sll (iy),a             ; Error
 sll (iy),b             ; Error
 sll (iy),c             ; Error
 sll (iy),d             ; Error
 sll (iy),e             ; Error
 sll (iy),h             ; Error
 sll (iy),l             ; Error
 sll (iy+DIS)           ; Error
 sll (iy+DIS),a         ; Error
 sll (iy+DIS),b         ; Error
 sll (iy+DIS),c         ; Error
 sll (iy+DIS),d         ; Error
 sll (iy+DIS),e         ; Error
 sll (iy+DIS),h         ; Error
 sll (iy+DIS),l         ; Error
 sll a                  ; Error
 sll b                  ; Error
 sll c                  ; Error
 sll d                  ; Error
 sll e                  ; Error
 sll h                  ; Error
 sll l                  ; Error
 slp                    ; Error
 sra (ix),a             ; Error
 sra (ix),b             ; Error
 sra (ix),c             ; Error
 sra (ix),d             ; Error
 sra (ix),e             ; Error
 sra (ix),h             ; Error
 sra (ix),l             ; Error
 sra (ix+DIS),a         ; Error
 sra (ix+DIS),b         ; Error
 sra (ix+DIS),c         ; Error
 sra (ix+DIS),d         ; Error
 sra (ix+DIS),e         ; Error
 sra (ix+DIS),h         ; Error
 sra (ix+DIS),l         ; Error
 sra (iy),a             ; Error
 sra (iy),b             ; Error
 sra (iy),c             ; Error
 sra (iy),d             ; Error
 sra (iy),e             ; Error
 sra (iy),h             ; Error
 sra (iy),l             ; Error
 sra (iy+DIS),a         ; Error
 sra (iy+DIS),b         ; Error
 sra (iy+DIS),c         ; Error
 sra (iy+DIS),d         ; Error
 sra (iy+DIS),e         ; Error
 sra (iy+DIS),h         ; Error
 sra (iy+DIS),l         ; Error
 srl (ix),a             ; Error
 srl (ix),b             ; Error
 srl (ix),c             ; Error
 srl (ix),d             ; Error
 srl (ix),e             ; Error
 srl (ix),h             ; Error
 srl (ix),l             ; Error
 srl (ix+DIS),a         ; Error
 srl (ix+DIS),b         ; Error
 srl (ix+DIS),c         ; Error
 srl (ix+DIS),d         ; Error
 srl (ix+DIS),e         ; Error
 srl (ix+DIS),h         ; Error
 srl (ix+DIS),l         ; Error
 srl (iy),a             ; Error
 srl (iy),b             ; Error
 srl (iy),c             ; Error
 srl (iy),d             ; Error
 srl (iy),e             ; Error
 srl (iy),h             ; Error
 srl (iy),l             ; Error
 srl (iy+DIS),a         ; Error
 srl (iy+DIS),b         ; Error
 srl (iy+DIS),c         ; Error
 srl (iy+DIS),d         ; Error
 srl (iy+DIS),e         ; Error
 srl (iy+DIS),h         ; Error
 srl (iy+DIS),l         ; Error
 sub a,ixh              ; Error
 sub a,ixl              ; Error
 sub a,iyh              ; Error
 sub a,iyl              ; Error
 sub ixh                ; Error
 sub ixl                ; Error
 sub iyh                ; Error
 sub iyl                ; Error
 tstio N                ; Error
 xor a,ixh              ; Error
 xor a,ixl              ; Error
 xor a,iyh              ; Error
 xor a,iyl              ; Error
 xor ixh                ; Error
 xor ixl                ; Error
 xor iyh                ; Error
 xor iyl                ; Error
