# Target library graphics sub-builds.
#
# Keep the stamp separate from the objects while the existing .lst files
# still use obj/${TARGET} paths. This file owns the recursive gfx build
# definitions; libsrc/Makefile only names the stamps as prerequisites.

GFX_STAMP_SOURCES := $(shell find classic/gfx -type f \( -name '*.asm' -o -name '*.c' -o -name 'Makefile' \))

define gfx_stamp
classic/gfx/obj/.stamp-$(1)-$(2): $(GFX_STAMP_SOURCES)
	@mkdir -p $$(dir $$@)
	$(MAKE) -C classic/gfx TARGET=$(1) FLAVOUR=$(2)
	@touch $$@
endef

define gfx_stamp_args
classic/gfx/obj/.stamp-$(1): $(GFX_STAMP_SOURCES)
	@mkdir -p $$(dir $$@)
	$(MAKE) -C classic/gfx $(2)
	@touch $$@
endef

$(eval $(call gfx_stamp,z88,wide))
$(eval $(call gfx_stamp,zx,narrow))
$(eval $(call gfx_stamp,zxn,wide))
$(eval $(call gfx_stamp,ts2068,wide))
$(eval $(call gfx_stamp_args,pacman,TARGET=pacman FLAVOUR="text6 narrow"))
$(eval $(call gfx_stamp_args,p2000,TARGET=p2000 FLAVOUR="text6 narrow"))
$(eval $(call gfx_stamp_args,pc6001,TARGET=pc6001 FLAVOUR="narrow portable"))
$(eval $(call gfx_stamp_args,pc88,TARGET=pc88 FLAVOUR=wide))
$(eval $(call gfx_stamp_args,pps,TARGET=pps))
$(eval $(call gfx_stamp_args,cpm-px4,TARGET=cpm SUBTYPE=px4 FLAVOUR=narrow))
$(eval $(call gfx_stamp_args,cpm-px8,TARGET=cpm SUBTYPE=px8 FLAVOUR=wide))
$(eval $(call gfx_stamp_args,cpm-v1050,TARGET=cpm FLAVOUR=wide SUBTYPE=v1050))
$(eval $(call gfx_stamp_args,cpm-v1050udg,TARGET=cpm SUBTYPE=v1050udg FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,vz,TARGET=vz))
$(eval $(call gfx_stamp_args,zx80,TARGET=zx80))
$(eval $(call gfx_stamp_args,zx81,TARGET=zx81 FLAVOUR=narrow))
$(eval $(call gfx_stamp_args,zx81-phrg,TARGET=zx81 FLAVOUR=narrow SUBTYPE=zx81phrg))
$(eval $(call gfx_stamp_args,zx81-lambda,TARGET=zx81 FLAVOUR=narrow SUBTYPE=lambda))
$(eval $(call gfx_stamp_args,zx81-udg,TARGET=zx81 SUBTYPE=zx81udg FLAVOUR="narrow text6"))
$(eval $(call gfx_stamp_args,zx81-hr64,TARGET=zx81 FLAVOUR="narrow gray" SUBTYPE=zx81hr64))
$(eval $(call gfx_stamp_args,zx81-g64,TARGET=zx81 FLAVOUR="narrow gray" SUBTYPE=zx81g64))
$(eval $(call gfx_stamp_args,zx81-mt64,TARGET=zx81 FLAVOUR="narrow gray" SUBTYPE=zx81mt64))
$(eval $(call gfx_stamp_args,zx81-hr128,TARGET=zx81 FLAVOUR="narrow gray" SUBTYPE=zx81hr128))
$(eval $(call gfx_stamp_args,zx81-hr192,TARGET=zx81 FLAVOUR="narrow gray" SUBTYPE=zx81hr192))
$(eval $(call gfx_stamp_args,zx81-mt192,TARGET=zx81 FLAVOUR="narrow gray" SUBTYPE=zx81mt192))
$(eval $(call gfx_stamp_args,zx81-g007,TARGET=zx81 FLAVOUR="narrow gray" SUBTYPE=zx81g007))
$(eval $(call gfx_stamp_args,zx81-hr384,TARGET=zx81 FLAVOUR=wide SUBTYPE=zx81hr384))
$(eval $(call gfx_stamp_args,ti82,TARGET=ti82 FLAVOUR="gray narrow"))
$(eval $(call gfx_stamp_args,ti83,TARGET=ti83 FLAVOUR="gray narrow"))
$(eval $(call gfx_stamp_args,ti83p,TARGET=ti83p FLAVOUR="gray narrow"))
$(eval $(call gfx_stamp_args,ti85,TARGET=ti85 FLAVOUR="gray narrow"))
$(eval $(call gfx_stamp_args,ti86,TARGET=ti86 FLAVOUR="gray narrow"))
$(eval $(call gfx_stamp_args,oz,TARGET=oz))
$(eval $(call gfx_stamp_args,cpm-kaypro,TARGET=cpm FLAVOUR=narrow SUBTYPE=kaypro))
$(eval $(call gfx_stamp_args,cpm-kaypro83,TARGET=cpm FLAVOUR=narrow SUBTYPE=kaypro83))
$(eval $(call gfx_stamp_args,cpm-attache,TARGET=cpm FLAVOUR=wide SUBTYPE=attache))
$(eval $(call gfx_stamp_args,cpm-bondwell,TARGET=cpm FLAVOUR="gencon narrow" SUBTYPE=bondwell))
$(eval $(call gfx_stamp_args,cpm-bondwell2,TARGET=cpm FLAVOUR=wide SUBTYPE=bondwell2 TARGET_CFLAGS="-subtype=bondwell2"))
$(eval $(call gfx_stamp_args,cpm-osborne1,TARGET=cpm FLAVOUR=narrow SUBTYPE=osborne1))
$(eval $(call gfx_stamp_args,cpm-rc700,TARGET=cpm FLAVOUR="portable narrow gencon" SUBTYPE=rc700))
$(eval $(call gfx_stamp_args,cpm-x1,TARGET=cpm FLAVOUR=wide SUBTYPE=x1))
$(eval $(call gfx_stamp_args,cpm-tim011,TARGET=cpm FLAVOUR="wide portable gencon" SUBTYPE=tim011 TARGET_CFLAGS="-subtype=tim011"))
$(eval $(call gfx_stamp_args,cpm-x820ii,TARGET=cpm FLAVOUR="narrow gencon" SUBTYPE=x820ii))
$(eval $(call gfx_stamp_args,cpm-gsx,TARGET=cpm SUBTYPE=gsx FLAVOUR=wide))
$(eval $(call gfx_stamp_args,cpm,TARGET=cpm FLAVOUR=portable))
$(eval $(call gfx_stamp_args,srr,TARGET=srr FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,mz,TARGET=mz))
$(eval $(call gfx_stamp_args,mz2500,TARGET=mz2500))
$(eval $(call gfx_stamp_args,abc80,TARGET=abc80))
$(eval $(call gfx_stamp_args,abc800,TARGET=abc800))
$(eval $(call gfx_stamp_args,ace,TARGET=ace FLAVOUR="text narrow"))
$(eval $(call gfx_stamp_args,ace-udg,TARGET=ace SUBTYPE=aceudg FLAVOUR="gencon text6 narrow"))
$(eval $(call gfx_stamp_args,aquarius,TARGET=aquarius FLAVOUR="text6 narrow"))
$(eval $(call gfx_stamp_args,aq48,TARGET=aquarius SUBTYPE=aq48 FLAVOUR="text narrow"))
$(eval $(call gfx_stamp_args,aqplus,TARGET=aquarius SUBTYPE=aqplus FLAVOUR=wide))
$(eval $(call gfx_stamp_args,cpm-aussie,TARGET=cpm SUBTYPE=aussie FLAVOUR=wide))
$(eval $(call gfx_stamp_args,bee,TARGET=bee FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,bee-cpm,TARGET=bee FLAVOUR="gencon text6 narrow"))
$(eval $(call gfx_stamp_args,bee-hr,TARGET=bee FLAVOUR=wide SUBTYPE=beehr))
$(eval $(call gfx_stamp_args,bee-hr320,TARGET=bee FLAVOUR=wide SUBTYPE=beehr320))
$(eval $(call gfx_stamp_args,bee-hr512,TARGET=bee FLAVOUR=wide SUBTYPE=beehr512))
$(eval $(call gfx_stamp_args,svi,TARGET=svi))
$(eval $(call gfx_stamp_args,msx,TARGET=msx))
$(eval $(call gfx_stamp_args,mtx,TARGET=mtx))
$(eval $(call gfx_stamp_args,tvc,TARGET=tvc))
$(eval $(call gfx_stamp_args,enterprise,TARGET=enterprise FLAVOUR=wide))
$(eval $(call gfx_stamp_args,smc777,TARGET=smc777 FLAVOUR=wide))
$(eval $(call gfx_stamp_args,cpm-smc777,TARGET=cpm SUBTYPE=smc777 FLAVOUR=wide))
$(eval $(call gfx_stamp_args,cpm-coleco,TARGET=coleco FLAVOUR=narrow))
$(eval $(call gfx_stamp_args,m5,TARGET=m5))
$(eval $(call gfx_stamp_args,cpm-mbc200,TARGET=cpm FLAVOUR=wide SUBTYPE=mbc200))
$(eval $(call gfx_stamp_args,mc1000,TARGET=mc1000))
$(eval $(call gfx_stamp_args,phc25,TARGET=phc25))
$(eval $(call gfx_stamp_args,nascom,TARGET=nascom FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,z1013,TARGET=z1013 FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,z9001,TARGET=z9001 FLAVOUR="gencon wide"))
$(eval $(call gfx_stamp_args,kc,TARGET=kc FLAVOUR="wide portable"))
$(eval $(call gfx_stamp_args,hemc,TARGET=hemc FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,kramermc,TARGET=kramermc FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,hgmc,TARGET=hgmc))
$(eval $(call gfx_stamp_args,primo,TARGET=primo))
$(eval $(call gfx_stamp_args,rx78,TARGET=rx78))
$(eval $(call gfx_stamp_args,fp1100,TARGET=fp1100 FLAVOUR=wide))
$(eval $(call gfx_stamp_args,z80tvgame,TARGET=z80tvgame))
$(eval $(call gfx_stamp_args,multi8,TARGET=multi8 FLAVOUR=wide))
$(eval $(call gfx_stamp_args,pasopia7,TARGET=pasopia7 FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,laser500,TARGET=laser500 FLAVOUR=wide))
$(eval $(call gfx_stamp_args,super80,TARGET=super80 FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,alphatro,TARGET=alphatro FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,spc1000,TARGET=spc1000))
$(eval $(call gfx_stamp_args,pv1000,TARGET=pv1000 FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,pv2000,TARGET=pv2000))
$(eval $(call gfx_stamp_args,myvision,TARGET=myvision))
$(eval $(call gfx_stamp_args,sv8000,TARGET=sv8000))
$(eval $(call gfx_stamp_args,coleco,TARGET=coleco))
$(eval $(call gfx_stamp_args,pencil2,TARGET=pencil2))
$(eval $(call gfx_stamp_args,lm80c,TARGET=lm80c))
$(eval $(call gfx_stamp_args,nabu,TARGET=nabu))
$(eval $(call gfx_stamp_args,cpm-z80retro,TARGET=cpm FLAVOUR=narrow SUBTYPE=z80retro))
$(eval $(call gfx_stamp_args,hector1,TARGET=hector FLAVOUR=narrow SUBTYPE=hector1))
$(eval $(call gfx_stamp_args,hectorhr,TARGET=hector FLAVOUR=narrow SUBTYPE=hectorhr))
$(eval $(call gfx_stamp_args,cpm-gemini,TARGET=cpm FLAVOUR=narrow SUBTYPE=gemini))
$(eval $(call gfx_stamp_args,sam,TARGET=sam FLAVOUR=wide))
$(eval $(call gfx_stamp_args,enterprisehr,TARGET=enterprise FLAVOUR=wide SUBTYPE=enterprisehr))
$(eval $(call gfx_stamp_args,cpm-einstein,TARGET=cpm FLAVOUR=narrow SUBTYPE=einstein))
$(eval $(call gfx_stamp_args,excali64,TARGET=excali64 FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,alphatp2,TARGET=alphatp2 FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,gl,TARGET=gl))
$(eval $(call gfx_stamp_args,gl6000,TARGET=gl SUBTYPE=gl6000 FLAVOUR=narrow))
$(eval $(call gfx_stamp_args,nc,TARGET=nc))
$(eval $(call gfx_stamp_args,nc100,TARGET=nc FLAVOUR=wide SUBTYPE=nc100))
$(eval $(call gfx_stamp_args,zcn,TARGET=nc FLAVOUR=wide SUBTYPE=zcn))
$(eval $(call gfx_stamp_args,nc200,TARGET=nc FLAVOUR=wide SUBTYPE=nc200))
$(eval $(call gfx_stamp_args,cpc,TARGET=cpc FLAVOUR=wide))
$(eval $(call gfx_stamp_args,trs80,TARGET=trs80 FLAVOUR="text6 narrow"))
$(eval $(call gfx_stamp_args,trs80-base,TARGET=trs80))
$(eval $(call gfx_stamp_args,trs80m2,TARGET=trs80 FLAVOUR="gencon text6 narrow" SUBTYPE=trs80m2))
$(eval $(call gfx_stamp_args,trs80m4,TARGET=trs80 FLAVOUR="text6 narrow" SUBTYPE=trs80m4))
$(eval $(call gfx_stamp_args,eg2000,TARGET=trs80 FLAVOUR=narrow SUBTYPE=eg2000))
$(eval $(call gfx_stamp_args,hrg1,TARGET=trs80 FLAVOUR=wide SUBTYPE=hrg1))
$(eval $(call gfx_stamp_args,grafyx3,TARGET=trs80 FLAVOUR=wide SUBTYPE=grafyx3))
$(eval $(call gfx_stamp_args,grafyx4,TARGET=trs80 FLAVOUR=wide SUBTYPE=grafyx4))
$(eval $(call gfx_stamp_args,x07,TARGET=x07 FLAVOUR=narrow))
$(eval $(call gfx_stamp_args,x1,TARGET=x1 FLAVOUR=wide))
$(eval $(call gfx_stamp_args,vg5k,TARGET=vg5k FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,sos,TARGET=sos))
$(eval $(call gfx_stamp_args,osca,TARGET=osca FLAVOUR=wide))
$(eval $(call gfx_stamp_args,pmd85,TARGET=pmd85 FLAVOUR="portable wide"))
$(eval $(call gfx_stamp_args,mikro80,TARGET=mikro80 FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,m100,TARGET=m100 FLAVOUR=narrow))
$(eval $(call gfx_stamp_args,vector06c,TARGET=vector06c FLAVOUR=wide))
$(eval $(call gfx_stamp_args,vector06c-portable,TARGET=vector06c FLAVOUR=portable))
$(eval $(call gfx_stamp_args,lviv,TARGET=lviv FLAVOUR="narrow portable"))
$(eval $(call gfx_stamp_args,sol20,TARGET=sol20 FLAVOUR="portable gencon"))
$(eval $(call gfx_stamp_args,agon,TARGET=agon FLAVOUR=wide))
$(eval $(call gfx_stamp_args,ondra,TARGET=ondra FLAVOUR=wide))
$(eval $(call gfx_stamp_args,homelab,TARGET=homelab FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,homelab2,TARGET=homelab2 FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,krokha,TARGET=krokha FLAVOUR="gencon portable"))
$(eval $(call gfx_stamp_args,rc2014,TARGET=rc2014 FLAVOUR=portable))
$(eval $(call gfx_stamp_args,vti,TARGET=altair8800 SUBTYPE=vti FLAVOUR="gencon portable"))
$(eval $(call gfx_stamp_args,tek,TARGET=test SUBTYPE=tek FLAVOUR=wide))
$(eval $(call gfx_stamp_args,regis,TARGET=test SUBTYPE=regis FLAVOUR=wide))
$(eval $(call gfx_stamp_args,h19,TARGET=cpm SUBTYPE=h19 FLAVOUR="gencon text narrow"))
$(eval $(call gfx_stamp_args,h19alt,TARGET=cpm SUBTYPE=h19alt FLAVOUR="gencon text6 narrow"))
$(eval $(call gfx_stamp_args,vio,TARGET=altair8800 SUBTYPE=vio FLAVOUR="gencon portable"))
$(eval $(call gfx_stamp_args,vdm,TARGET=altair8800 SUBTYPE=vdm FLAVOUR="gencon portable"))
$(eval $(call gfx_stamp_args,cpm-nanos,TARGET=cpm FLAVOUR="narrow gencon" SUBTYPE=nanos))
$(eval $(call gfx_stamp_args,micro8085,TARGET=micro8085))
$(eval $(call gfx_stamp_args,c7420,TARGET=c7420))
$(eval $(call gfx_stamp_args,rex,TARGET=rex))
$(eval $(call gfx_stamp_args,phc20,TARGET=phc20))
$(eval $(call gfx_stamp_args,z80,TARGET=z80))
$(eval $(call gfx_stamp_args,rcmx000,TARGET=rcmx000))
$(eval $(call gfx_stamp_args,embedded,TARGET=embedded))
$(eval $(call gfx_stamp_args,test,TARGET=test))
$(eval $(call gfx_stamp_args,s1mp3,TARGET=s1mp3))
$(eval $(call gfx_stamp_args,special,TARGET=special FLAVOUR="wide portable"))
$(eval $(call gfx_stamp_args,pk8000,TARGET=pk8000 FLAVOUR=portable))
$(eval $(call gfx_stamp_args,altair8800,TARGET=altair8800 FLAVOUR=portable))
$(eval $(call gfx_stamp_args,dai,TARGET=dai FLAVOUR=portable))
$(eval $(call gfx_stamp_args,radio86,TARGET=radio86 FLAVOUR="gencon portable"))
$(eval $(call gfx_stamp_args,c128,TARGET=c128 FLAVOUR="text narrow"))
$(eval $(call gfx_stamp_args,c128udg,TARGET=c128 FLAVOUR="text6 narrow" SUBTYPE=c128udg))
$(eval $(call gfx_stamp_args,c128hr,TARGET=c128 FLAVOUR=wide SUBTYPE=c128hr))
$(eval $(call gfx_stamp_args,c128hr480,TARGET=c128 FLAVOUR=wide SUBTYPE=c128hr480))
$(eval $(call gfx_stamp_args,newbrain,TARGET=newbrain))
$(eval $(call gfx_stamp_args,cpm-northstar,TARGET=cpm FLAVOUR=wide SUBTYPE=northstar))
$(eval $(call gfx_stamp_args,cpm-tiki100,TARGET=cpm FLAVOUR=wide SUBTYPE=tiki100))
$(eval $(call gfx_stamp_args,gal,TARGET=gal))
$(eval $(call gfx_stamp_args,g800,TARGET=g800))
$(eval $(call gfx_stamp_args,g800-g815,TARGET=g800 FLAVOUR=narrow SUBTYPE=g815))
$(eval $(call gfx_stamp_args,g800-e200,TARGET=g800 FLAVOUR=narrow SUBTYPE=e200))
$(eval $(call gfx_stamp_args,g800-g850,TARGET=g800 FLAVOUR=narrow SUBTYPE=g850))
$(eval $(call gfx_stamp_args,lynx,TARGET=lynx FLAVOUR="gencon narrow"))
$(eval $(call gfx_stamp_args,sms,TARGET=sms))
$(eval $(call gfx_stamp_args,sc3000,TARGET=sc3000))
$(eval $(call gfx_stamp_args,gb,TARGET=gb FLAVOUR="gencon portable"))
$(eval $(call gfx_stamp_args,cpm-pcw,TARGET=cpm FLAVOUR=wide SUBTYPE=pcw))
