;
;	This file is automatically generated
;
;	Do not edit!!!
;
;	djm 12/2/2000
;
;	ZSock Lib function: getnetbyname


	XLIB	getnetbyname

	LIB	no_zsock

	INCLUDE	"#packages.def"
	INCLUDE	"#zsock.def"

.getnetbyname
	ld	a,r_getnetbyname
	call_pkg(tcp_all)
	ret	nc
; We failed..are we installed?
	cp	rc_pnf
	scf		;signal error
	ret	nz	;Internal error
	call_pkg(tcp_ayt)
	jr	nc,getnetbyname
	jp	no_zsock
