;
;	This file is automatically generated
;
;	Do not edit!!!
;
;	djm 12/2/2000
;
;	ZSock Lib function: getprotobynumber


	XLIB	getprotobynumber

	LIB	no_zsock

	INCLUDE	"#packages.def"
	INCLUDE	"#zsock.def"

.getprotobynumber
	ld	a,r_getprotobynumber
	call_pkg(tcp_all)
	ret	nc
; We failed..are we installed?
	cp	rc_pnf
	scf		;signal error
	ret	nz	;Internal error
	call_pkg(tcp_ayt)
	jr	nc,getprotobynumber
	jp	no_zsock
