; void SMS_setLineInterruptHandler(void *theHandlerFunction)

SECTION code_clib
SECTION code_SMSlib

PUBLIC _SMS_setLineInterruptHandler

EXTERN asm_SMSlib_setLineInterruptHandler

defc _SMS_setLineInterruptHandler = asm_SMSlib_setLineInterruptHandler
