; void SMS_loadBGPaletteHalfBrightness(void *palette)

SECTION code_clib
SECTION code_SMSlib

PUBLIC _SMS_loadBGPaletteHalfBrightness

EXTERN asm_SMSlib_loadBGPaletteHalfBrightness

defc _SMS_loadBGPaletteHalfBrightness = asm_SMSlib_loadBGPaletteHalfBrightness
