threads/mutex/c/rl_sdcc/mtx_destroy
threads/mutex/c/rl_sdcc/mtx_init
threads/mutex/c/rl_sdcc/mtx_lock
threads/mutex/c/rl_sdcc/mtx_timedlock
threads/mutex/c/rl_sdcc/mtx_trylock
threads/mutex/c/rl_sdcc/mtx_unlock
threads/mutex/c/rl_sdcc/spinlock_acquire
threads/mutex/c/rl_sdcc/spinlock_release
threads/mutex/c/rl_sdcc/spinlock_tryacquire
