/* Generated by re2c 4.4 */
//-----------------------------------------------------------------------------
// Z80 assembler
// Copyright (C) Paulo Custodio, 2011-2026
// License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
//-----------------------------------------------------------------------------

#include "errors.h"
#include "lexer.h"
#include "lexer_scan.h"
#include "source_loc.h"
#include <string>
#include <vector>
#include <charconv>

static inline int digit_value(char c) {
    if (c >= '0' && c <= '9') {
        return c - '0';
    }
    if (c >= 'a' && c <= 'z') {
        return 10 + (c - 'a');
    }
    if (c >= 'A' && c <= 'Z') {
        return 10 + (c - 'A');
    }
    return -1;
}

// Returns true on success, false on error.
// Advances idx and writes the decoded character into out_char.
static bool parse_escape(uint32_t& idx,
                         bool probing,
                         const MergedLine& line,
                         char& out_char) {
    uint32_t n = static_cast<uint32_t>(line.text.size());
    if (idx + 1 >= n) {
        if (!probing) {
            error(line.locmap[idx], "Unterminated escape sequence");
        }
        return false;
    }

    char esc = line.text[idx + 1];
    idx += 2; // consume '\' and the next char

    switch (esc) {
    case 'n':
        out_char = '\n';
        return true;
    case 't':
        out_char = '\t';
        return true;
    case 'r':
        out_char = '\r';
        return true;
    case 'v':
        out_char = '\v';
        return true;
    case 'f':
        out_char = '\f';
        return true;
    case 'e':
        out_char = '\x1b';
        return true;
    case '\\':
        out_char = '\\';
        return true;
    case '"':
        out_char = '"';
        return true;
    case '\'':
        out_char = '\'';
        return true;

    // Octal: \123
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7': {
        int value = digit_value(esc);
        for (int i = 0; i < 2 && idx < n; i++) {
            int digit = digit_value(line.text[idx]);
            if (digit >= 0 && digit < 8) {
                value = value * 8 + digit;
                idx++;
            }
            else {
                break;
            }
        }
        out_char = static_cast<char>(value & 0xFF);
        return true;
    }

    // Hex: \xFF
    case 'x': {
        if (idx >= n || !is_hex_digit(line.text[idx])) {
            if (!probing) {
                error(line.locmap[idx - 2], "Invalid hex escape");
            }
            return false;
        }
        int value = 0;
        int digits = 0;
        while (idx < n && digits < 2 && is_hex_digit(line.text[idx])) {
            value = value * 16 + digit_value(line.text[idx]);
            digits++;
            idx++;
        }
        out_char = char(value & 0xFF);
        return true;
    }

    default:
        if (!probing) {
            error(line.locmap[idx - 2], std::string("Unknown escape: \\") + esc);
        }
        return false;
    }
}

static bool scan_quoted_content(char end_quote,
                                bool allow_escapes,
                                bool probing,
                                uint32_t& idx,
                                const MergedLine& line,
                                std::string& out_content) {
    uint32_t n = static_cast<uint32_t>(line.text.size());
    idx++; // skip opening quote

    while (idx < n) {
        char c = line.text[idx];

        if (c == end_quote) {
            idx++; // consume closing quote
            return true;
        }

        if (c == '\\' && allow_escapes) {
            char decoded;
            if (!parse_escape(idx, probing, line, decoded)) {
                return false;
            }
            out_content.push_back(decoded);
            continue;
        }

        out_content.push_back(c);
        idx++;
    }

    if (!probing) {
        error(line.locmap[idx - 1], "Unterminated string literal");
    }
    idx = n;    // advance past the malformed string
    return false;
}

static void parse_string(char end_quote,
                         uint32_t& idx,
                         const MergedLine& line,
                         std::vector<Token>& out) {
    uint32_t start = idx;
    std::string content;

    if (!scan_quoted_content(end_quote,
                             /*allow_escapes=*/true,
                             /*probing=*/false,
                             idx, line, content)) {
        return;
    }

    out.push_back(Token::string(line.text.substr(start, idx - start),
                                content,
                                line.locmap[start]));
}

static void parse_char_literal(uint32_t& idx,
                               const MergedLine& line,
                               std::vector<Token>& out) {
    uint32_t start = idx;      // points at opening '
    uint32_t probe = idx;      // speculative index

    std::string content;

    // Try to parse as a quoted literal
    bool ok = scan_quoted_content('\'',
                                  /*allow_escapes=*/true,
                                  /*probing=*/true,
                                  probe,
                                  line,
                                  content);

    // valid character literal if scan succeeded and consumed
    // exactly one character
    if (ok && content.size() == 1) {
        idx = probe; // commit
        out.push_back(Token::integer(line.text.substr(start, idx - start),
                                     static_cast<int>(content[0]),
                                     line.locmap[start]));
        return;
    }

    // Else this is a Tick token.
    out.push_back(Token::token(TokenType::Tick, "'", line.locmap[start]));
    idx++; // consume '
    return;
}

static void parse_raw_string(char end_quote,
                             uint32_t& idx,
                             const MergedLine& line,
                             std::vector<Token>& out) {
    uint32_t start = idx;
    std::string content;

    if (!scan_quoted_content(end_quote,
                             /*allow_escapes=*/false,
                             /*probing=*/false,
                             idx, line, content)) {
        return;
    }

    out.push_back(Token::string(line.text.substr(start, idx - start),
                                content,
                                line.locmap[start]));
}

static double parse_float_from_chars(const std::string_view s) {
    std::string t;
    t.reserve(s.size());
    for (char c : s) {
        if (c != '_') {
            t.push_back(c);
        }
    }
    return std::stod(t);
}

static int parse_int_from_chars(const std::string_view s, int base) {
    // Remove underscores
    std::string t;
    t.reserve(s.size());
    for (char c : s) {
        if (c != '_') {
            t.push_back(c);
        }
    }

    int value = 0;
    std::from_chars(t.data(), t.data() + t.size(), value, base);
    return value;
}

void tokenize_line(const MergedLine& line,
                   TokenizeState& state,
                   std::vector<Token>& out) {
    bool raw_strings = false;  // whether to treat string literals as raw (no escapes)

    const char* p = line.text.c_str();
    const char* limit = p + line.text.size();
    uint32_t idx = 0, start = 0;
    uint32_t end = static_cast<uint32_t>(line.text.size());
    auto current_loc = [&]() -> SourceLoc {
        return line.locmap[idx];
    };

    auto check_trailing_char = [&]() -> bool {
        if (is_ident_char(*p)) {
            error(current_loc(),
                  "Invalid character '" + std::string(1, *p) +
                  "' after literal: '" +
                  line.text.substr(start, p - line.text.c_str() - start) + "'");
            return false;
        }
        return true;
    };

    auto emit = [&](TokenType type) {
        std::string token_text = line.text.substr(start, p - line.text.c_str() - start);
        out.push_back(Token::token(type, token_text, current_loc()));
    };

    for (; idx < end; idx = static_cast<uint32_t>(p - line.text.c_str())) {
        // ------------------------------------------------------------
        // 1. If we are inside a multi-line comment, skip until "*/"
        // ------------------------------------------------------------
        if (state.in_multiline_comment) {
            while (idx + 1 < end) {
                if (line.text[idx] == '*' && line.text[idx + 1] == '/') {
                    idx += 2;
                    state.in_multiline_comment = false;
                    state.multiline_comment_start = SourceLoc();
                    goto continue_lexing;
                }
                idx++;
            }
            // Reached end of line still inside comment
            return;
        }

        // ------------------------------------------------------------
        // 2. Check for start of multi-line comment BEFORE re2c runs
        // ------------------------------------------------------------
        if (idx + 1 < end &&
                line.text[idx] == '/' &&
                line.text[idx + 1] == '*') {
            state.in_multiline_comment = true;
            state.multiline_comment_start = current_loc();
            idx += 2;
            continue;
        }

continue_lexing:
        // ------------------------------------------------------------
        // 3. Now run re2c on the remaining text
        // ------------------------------------------------------------
        start = idx;
        p = line.text.c_str() + idx;
        const char* tok = p;
        const char* marker = nullptr;


        {
            char yych;
            unsigned int yyaccept = 0;
            yych = *p;
            switch (yych) {
            case '\t':
            case '\n':
            case '\v':
            case '\f':
            case '\r':
            case ' ':
                goto yy2;
            case '!':
                goto yy4;
            case '"':
                goto yy6;
            case '#':
                goto yy7;
            case '$':
                goto yy9;
            case '%':
                goto yy11;
            case '&':
                goto yy13;
            case '\'':
                goto yy15;
            case '(':
                goto yy16;
            case ')':
                goto yy17;
            case '*':
                goto yy18;
            case '+':
                goto yy20;
            case ',':
                goto yy21;
            case '-':
                goto yy22;
            case '.':
                goto yy23;
            case '/':
                goto yy25;
            case '0':
                goto yy27;
            case '1':
                goto yy29;
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy31;
            case ':':
                goto yy32;
            case ';':
                goto yy33;
            case '<':
                goto yy34;
            case '=':
                goto yy36;
            case '>':
                goto yy38;
            case '?':
                goto yy40;
            case '@':
                goto yy41;
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
                goto yy43;
            case '[':
                goto yy45;
            case '\\':
                goto yy46;
            case ']':
                goto yy47;
            case '^':
                goto yy48;
            case '{':
                goto yy50;
            case '|':
                goto yy51;
            case '}':
                goto yy53;
            case '~':
                goto yy54;
            default:
                if (limit <= p) {
                    goto yy102;
                }
                goto yy1;
            }
yy1:
            ++p;
            {
                error(current_loc(), "Unexpected character: '" +
                      std::string(tok, p) + "'");
                return;
            }
yy2:
            yych = *++p;
            switch (yych) {
            case '\t':
            case '\n':
            case '\v':
            case '\f':
            case '\r':
            case ' ':
                goto yy2;
            default:
                goto yy3;
            }
yy3: {
                continue;
            }
yy4:
            yych = *++p;
            switch (yych) {
            case '=':
                goto yy55;
            default:
                goto yy5;
            }
yy5: {
                emit(TokenType::LogicalNot);
                continue;
            }
yy6:
            ++p;
            {
                if (raw_strings) {
                    parse_raw_string('"', idx, line, out);
                }
                else {
                    parse_string('"', idx, line, out);
                }
                p = line.text.c_str() + idx;
                continue;
            }
yy7:
            yych = *++p;
            switch (yych) {
            case '#':
                goto yy56;
            default:
                goto yy8;
            }
yy8: {
                emit(TokenType::Hash);
                continue;
            }
yy9:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy57;
            default:
                goto yy10;
            }
yy10: {
                emit(TokenType::Dollar);
                continue;
            }
yy11:
            yyaccept = 0;
            yych = *(marker = ++p);
            switch (yych) {
            case '"':
                goto yy59;
            case '0':
            case '1':
                goto yy61;
            default:
                goto yy12;
            }
yy12: {
                emit(TokenType::Modulo);
                continue;
            }
yy13:
            yych = *++p;
            switch (yych) {
            case '&':
                goto yy63;
            default:
                goto yy14;
            }
yy14: {
                emit(TokenType::BitwiseAnd);
                continue;
            }
yy15:
            ++p;
            {
                parse_char_literal(idx, line, out);
                p = line.text.c_str() + idx;
                continue;
            }
yy16:
            ++p;
            {
                emit(TokenType::LeftParen);
                continue;
            }
yy17:
            ++p;
            {
                emit(TokenType::RightParen);
                continue;
            }
yy18:
            yych = *++p;
            switch (yych) {
            case '*':
                goto yy64;
            default:
                goto yy19;
            }
yy19: {
                emit(TokenType::Multiply);
                continue;
            }
yy20:
            ++p;
            {
                emit(TokenType::Plus);
                continue;
            }
yy21:
            ++p;
            {
                emit(TokenType::Comma);
                continue;
            }
yy22:
            ++p;
            {
                emit(TokenType::Minus);
                continue;
            }
yy23:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy65;
            default:
                goto yy24;
            }
yy24: {
                emit(TokenType::Dot);
                continue;
            }
yy25:
            yych = *++p;
            switch (yych) {
            case '/':
                goto yy68;
            default:
                goto yy26;
            }
yy26: {
                emit(TokenType::Divide);
                continue;
            }
yy27:
            yyaccept = 1;
            yych = *(marker = ++p);
            switch (yych) {
            case 0x00:
                goto yy28;
            case 'B':
            case 'b':
                goto yy71;
            case 'X':
            case 'x':
                goto yy75;
            default:
                goto yy30;
            }
yy28: {
                if (!check_trailing_char()) {
                    return;
                }
                std::string digits = std::string(tok, p);
                if (digits.back() == 'd' || digits.back() == 'D') {
                    digits.pop_back();
                }
                int value = parse_int_from_chars(digits.c_str(), 10);
                out.push_back(Token::integer(std::string(tok, p), value, current_loc()));
                continue;
            }
yy29:
            yyaccept = 1;
            yych = *(marker = ++p);
yy30:
            switch (yych) {
            case '.':
                goto yy69;
            case '0':
            case '1':
                goto yy29;
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy31;
            case 'A':
            case 'C':
            case 'E':
            case 'F':
            case 'a':
            case 'c':
            case 'e':
            case 'f':
                goto yy70;
            case 'B':
            case 'b':
                goto yy77;
            case 'D':
            case 'd':
                goto yy73;
            case 'H':
            case 'h':
                goto yy74;
            case '_':
                goto yy76;
            default:
                goto yy28;
            }
yy31:
            yyaccept = 1;
            yych = *(marker = ++p);
            switch (yych) {
            case '.':
                goto yy69;
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy31;
            case 'A':
            case 'B':
            case 'C':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'e':
            case 'f':
                goto yy70;
            case 'D':
            case 'd':
                goto yy73;
            case 'H':
            case 'h':
                goto yy74;
            case '_':
                goto yy78;
            default:
                goto yy28;
            }
yy32:
            ++p;
            {
                emit(TokenType::Colon);
                continue;
            }
yy33:
            ++p;
            {
                return;
            }
yy34:
            yych = *++p;
            switch (yych) {
            case '<':
                goto yy79;
            case '=':
                goto yy80;
            case '>':
                goto yy55;
            default:
                goto yy35;
            }
yy35: {
                if (raw_strings) {
                    parse_raw_string('>', idx, line, out);
                    p = line.text.c_str() + idx;
                    continue;
                }
                else {
                    emit(TokenType::LT);
                    continue;
                }
            }
yy36:
            yych = *++p;
            switch (yych) {
            case '=':
                goto yy81;
            default:
                goto yy37;
            }
yy37: {
                emit(TokenType::EQ);
                continue;
            }
yy38:
            yych = *++p;
            switch (yych) {
            case '=':
                goto yy82;
            case '>':
                goto yy83;
            default:
                goto yy39;
            }
yy39: {
                emit(TokenType::GT);
                continue;
            }
yy40:
            ++p;
            {
                emit(TokenType::Question);
                continue;
            }
yy41:
            yyaccept = 2;
            yych = *(marker = ++p);
            switch (yych) {
            case '"':
                goto yy59;
            case '0':
            case '1':
                goto yy61;
            default:
                goto yy42;
            }
yy42: {
                emit(TokenType::At);
                continue;
            }
yy43:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
                goto yy43;
            default:
                goto yy44;
            }
yy44: {
                std::string ident = std::string(tok, p);
                Keyword keyword = keyword_lookup(ident);

                // check for ASMPC
                if (keyword == Keyword::ASMPC) {
                    out.push_back(Token::token(TokenType::ASMPC, ident, current_loc()));
                    continue;
                }

                // need raw strings after INCLUDE, BINARY, INCBIN, LINE, C_LINE
                if (keyword_directive_has_file_arg(keyword)) {
                    raw_strings = true;
                }

                out.push_back(Token::identifier(ident, current_loc()));
                continue;
            }
yy45:
            ++p;
            {
                emit(TokenType::LeftBracket);
                continue;
            }
yy46:
            ++p;
            {
                emit(TokenType::Backslash);
                continue;
            }
yy47:
            ++p;
            {
                emit(TokenType::RightBracket);
                continue;
            }
yy48:
            yych = *++p;
            switch (yych) {
            case '^':
                goto yy84;
            default:
                goto yy49;
            }
yy49: {
                emit(TokenType::BitwiseXor);
                continue;
            }
yy50:
            ++p;
            {
                emit(TokenType::LeftBrace);
                continue;
            }
yy51:
            yych = *++p;
            switch (yych) {
            case '|':
                goto yy85;
            default:
                goto yy52;
            }
yy52: {
                emit(TokenType::BitwiseOr);
                continue;
            }
yy53:
            ++p;
            {
                emit(TokenType::RightBrace);
                continue;
            }
yy54:
            ++p;
            {
                emit(TokenType::BitwiseNot);
                continue;
            }
yy55:
            ++p;
            {
                emit(TokenType::NE);
                continue;
            }
yy56:
            ++p;
            {
                emit(TokenType::DoubleHash);
                continue;
            }
yy57:
            yyaccept = 3;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy57;
            case '_':
                goto yy86;
            default:
                goto yy58;
            }
yy58: {
                if (!check_trailing_char()) {
                    return;
                }
                std::string digits = std::string(tok + 1, p);
                int value = parse_int_from_chars(digits.c_str(), 16);
                out.push_back(Token::integer(std::string(tok, p), value, current_loc()));
                continue;
            }
yy59:
            yych = *++p;
            switch (yych) {
            case '"':
                goto yy87;
            case '#':
            case '-':
                goto yy59;
            default:
                goto yy60;
            }
yy60:
            p = marker;
            switch (yyaccept) {
            case 0:
                goto yy12;
            case 1:
                goto yy28;
            case 2:
                goto yy42;
            case 3:
                goto yy58;
            case 4:
                goto yy62;
            case 5:
                goto yy67;
            case 6:
                goto yy72;
            case 7:
                goto yy94;
            default:
                goto yy96;
            }
yy61:
            yyaccept = 4;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
                goto yy61;
            case '_':
                goto yy88;
            default:
                goto yy62;
            }
yy62: {
                if (!check_trailing_char()) {
                    return;
                }
                std::string digits = std::string(tok + 1, p);
                int value = parse_int_from_chars(digits.c_str(), 2);
                out.push_back(Token::integer(std::string(tok, p), value, current_loc()));
                continue;
            }
yy63:
            ++p;
            {
                emit(TokenType::LogicalAnd);
                continue;
            }
yy64:
            ++p;
            {
                emit(TokenType::Power);
                continue;
            }
yy65:
            yyaccept = 5;
            yych = *(marker = ++p);
yy66:
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy65;
            case 'E':
            case 'e':
                goto yy89;
            case '_':
                goto yy90;
            default:
                goto yy67;
            }
yy67: {
                if (!check_trailing_char()) {
                    return;
                }
                std::string digits = std::string(tok, p);
                double value = parse_float_from_chars(digits);
                out.push_back(Token::floating(digits, value, current_loc()));
                continue;
            }
yy68:
            ++p;
            {
                return;
            }
yy69:
            yyaccept = 5;
            yych = *(marker = ++p);
            switch (yych) {
            case 0x00:
            case '_':
                goto yy67;
            default:
                goto yy66;
            }
yy70:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy70;
            case 'H':
            case 'h':
                goto yy74;
            case '_':
                goto yy91;
            default:
                goto yy60;
            }
yy71:
            yyaccept = 6;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'H':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'h':
                goto yy93;
            case '_':
                goto yy91;
            default:
                goto yy72;
            }
yy72: {
                if (!check_trailing_char()) {
                    return;
                }
                std::string digits = std::string(tok, p - 1);
                int value = parse_int_from_chars(digits.c_str(), 2);
                out.push_back(Token::integer(std::string(tok, p), value, current_loc()));
                continue;
            }
yy73:
            yyaccept = 1;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy70;
            case 'H':
            case 'h':
                goto yy74;
            case '_':
                goto yy91;
            default:
                goto yy28;
            }
yy74:
            ++p;
            {
                if (!check_trailing_char()) {
                    return;
                }
                std::string digits = std::string(tok, p - 1);
                int value = parse_int_from_chars(digits.c_str(), 16);
                out.push_back(Token::integer(std::string(tok, p), value, current_loc()));
                continue;
            }
yy75:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy95;
            default:
                goto yy60;
            }
yy76:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
                goto yy29;
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy31;
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy70;
            case '_':
                goto yy76;
            default:
                goto yy60;
            }
yy77:
            yyaccept = 6;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy70;
            case 'H':
            case 'h':
                goto yy74;
            case '_':
                goto yy91;
            default:
                goto yy72;
            }
yy78:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy31;
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy70;
            case '_':
                goto yy78;
            default:
                goto yy60;
            }
yy79:
            ++p;
            {
                emit(TokenType::LeftShift);
                continue;
            }
yy80:
            ++p;
            {
                emit(TokenType::LE);
                continue;
            }
yy81:
            ++p;
            goto yy37;
yy82:
            ++p;
            {
                emit(TokenType::GE);
                continue;
            }
yy83:
            ++p;
            {
                emit(TokenType::RightShift);
                continue;
            }
yy84:
            ++p;
            {
                emit(TokenType::LogicalXor);
                continue;
            }
yy85:
            ++p;
            {
                emit(TokenType::LogicalOr);
                continue;
            }
yy86:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy57;
            case '_':
                goto yy86;
            default:
                goto yy60;
            }
yy87:
            ++p;
            {
                int value = 0;
                for (const char* i = tok + 2; i < p - 1; ++i) {
                    value *= 2;
                    if (*i == '#') {
                        ++value;
                    }
                }
                out.push_back(Token::integer(std::string(tok, p), value, current_loc()));
                continue;
            }
yy88:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
                goto yy61;
            case '_':
                goto yy88;
            default:
                goto yy60;
            }
yy89:
            yych = *++p;
            switch (yych) {
            case '+':
            case '-':
                goto yy97;
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy98;
            default:
                goto yy60;
            }
yy90:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy65;
            case '_':
                goto yy90;
            default:
                goto yy60;
            }
yy91:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy70;
            case '_':
                goto yy91;
            default:
                goto yy60;
            }
yy92:
            yyaccept = 7;
            yych = *(marker = ++p);
yy93:
            switch (yych) {
            case '0':
            case '1':
                goto yy92;
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy70;
            case 'H':
            case 'h':
                goto yy74;
            case '_':
                goto yy99;
            default:
                goto yy94;
            }
yy94: {
                if (!check_trailing_char()) {
                    return;
                }
                std::string digits = std::string(tok + 2, p);
                int value = parse_int_from_chars(digits.c_str(), 2);
                out.push_back(Token::integer(std::string(tok, p), value, current_loc()));
                continue;
            }
yy95:
            yyaccept = 8;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy95;
            case '_':
                goto yy100;
            default:
                goto yy96;
            }
yy96: {
                if (!check_trailing_char()) {
                    return;
                }
                std::string digits = std::string(tok + 2, p);
                int value = parse_int_from_chars(digits.c_str(), 16);
                out.push_back(Token::integer(std::string(tok, p), value, current_loc()));
                continue;
            }
yy97:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy98;
            default:
                goto yy60;
            }
yy98:
            yyaccept = 5;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy98;
            case '_':
                goto yy101;
            default:
                goto yy67;
            }
yy99:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
                goto yy92;
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy70;
            case '_':
                goto yy99;
            default:
                goto yy60;
            }
yy100:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy95;
            case '_':
                goto yy100;
            default:
                goto yy60;
            }
yy101:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy98;
            case '_':
                goto yy101;
            default:
                goto yy60;
            }
yy102: {
                return;
            }
        }

    }
}
