// generated by make_synth_trie.pl
#pragma once
#include "opcodes.h"

extern TrieNode opcodes_synth_trie_nodes[];
extern TrieTransition opcodes_synth_trie_transitions[];

extern TrieAction opcodes_synth_trie_actions[];
extern SynthBytecode opcodes_synth_trie_bytecode[];

