//-----------------------------------------------------------------------------
// Z80 assembler
// Copyright (C) Paulo Custodio, 2011-2025
// License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
//-----------------------------------------------------------------------------

#include "macros.h"
#include "opcodes.h"
#include "opcodes_tables.h"
#include <cstdint>

// map CPU to DFA_Token
const DFA_Token OpcodesParser::map_cpu_to_dfa_tokens[33] = {
    DFA_Token::None                 , // CPU::not_defined
    DFA_Token::CPU_z80              , // CPU::z80
    DFA_Token::CPU_z80_strict       , // CPU::z80_strict
    DFA_Token::CPU_z180             , // CPU::z180
    DFA_Token::CPU_ez80_z80         , // CPU::ez80_z80
    DFA_Token::CPU_ez80             , // CPU::ez80
    DFA_Token::CPU_z80n             , // CPU::z80n
    DFA_Token::CPU_r2ka             , // CPU::r2ka
    DFA_Token::CPU_r3k              , // CPU::r3k
    DFA_Token::CPU_gbz80            , // CPU::gbz80
    DFA_Token::CPU_i8080            , // CPU::i8080
    DFA_Token::CPU_i8085            , // CPU::i8085
    DFA_Token::CPU_r800             , // CPU::r800
    DFA_Token::CPU_r4k              , // CPU::r4k
    DFA_Token::CPU_r5k              , // CPU::r5k
    DFA_Token::CPU_kc160            , // CPU::kc160
    DFA_Token::CPU_kc160_z80        , // CPU::kc160_z80
    DFA_Token::CPU_i8080_strict     , // CPU::i8080_strict
    DFA_Token::CPU_i8085_strict     , // CPU::i8085_strict
    DFA_Token::CPU_gbz80_strict     , // CPU::gbz80_strict
    DFA_Token::CPU_z180_strict      , // CPU::z180_strict
    DFA_Token::CPU_z80n_strict      , // CPU::z80n_strict
    DFA_Token::CPU_ez80_z80_strict  , // CPU::ez80_z80_strict
    DFA_Token::CPU_ez80_strict      , // CPU::ez80_strict
    DFA_Token::CPU_r800_strict      , // CPU::r800_strict
    DFA_Token::CPU_kc160_strict     , // CPU::kc160_strict
    DFA_Token::CPU_kc160_z80_strict , // CPU::kc160_z80_strict
    DFA_Token::CPU_r2ka_strict      , // CPU::r2ka_strict
    DFA_Token::CPU_r3k_strict       , // CPU::r3k_strict
    DFA_Token::CPU_r4k_strict       , // CPU::r4k_strict
    DFA_Token::CPU_r5k_strict       , // CPU::r5k_strict
    DFA_Token::CPU_r6k              , // CPU::r6k
    DFA_Token::CPU_r6k_strict       , // CPU::r6k_strict
};

// map Keyword to DFA_Token
const DFA_Token OpcodesParser::map_keyword_to_dfa_tokens[614] = {
    DFA_Token::None                 , // Keyword::None
    DFA_Token::KW_A                 , // Keyword::A
    DFA_Token::KW_A_                , // Keyword::A_
    DFA_Token::KW_ABC               , // Keyword::ABC
    DFA_Token::KW_ACI               , // Keyword::ACI
    DFA_Token::KW_ADC               , // Keyword::ADC
    DFA_Token::KW_ADD               , // Keyword::ADD
    DFA_Token::KW_ADE               , // Keyword::ADE
    DFA_Token::KW_ADI               , // Keyword::ADI
    DFA_Token::KW_AESIMC            , // Keyword::AESIMC
    DFA_Token::KW_AESISR            , // Keyword::AESISR
    DFA_Token::KW_AESMC             , // Keyword::AESMC
    DFA_Token::KW_AESSR             , // Keyword::AESSR
    DFA_Token::KW_AF                , // Keyword::AF
    DFA_Token::KW_AF_               , // Keyword::AF_
    DFA_Token::KW_AHL               , // Keyword::AHL
    DFA_Token::KW_AIX               , // Keyword::AIX
    DFA_Token::KW_AIY               , // Keyword::AIY
    DFA_Token::KW_ALTD              , // Keyword::ALTD
    DFA_Token::KW_ALTS              , // Keyword::ALTS
    DFA_Token::KW_ALTSD             , // Keyword::ALTSD
    DFA_Token::KW_ANA               , // Keyword::ANA
    DFA_Token::KW_AND               , // Keyword::AND
    DFA_Token::KW_ANI               , // Keyword::ANI
    DFA_Token::KW_ARHL              , // Keyword::ARHL
    DFA_Token::None                 , // Keyword::ASMPC
    DFA_Token::KW_ASP               , // Keyword::ASP
    DFA_Token::None                 , // Keyword::ASSUME
    DFA_Token::KW_B                 , // Keyword::B
    DFA_Token::KW_B_                , // Keyword::B_
    DFA_Token::KW_BC                , // Keyword::BC
    DFA_Token::KW_BC_               , // Keyword::BC_
    DFA_Token::KW_BCDE              , // Keyword::BCDE
    DFA_Token::KW_BCDE_             , // Keyword::BCDE_
    DFA_Token::None                 , // Keyword::BINARY
    DFA_Token::KW_BIT               , // Keyword::BIT
    DFA_Token::KW_BOOL              , // Keyword::BOOL
    DFA_Token::None                 , // Keyword::BREAK
    DFA_Token::KW_BRLC              , // Keyword::BRLC
    DFA_Token::KW_BSLA              , // Keyword::BSLA
    DFA_Token::KW_BSRA              , // Keyword::BSRA
    DFA_Token::KW_BSRF              , // Keyword::BSRF
    DFA_Token::KW_BSRL              , // Keyword::BSRL
    DFA_Token::KW_C                 , // Keyword::C
    DFA_Token::KW_C_                , // Keyword::C_
    DFA_Token::KW_C_C               , // Keyword::C_C
    DFA_Token::KW_C_EQ              , // Keyword::C_EQ
    DFA_Token::KW_C_GEU             , // Keyword::C_GEU
    DFA_Token::KW_C_GTU             , // Keyword::C_GTU
    DFA_Token::KW_C_LEU             , // Keyword::C_LEU
    DFA_Token::None                 , // Keyword::C_LINE
    DFA_Token::KW_C_LO              , // Keyword::C_LO
    DFA_Token::KW_C_LTU             , // Keyword::C_LTU
    DFA_Token::KW_C_LZ              , // Keyword::C_LZ
    DFA_Token::KW_C_M               , // Keyword::C_M
    DFA_Token::KW_C_NC              , // Keyword::C_NC
    DFA_Token::KW_C_NE              , // Keyword::C_NE
    DFA_Token::KW_C_NV              , // Keyword::C_NV
    DFA_Token::KW_C_NZ              , // Keyword::C_NZ
    DFA_Token::KW_C_P               , // Keyword::C_P
    DFA_Token::KW_C_PE              , // Keyword::C_PE
    DFA_Token::KW_C_PO              , // Keyword::C_PO
    DFA_Token::KW_C_V               , // Keyword::C_V
    DFA_Token::KW_C_Z               , // Keyword::C_Z
    DFA_Token::KW_CALL              , // Keyword::CALL
    DFA_Token::KW_CALL3             , // Keyword::CALL3
    DFA_Token::KW_CBM               , // Keyword::CBM
    DFA_Token::KW_CC                , // Keyword::CC
    DFA_Token::KW_CCF               , // Keyword::CCF
    DFA_Token::KW_CCF_              , // Keyword::CCF_
    DFA_Token::KW_CEQ               , // Keyword::CEQ
    DFA_Token::KW_CGEU              , // Keyword::CGEU
    DFA_Token::KW_CGTU              , // Keyword::CGTU
    DFA_Token::KW_CLEU              , // Keyword::CLEU
    DFA_Token::KW_CLO               , // Keyword::CLO
    DFA_Token::KW_CLR               , // Keyword::CLR
    DFA_Token::KW_CLTU              , // Keyword::CLTU
    DFA_Token::KW_CLZ               , // Keyword::CLZ
    DFA_Token::KW_CM                , // Keyword::CM
    DFA_Token::KW_CMA               , // Keyword::CMA
    DFA_Token::KW_CMC               , // Keyword::CMC
    DFA_Token::KW_CMP               , // Keyword::CMP
    DFA_Token::KW_CNC               , // Keyword::CNC
    DFA_Token::KW_CNE               , // Keyword::CNE
    DFA_Token::KW_CNV               , // Keyword::CNV
    DFA_Token::KW_CNVC              , // Keyword::CNVC
    DFA_Token::KW_CNVD              , // Keyword::CNVD
    DFA_Token::KW_CNZ               , // Keyword::CNZ
    DFA_Token::None                 , // Keyword::CONTINUE
    DFA_Token::KW_CONVC             , // Keyword::CONVC
    DFA_Token::KW_CONVD             , // Keyword::CONVD
    DFA_Token::KW_COPY              , // Keyword::COPY
    DFA_Token::KW_COPYR             , // Keyword::COPYR
    DFA_Token::KW_CP                , // Keyword::CP
    DFA_Token::KW_CPD               , // Keyword::CPD
    DFA_Token::KW_CPDR              , // Keyword::CPDR
    DFA_Token::KW_CPE               , // Keyword::CPE
    DFA_Token::KW_CPI               , // Keyword::CPI
    DFA_Token::KW_CPIR              , // Keyword::CPIR
    DFA_Token::KW_CPL               , // Keyword::CPL
    DFA_Token::KW_CPO               , // Keyword::CPO
    DFA_Token::KW_CV                , // Keyword::CV
    DFA_Token::KW_CZ                , // Keyword::CZ
    DFA_Token::KW_D                 , // Keyword::D
    DFA_Token::KW_D_                , // Keyword::D_
    DFA_Token::KW_DAA               , // Keyword::DAA
    DFA_Token::KW_DAD               , // Keyword::DAD
    DFA_Token::None                 , // Keyword::DB
    DFA_Token::KW_DCR               , // Keyword::DCR
    DFA_Token::KW_DCX               , // Keyword::DCX
    DFA_Token::KW_DE                , // Keyword::DE
    DFA_Token::KW_DE_               , // Keyword::DE_
    DFA_Token::KW_DEC               , // Keyword::DEC
    DFA_Token::None                 , // Keyword::DEFB
    DFA_Token::None                 , // Keyword::DEFC
    DFA_Token::None                 , // Keyword::DEFINE
    DFA_Token::None                 , // Keyword::DEFL
    DFA_Token::None                 , // Keyword::DEFM
    DFA_Token::None                 , // Keyword::DEFP
    DFA_Token::None                 , // Keyword::DEFQ
    DFA_Token::None                 , // Keyword::DEFS
    DFA_Token::None                 , // Keyword::DEFW
    DFA_Token::KW_DEHL              , // Keyword::DEHL
    DFA_Token::KW_DI                , // Keyword::DI
    DFA_Token::KW_DIV               , // Keyword::DIV
    DFA_Token::KW_DIVS              , // Keyword::DIVS
    DFA_Token::KW_DJNZ              , // Keyword::DJNZ
    DFA_Token::KW_DSUB              , // Keyword::DSUB
    DFA_Token::None                 , // Keyword::DW
    DFA_Token::KW_DWJNZ             , // Keyword::DWJNZ
    DFA_Token::KW_E                 , // Keyword::E
    DFA_Token::KW_E_                , // Keyword::E_
    DFA_Token::KW_EI                , // Keyword::EI
    DFA_Token::KW_EIR               , // Keyword::EIR
    DFA_Token::None                 , // Keyword::ELIF
    DFA_Token::None                 , // Keyword::ELIFDEF
    DFA_Token::None                 , // Keyword::ELIFNDEF
    DFA_Token::None                 , // Keyword::ELSE
    DFA_Token::None                 , // Keyword::ELSEIF
    DFA_Token::None                 , // Keyword::ELSEIFDEF
    DFA_Token::None                 , // Keyword::ELSEIFNDEF
    DFA_Token::None                 , // Keyword::ENDIF
    DFA_Token::None                 , // Keyword::ENDM
    DFA_Token::None                 , // Keyword::ENDR
    DFA_Token::None                 , // Keyword::ENDW
    DFA_Token::None                 , // Keyword::ENDWHILE
    DFA_Token::KW_EQ                , // Keyword::EQ
    DFA_Token::None                 , // Keyword::EQU
    DFA_Token::KW_EX                , // Keyword::EX
    DFA_Token::None                 , // Keyword::EXITM
    DFA_Token::KW_EXP               , // Keyword::EXP
    DFA_Token::KW_EXX               , // Keyword::EXX
    DFA_Token::KW_F                 , // Keyword::F
    DFA_Token::None                 , // Keyword::F_
    DFA_Token::KW_FLAG              , // Keyword::FLAG
    DFA_Token::KW_FSYSCALL          , // Keyword::FSYSCALL
    DFA_Token::KW_GE                , // Keyword::GE
    DFA_Token::KW_GEU               , // Keyword::GEU
    DFA_Token::KW_GT                , // Keyword::GT
    DFA_Token::KW_GTU               , // Keyword::GTU
    DFA_Token::KW_H                 , // Keyword::H
    DFA_Token::KW_H_                , // Keyword::H_
    DFA_Token::KW_HALT              , // Keyword::HALT
    DFA_Token::KW_HL                , // Keyword::HL
    DFA_Token::KW_HL_               , // Keyword::HL_
    DFA_Token::KW_HLD               , // Keyword::HLD
    DFA_Token::KW_HLI               , // Keyword::HLI
    DFA_Token::KW_HLT               , // Keyword::HLT
    DFA_Token::KW_HTR               , // Keyword::HTR
    DFA_Token::KW_I                 , // Keyword::I
    DFA_Token::KW_IBOX              , // Keyword::IBOX
    DFA_Token::KW_IDET              , // Keyword::IDET
    DFA_Token::None                 , // Keyword::IF
    DFA_Token::None                 , // Keyword::IFDEF
    DFA_Token::None                 , // Keyword::IFNDEF
    DFA_Token::KW_IIR               , // Keyword::IIR
    DFA_Token::KW_IL                , // Keyword::IL
    DFA_Token::KW_IM                , // Keyword::IM
    DFA_Token::KW_IN                , // Keyword::IN
    DFA_Token::KW_IN0               , // Keyword::IN0
    DFA_Token::KW_INC               , // Keyword::INC
    DFA_Token::None                 , // Keyword::INCBIN
    DFA_Token::None                 , // Keyword::INCLUDE
    DFA_Token::KW_IND               , // Keyword::IND
    DFA_Token::KW_IND2              , // Keyword::IND2
    DFA_Token::KW_IND2R             , // Keyword::IND2R
    DFA_Token::KW_INDM              , // Keyword::INDM
    DFA_Token::KW_INDMR             , // Keyword::INDMR
    DFA_Token::KW_INDR              , // Keyword::INDR
    DFA_Token::KW_INDRX             , // Keyword::INDRX
    DFA_Token::KW_INI               , // Keyword::INI
    DFA_Token::KW_INI2              , // Keyword::INI2
    DFA_Token::KW_INI2R             , // Keyword::INI2R
    DFA_Token::KW_INIM              , // Keyword::INIM
    DFA_Token::KW_INIMR             , // Keyword::INIMR
    DFA_Token::KW_INIR              , // Keyword::INIR
    DFA_Token::KW_INIRX             , // Keyword::INIRX
    DFA_Token::KW_INR               , // Keyword::INR
    DFA_Token::KW_INX               , // Keyword::INX
    DFA_Token::KW_IOE               , // Keyword::IOE
    DFA_Token::KW_IOI               , // Keyword::IOI
    DFA_Token::KW_IP                , // Keyword::IP
    DFA_Token::KW_IPRES             , // Keyword::IPRES
    DFA_Token::KW_IPSET             , // Keyword::IPSET
    DFA_Token::KW_IS                , // Keyword::IS
    DFA_Token::KW_IX                , // Keyword::IX
    DFA_Token::KW_IXH               , // Keyword::IXH
    DFA_Token::KW_IXL               , // Keyword::IXL
    DFA_Token::KW_IY                , // Keyword::IY
    DFA_Token::KW_IYH               , // Keyword::IYH
    DFA_Token::KW_IYL               , // Keyword::IYL
    DFA_Token::KW_J_C               , // Keyword::J_C
    DFA_Token::KW_J_EQ              , // Keyword::J_EQ
    DFA_Token::KW_J_GE              , // Keyword::J_GE
    DFA_Token::KW_J_GEU             , // Keyword::J_GEU
    DFA_Token::KW_J_GT              , // Keyword::J_GT
    DFA_Token::KW_J_GTU             , // Keyword::J_GTU
    DFA_Token::KW_J_LE              , // Keyword::J_LE
    DFA_Token::KW_J_LEU             , // Keyword::J_LEU
    DFA_Token::KW_J_LO              , // Keyword::J_LO
    DFA_Token::KW_J_LT              , // Keyword::J_LT
    DFA_Token::KW_J_LTU             , // Keyword::J_LTU
    DFA_Token::KW_J_LZ              , // Keyword::J_LZ
    DFA_Token::KW_J_M               , // Keyword::J_M
    DFA_Token::KW_J_NC              , // Keyword::J_NC
    DFA_Token::KW_J_NE              , // Keyword::J_NE
    DFA_Token::KW_J_NV              , // Keyword::J_NV
    DFA_Token::KW_J_NZ              , // Keyword::J_NZ
    DFA_Token::KW_J_P               , // Keyword::J_P
    DFA_Token::KW_J_PE              , // Keyword::J_PE
    DFA_Token::KW_J_PO              , // Keyword::J_PO
    DFA_Token::KW_J_V               , // Keyword::J_V
    DFA_Token::KW_J_Z               , // Keyword::J_Z
    DFA_Token::KW_JC                , // Keyword::JC
    DFA_Token::KW_JEQ               , // Keyword::JEQ
    DFA_Token::KW_JGE               , // Keyword::JGE
    DFA_Token::KW_JGEU              , // Keyword::JGEU
    DFA_Token::KW_JGT               , // Keyword::JGT
    DFA_Token::KW_JGTU              , // Keyword::JGTU
    DFA_Token::KW_JK                , // Keyword::JK
    DFA_Token::KW_JK_               , // Keyword::JK_
    DFA_Token::KW_JKHL              , // Keyword::JKHL
    DFA_Token::KW_JKHL_             , // Keyword::JKHL_
    DFA_Token::KW_JLE               , // Keyword::JLE
    DFA_Token::KW_JLEU              , // Keyword::JLEU
    DFA_Token::KW_JLO               , // Keyword::JLO
    DFA_Token::KW_JLT               , // Keyword::JLT
    DFA_Token::KW_JLTU              , // Keyword::JLTU
    DFA_Token::KW_JLZ               , // Keyword::JLZ
    DFA_Token::KW_JM                , // Keyword::JM
    DFA_Token::KW_JMP               , // Keyword::JMP
    DFA_Token::KW_JNC               , // Keyword::JNC
    DFA_Token::KW_JNE               , // Keyword::JNE
    DFA_Token::KW_JNK               , // Keyword::JNK
    DFA_Token::KW_JNV               , // Keyword::JNV
    DFA_Token::KW_JNX5              , // Keyword::JNX5
    DFA_Token::KW_JNZ               , // Keyword::JNZ
    DFA_Token::KW_JP                , // Keyword::JP
    DFA_Token::KW_JP3               , // Keyword::JP3
    DFA_Token::KW_JPE               , // Keyword::JPE
    DFA_Token::KW_JPO               , // Keyword::JPO
    DFA_Token::KW_JR                , // Keyword::JR
    DFA_Token::KW_JRE               , // Keyword::JRE
    DFA_Token::KW_JV                , // Keyword::JV
    DFA_Token::KW_JX5               , // Keyword::JX5
    DFA_Token::KW_JZ                , // Keyword::JZ
    DFA_Token::KW_K                 , // Keyword::K
    DFA_Token::KW_L                 , // Keyword::L
    DFA_Token::KW_L_                , // Keyword::L_
    DFA_Token::KW_LCALL             , // Keyword::LCALL
    DFA_Token::KW_LD                , // Keyword::LD
    DFA_Token::KW_LDA               , // Keyword::LDA
    DFA_Token::KW_LDAX              , // Keyword::LDAX
    DFA_Token::KW_LDD               , // Keyword::LDD
    DFA_Token::KW_LDDR              , // Keyword::LDDR
    DFA_Token::KW_LDDRX             , // Keyword::LDDRX
    DFA_Token::KW_LDDSR             , // Keyword::LDDSR
    DFA_Token::KW_LDDX              , // Keyword::LDDX
    DFA_Token::KW_LDF               , // Keyword::LDF
    DFA_Token::KW_LDH               , // Keyword::LDH
    DFA_Token::KW_LDHI              , // Keyword::LDHI
    DFA_Token::KW_LDHL              , // Keyword::LDHL
    DFA_Token::KW_LDI               , // Keyword::LDI
    DFA_Token::KW_LDIR              , // Keyword::LDIR
    DFA_Token::KW_LDIRX             , // Keyword::LDIRX
    DFA_Token::KW_LDISR             , // Keyword::LDISR
    DFA_Token::KW_LDIX              , // Keyword::LDIX
    DFA_Token::KW_LDL               , // Keyword::LDL
    DFA_Token::KW_LDP               , // Keyword::LDP
    DFA_Token::KW_LDPIRX            , // Keyword::LDPIRX
    DFA_Token::KW_LDRX              , // Keyword::LDRX
    DFA_Token::KW_LDSI              , // Keyword::LDSI
    DFA_Token::KW_LDWS              , // Keyword::LDWS
    DFA_Token::KW_LE                , // Keyword::LE
    DFA_Token::KW_LEA               , // Keyword::LEA
    DFA_Token::KW_LEU               , // Keyword::LEU
    DFA_Token::KW_LHLD              , // Keyword::LHLD
    DFA_Token::KW_LHLDE             , // Keyword::LHLDE
    DFA_Token::KW_LHLX              , // Keyword::LHLX
    DFA_Token::KW_LIL               , // Keyword::LIL
    DFA_Token::None                 , // Keyword::LINE
    DFA_Token::KW_LIRX              , // Keyword::LIRX
    DFA_Token::KW_LIS               , // Keyword::LIS
    DFA_Token::KW_LJP               , // Keyword::LJP
    DFA_Token::KW_LLCALL            , // Keyword::LLCALL
    DFA_Token::KW_LLJP              , // Keyword::LLJP
    DFA_Token::KW_LLRET             , // Keyword::LLRET
    DFA_Token::KW_LO                , // Keyword::LO
    DFA_Token::None                 , // Keyword::LOCAL
    DFA_Token::KW_LPRX              , // Keyword::LPRX
    DFA_Token::KW_LRET              , // Keyword::LRET
    DFA_Token::KW_LSDDR             , // Keyword::LSDDR
    DFA_Token::KW_LSDR              , // Keyword::LSDR
    DFA_Token::KW_LSIDR             , // Keyword::LSIDR
    DFA_Token::KW_LSIR              , // Keyword::LSIR
    DFA_Token::KW_LT                , // Keyword::LT
    DFA_Token::KW_LTU               , // Keyword::LTU
    DFA_Token::KW_LXI               , // Keyword::LXI
    DFA_Token::KW_LXPC              , // Keyword::LXPC
    DFA_Token::KW_LZ                , // Keyword::LZ
    DFA_Token::KW_M                 , // Keyword::M
    DFA_Token::None                 , // Keyword::MACRO
    DFA_Token::KW_MB                , // Keyword::MB
    DFA_Token::KW_MD5F1             , // Keyword::MD5F1
    DFA_Token::KW_MD5F2             , // Keyword::MD5F2
    DFA_Token::KW_MD5F3             , // Keyword::MD5F3
    DFA_Token::KW_MIRR              , // Keyword::MIRR
    DFA_Token::KW_MIRROR            , // Keyword::MIRROR
    DFA_Token::KW_MLT               , // Keyword::MLT
    DFA_Token::KW_MMU               , // Keyword::MMU
    DFA_Token::KW_MMU0              , // Keyword::MMU0
    DFA_Token::KW_MMU1              , // Keyword::MMU1
    DFA_Token::KW_MMU2              , // Keyword::MMU2
    DFA_Token::KW_MMU3              , // Keyword::MMU3
    DFA_Token::KW_MMU4              , // Keyword::MMU4
    DFA_Token::KW_MMU5              , // Keyword::MMU5
    DFA_Token::KW_MMU6              , // Keyword::MMU6
    DFA_Token::KW_MMU7              , // Keyword::MMU7
    DFA_Token::KW_MOV               , // Keyword::MOV
    DFA_Token::KW_MUL               , // Keyword::MUL
    DFA_Token::KW_MULS              , // Keyword::MULS
    DFA_Token::KW_MULU              , // Keyword::MULU
    DFA_Token::KW_MULUB             , // Keyword::MULUB
    DFA_Token::KW_MULUW             , // Keyword::MULUW
    DFA_Token::KW_MVI               , // Keyword::MVI
    DFA_Token::KW_NC                , // Keyword::NC
    DFA_Token::KW_NE                , // Keyword::NE
    DFA_Token::KW_NEG               , // Keyword::NEG
    DFA_Token::KW_NEXTREG           , // Keyword::NEXTREG
    DFA_Token::KW_NK                , // Keyword::NK
    DFA_Token::KW_NOP               , // Keyword::NOP
    DFA_Token::KW_NREG              , // Keyword::NREG
    DFA_Token::KW_NV                , // Keyword::NV
    DFA_Token::KW_NX5               , // Keyword::NX5
    DFA_Token::KW_NZ                , // Keyword::NZ
    DFA_Token::None                 , // Keyword::ONCE
    DFA_Token::KW_OR                , // Keyword::OR
    DFA_Token::KW_ORA               , // Keyword::ORA
    DFA_Token::KW_ORI               , // Keyword::ORI
    DFA_Token::KW_OTD2R             , // Keyword::OTD2R
    DFA_Token::KW_OTDM              , // Keyword::OTDM
    DFA_Token::KW_OTDMR             , // Keyword::OTDMR
    DFA_Token::KW_OTDR              , // Keyword::OTDR
    DFA_Token::KW_OTDRX             , // Keyword::OTDRX
    DFA_Token::KW_OTI2R             , // Keyword::OTI2R
    DFA_Token::KW_OTIB              , // Keyword::OTIB
    DFA_Token::KW_OTIM              , // Keyword::OTIM
    DFA_Token::KW_OTIMR             , // Keyword::OTIMR
    DFA_Token::KW_OTIR              , // Keyword::OTIR
    DFA_Token::KW_OTIRX             , // Keyword::OTIRX
    DFA_Token::KW_OUT               , // Keyword::OUT
    DFA_Token::KW_OUT0              , // Keyword::OUT0
    DFA_Token::KW_OUTD              , // Keyword::OUTD
    DFA_Token::KW_OUTD2             , // Keyword::OUTD2
    DFA_Token::KW_OUTI              , // Keyword::OUTI
    DFA_Token::KW_OUTI2             , // Keyword::OUTI2
    DFA_Token::KW_OUTINB            , // Keyword::OUTINB
    DFA_Token::KW_OVRST8            , // Keyword::OVRST8
    DFA_Token::KW_P                 , // Keyword::P
    DFA_Token::KW_PBC               , // Keyword::PBC
    DFA_Token::KW_PCHL              , // Keyword::PCHL
    DFA_Token::KW_PDE               , // Keyword::PDE
    DFA_Token::KW_PE                , // Keyword::PE
    DFA_Token::KW_PEA               , // Keyword::PEA
    DFA_Token::KW_PHL               , // Keyword::PHL
    DFA_Token::KW_PIX               , // Keyword::PIX
    DFA_Token::KW_PIXELAD           , // Keyword::PIXELAD
    DFA_Token::KW_PIXELDN           , // Keyword::PIXELDN
    DFA_Token::KW_PIY               , // Keyword::PIY
    DFA_Token::KW_PLDD              , // Keyword::PLDD
    DFA_Token::KW_PLDDR             , // Keyword::PLDDR
    DFA_Token::KW_PLDDSR            , // Keyword::PLDDSR
    DFA_Token::KW_PLDI              , // Keyword::PLDI
    DFA_Token::KW_PLDIR             , // Keyword::PLDIR
    DFA_Token::KW_PLDISR            , // Keyword::PLDISR
    DFA_Token::KW_PLSDDR            , // Keyword::PLSDDR
    DFA_Token::KW_PLSDR             , // Keyword::PLSDR
    DFA_Token::KW_PLSIDR            , // Keyword::PLSIDR
    DFA_Token::KW_PLSIR             , // Keyword::PLSIR
    DFA_Token::KW_PO                , // Keyword::PO
    DFA_Token::KW_POP               , // Keyword::POP
    DFA_Token::KW_PP                , // Keyword::PP
    DFA_Token::None                 , // Keyword::PRAGMA
    DFA_Token::KW_PSW               , // Keyword::PSW
    DFA_Token::KW_PUMA              , // Keyword::PUMA
    DFA_Token::KW_PUMS              , // Keyword::PUMS
    DFA_Token::KW_PUSH              , // Keyword::PUSH
    DFA_Token::KW_PW                , // Keyword::PW
    DFA_Token::KW_PW_               , // Keyword::PW_
    DFA_Token::KW_PX                , // Keyword::PX
    DFA_Token::KW_PX_               , // Keyword::PX_
    DFA_Token::KW_PXAD              , // Keyword::PXAD
    DFA_Token::KW_PXDN              , // Keyword::PXDN
    DFA_Token::KW_PY                , // Keyword::PY
    DFA_Token::KW_PY_               , // Keyword::PY_
    DFA_Token::KW_PZ                , // Keyword::PZ
    DFA_Token::KW_PZ_               , // Keyword::PZ_
    DFA_Token::KW_R                 , // Keyword::R
    DFA_Token::KW_R_C               , // Keyword::R_C
    DFA_Token::KW_R_EQ              , // Keyword::R_EQ
    DFA_Token::KW_R_GEU             , // Keyword::R_GEU
    DFA_Token::KW_R_GTU             , // Keyword::R_GTU
    DFA_Token::KW_R_LEU             , // Keyword::R_LEU
    DFA_Token::KW_R_LO              , // Keyword::R_LO
    DFA_Token::KW_R_LTU             , // Keyword::R_LTU
    DFA_Token::KW_R_LZ              , // Keyword::R_LZ
    DFA_Token::KW_R_M               , // Keyword::R_M
    DFA_Token::KW_R_NC              , // Keyword::R_NC
    DFA_Token::KW_R_NE              , // Keyword::R_NE
    DFA_Token::KW_R_NV              , // Keyword::R_NV
    DFA_Token::KW_R_NZ              , // Keyword::R_NZ
    DFA_Token::KW_R_P               , // Keyword::R_P
    DFA_Token::KW_R_PE              , // Keyword::R_PE
    DFA_Token::KW_R_PO              , // Keyword::R_PO
    DFA_Token::KW_R_V               , // Keyword::R_V
    DFA_Token::KW_R_Z               , // Keyword::R_Z
    DFA_Token::KW_RAL               , // Keyword::RAL
    DFA_Token::KW_RAR               , // Keyword::RAR
    DFA_Token::KW_RC                , // Keyword::RC
    DFA_Token::KW_RDEL              , // Keyword::RDEL
    DFA_Token::KW_RDMODE            , // Keyword::RDMODE
    DFA_Token::None                 , // Keyword::REPEAT
    DFA_Token::None                 , // Keyword::REPT
    DFA_Token::None                 , // Keyword::REPTC
    DFA_Token::None                 , // Keyword::REPTI
    DFA_Token::KW_REQ               , // Keyword::REQ
    DFA_Token::KW_RES               , // Keyword::RES
    DFA_Token::KW_RET               , // Keyword::RET
    DFA_Token::KW_RET3              , // Keyword::RET3
    DFA_Token::KW_RETI              , // Keyword::RETI
    DFA_Token::KW_RETN              , // Keyword::RETN
    DFA_Token::KW_RETN3             , // Keyword::RETN3
    DFA_Token::KW_RGEU              , // Keyword::RGEU
    DFA_Token::KW_RGTU              , // Keyword::RGTU
    DFA_Token::KW_RIM               , // Keyword::RIM
    DFA_Token::KW_RL                , // Keyword::RL
    DFA_Token::KW_RL1REG            , // Keyword::RL1REG
    DFA_Token::KW_RL2REG            , // Keyword::RL2REG
    DFA_Token::KW_RL3REG            , // Keyword::RL3REG
    DFA_Token::KW_RL4REG            , // Keyword::RL4REG
    DFA_Token::KW_RL5REG            , // Keyword::RL5REG
    DFA_Token::KW_RL6REG            , // Keyword::RL6REG
    DFA_Token::KW_RL7REG            , // Keyword::RL7REG
    DFA_Token::KW_RL8REG            , // Keyword::RL8REG
    DFA_Token::KW_RLA               , // Keyword::RLA
    DFA_Token::KW_RLA_              , // Keyword::RLA_
    DFA_Token::KW_RLB               , // Keyword::RLB
    DFA_Token::KW_RLC               , // Keyword::RLC
    DFA_Token::KW_RLCA              , // Keyword::RLCA
    DFA_Token::KW_RLCA_             , // Keyword::RLCA_
    DFA_Token::KW_RLD               , // Keyword::RLD
    DFA_Token::KW_RLDE              , // Keyword::RLDE
    DFA_Token::KW_RLEU              , // Keyword::RLEU
    DFA_Token::KW_RLO               , // Keyword::RLO
    DFA_Token::KW_RLTU              , // Keyword::RLTU
    DFA_Token::KW_RLZ               , // Keyword::RLZ
    DFA_Token::KW_RM                , // Keyword::RM
    DFA_Token::KW_RNC               , // Keyword::RNC
    DFA_Token::KW_RNE               , // Keyword::RNE
    DFA_Token::KW_RNV               , // Keyword::RNV
    DFA_Token::KW_RNZ               , // Keyword::RNZ
    DFA_Token::KW_RP                , // Keyword::RP
    DFA_Token::KW_RPE               , // Keyword::RPE
    DFA_Token::KW_RPO               , // Keyword::RPO
    DFA_Token::KW_RR                , // Keyword::RR
    DFA_Token::KW_RR1REG            , // Keyword::RR1REG
    DFA_Token::KW_RR2REG            , // Keyword::RR2REG
    DFA_Token::KW_RR3REG            , // Keyword::RR3REG
    DFA_Token::KW_RR4REG            , // Keyword::RR4REG
    DFA_Token::KW_RR5REG            , // Keyword::RR5REG
    DFA_Token::KW_RR6REG            , // Keyword::RR6REG
    DFA_Token::KW_RR7REG            , // Keyword::RR7REG
    DFA_Token::KW_RR8REG            , // Keyword::RR8REG
    DFA_Token::KW_RRA               , // Keyword::RRA
    DFA_Token::KW_RRA_              , // Keyword::RRA_
    DFA_Token::KW_RRB               , // Keyword::RRB
    DFA_Token::KW_RRC               , // Keyword::RRC
    DFA_Token::KW_RRCA              , // Keyword::RRCA
    DFA_Token::KW_RRCA_             , // Keyword::RRCA_
    DFA_Token::KW_RRD               , // Keyword::RRD
    DFA_Token::KW_RRHL              , // Keyword::RRHL
    DFA_Token::KW_RSMIX             , // Keyword::RSMIX
    DFA_Token::KW_RST               , // Keyword::RST
    DFA_Token::KW_RSTV              , // Keyword::RSTV
    DFA_Token::KW_RV                , // Keyword::RV
    DFA_Token::KW_RZ                , // Keyword::RZ
    DFA_Token::KW_S                 , // Keyword::S
    DFA_Token::KW_SBB               , // Keyword::SBB
    DFA_Token::KW_SBC               , // Keyword::SBC
    DFA_Token::KW_SBI               , // Keyword::SBI
    DFA_Token::KW_SBOX              , // Keyword::SBOX
    DFA_Token::KW_SCALL             , // Keyword::SCALL
    DFA_Token::KW_SCF               , // Keyword::SCF
    DFA_Token::KW_SCF_              , // Keyword::SCF_
    DFA_Token::KW_SET               , // Keyword::SET
    DFA_Token::KW_SETAE             , // Keyword::SETAE
    DFA_Token::KW_SETSYSP           , // Keyword::SETSYSP
    DFA_Token::KW_SETUSR            , // Keyword::SETUSR
    DFA_Token::KW_SETUSRP           , // Keyword::SETUSRP
    DFA_Token::KW_SHAF1             , // Keyword::SHAF1
    DFA_Token::KW_SHAF2             , // Keyword::SHAF2
    DFA_Token::KW_SHAF3             , // Keyword::SHAF3
    DFA_Token::KW_SHLD              , // Keyword::SHLD
    DFA_Token::KW_SHLDE             , // Keyword::SHLDE
    DFA_Token::KW_SHLX              , // Keyword::SHLX
    DFA_Token::KW_SIL               , // Keyword::SIL
    DFA_Token::KW_SIM               , // Keyword::SIM
    DFA_Token::KW_SIS               , // Keyword::SIS
    DFA_Token::KW_SL1REG            , // Keyword::SL1REG
    DFA_Token::KW_SL2REG            , // Keyword::SL2REG
    DFA_Token::KW_SL3REG            , // Keyword::SL3REG
    DFA_Token::KW_SL4REG            , // Keyword::SL4REG
    DFA_Token::KW_SL5REG            , // Keyword::SL5REG
    DFA_Token::KW_SL6REG            , // Keyword::SL6REG
    DFA_Token::KW_SL7REG            , // Keyword::SL7REG
    DFA_Token::KW_SL8REG            , // Keyword::SL8REG
    DFA_Token::KW_SLA               , // Keyword::SLA
    DFA_Token::KW_SLI               , // Keyword::SLI
    DFA_Token::KW_SLL               , // Keyword::SLL
    DFA_Token::KW_SLP               , // Keyword::SLP
    DFA_Token::KW_SLS               , // Keyword::SLS
    DFA_Token::KW_SP                , // Keyword::SP
    DFA_Token::KW_SPHL              , // Keyword::SPHL
    DFA_Token::KW_SR1REG            , // Keyword::SR1REG
    DFA_Token::KW_SR2REG            , // Keyword::SR2REG
    DFA_Token::KW_SR3REG            , // Keyword::SR3REG
    DFA_Token::KW_SR4REG            , // Keyword::SR4REG
    DFA_Token::KW_SR5REG            , // Keyword::SR5REG
    DFA_Token::KW_SR6REG            , // Keyword::SR6REG
    DFA_Token::KW_SR7REG            , // Keyword::SR7REG
    DFA_Token::KW_SR8REG            , // Keyword::SR8REG
    DFA_Token::KW_SRA               , // Keyword::SRA
    DFA_Token::KW_SRET              , // Keyword::SRET
    DFA_Token::KW_SRL               , // Keyword::SRL
    DFA_Token::KW_STA               , // Keyword::STA
    DFA_Token::KW_STAE              , // Keyword::STAE
    DFA_Token::KW_STAX              , // Keyword::STAX
    DFA_Token::KW_STC               , // Keyword::STC
    DFA_Token::KW_STMIX             , // Keyword::STMIX
    DFA_Token::KW_STOP              , // Keyword::STOP
    DFA_Token::KW_SU                , // Keyword::SU
    DFA_Token::KW_SUB               , // Keyword::SUB
    DFA_Token::KW_SUI               , // Keyword::SUI
    DFA_Token::KW_SURES             , // Keyword::SURES
    DFA_Token::KW_SWAP              , // Keyword::SWAP
    DFA_Token::KW_SWAPNIB           , // Keyword::SWAPNIB
    DFA_Token::KW_SYSCALL           , // Keyword::SYSCALL
    DFA_Token::KW_SYSRET            , // Keyword::SYSRET
    DFA_Token::KW_TEST              , // Keyword::TEST
    DFA_Token::KW_TRA               , // Keyword::TRA
    DFA_Token::KW_TST               , // Keyword::TST
    DFA_Token::KW_TSTIO             , // Keyword::TSTIO
    DFA_Token::KW_TSTNULL           , // Keyword::TSTNULL
    DFA_Token::KW_UMA               , // Keyword::UMA
    DFA_Token::KW_UMS               , // Keyword::UMS
    DFA_Token::None                 , // Keyword::UNDEF
    DFA_Token::None                 , // Keyword::UNDEFINE
    DFA_Token::None                 , // Keyword::UNTIL
    DFA_Token::None                 , // Keyword::UNTILB
    DFA_Token::None                 , // Keyword::UNTILBC
    DFA_Token::KW_V                 , // Keyword::V
    DFA_Token::None                 , // Keyword::WEND
    DFA_Token::None                 , // Keyword::WHILE
    DFA_Token::KW_X                 , // Keyword::X
    DFA_Token::KW_X5                , // Keyword::X5
    DFA_Token::KW_XBC               , // Keyword::XBC
    DFA_Token::KW_XCHG              , // Keyword::XCHG
    DFA_Token::KW_XDE               , // Keyword::XDE
    DFA_Token::KW_XHL               , // Keyword::XHL
    DFA_Token::KW_XIX               , // Keyword::XIX
    DFA_Token::KW_XIY               , // Keyword::XIY
    DFA_Token::KW_XOR               , // Keyword::XOR
    DFA_Token::KW_XP                , // Keyword::XP
    DFA_Token::KW_XPC               , // Keyword::XPC
    DFA_Token::KW_XRA               , // Keyword::XRA
    DFA_Token::KW_XRI               , // Keyword::XRI
    DFA_Token::KW_XSP               , // Keyword::XSP
    DFA_Token::KW_XTHL              , // Keyword::XTHL
    DFA_Token::KW_XY                , // Keyword::XY
    DFA_Token::KW_YBC               , // Keyword::YBC
    DFA_Token::KW_YDE               , // Keyword::YDE
    DFA_Token::KW_YHL               , // Keyword::YHL
    DFA_Token::KW_YIX               , // Keyword::YIX
    DFA_Token::KW_YIY               , // Keyword::YIY
    DFA_Token::KW_YP                , // Keyword::YP
    DFA_Token::KW_YSP               , // Keyword::YSP
    DFA_Token::KW_Z                 , // Keyword::Z
    DFA_Token::KW_ZBC               , // Keyword::ZBC
    DFA_Token::KW_ZDE               , // Keyword::ZDE
    DFA_Token::KW_ZHL               , // Keyword::ZHL
    DFA_Token::KW_ZIX               , // Keyword::ZIX
    DFA_Token::KW_ZIY               , // Keyword::ZIY
    DFA_Token::KW_ZP                , // Keyword::ZP
    DFA_Token::KW_ZSP               , // Keyword::ZSP
};

// map TokenType to DFA_Token
const DFA_Token OpcodesParser::map_token_type_to_dfa_tokens[49] = {
    DFA_Token::TK_EndOfLine , // TokenType::EndOfLine
    DFA_Token::None         , // TokenType::Identifier
    DFA_Token::None         , // TokenType::Integer
    DFA_Token::None         , // TokenType::Float
    DFA_Token::None         , // TokenType::String
    DFA_Token::TK_Plus      , // TokenType::Plus
    DFA_Token::TK_Minus     , // TokenType::Minus
    DFA_Token::None         , // TokenType::Multiply
    DFA_Token::None         , // TokenType::Divide
    DFA_Token::None         , // TokenType::Modulo
    DFA_Token::None         , // TokenType::Power
    DFA_Token::None         , // TokenType::BitwiseAnd
    DFA_Token::None         , // TokenType::BitwiseOr
    DFA_Token::None         , // TokenType::BitwiseXor
    DFA_Token::None         , // TokenType::BitwiseNot
    DFA_Token::None         , // TokenType::LeftShift
    DFA_Token::None         , // TokenType::RightShift
    DFA_Token::None         , // TokenType::LogicalAnd
    DFA_Token::None         , // TokenType::LogicalOr
    DFA_Token::None         , // TokenType::LogicalXor
    DFA_Token::None         , // TokenType::LogicalNot
    DFA_Token::None         , // TokenType::EQ
    DFA_Token::None         , // TokenType::NE
    DFA_Token::None         , // TokenType::LT
    DFA_Token::None         , // TokenType::LE
    DFA_Token::None         , // TokenType::GT
    DFA_Token::None         , // TokenType::GE
    DFA_Token::TK_LeftParen , // TokenType::LeftParen
    DFA_Token::TK_RightParen, // TokenType::RightParen
    DFA_Token::None         , // TokenType::LeftBracket
    DFA_Token::None         , // TokenType::RightBracket
    DFA_Token::None         , // TokenType::LeftBrace
    DFA_Token::None         , // TokenType::RightBrace
    DFA_Token::TK_Comma     , // TokenType::Comma
    DFA_Token::TK_Colon     , // TokenType::Colon
    DFA_Token::TK_Dot       , // TokenType::Dot
    DFA_Token::None         , // TokenType::Question
    DFA_Token::None         , // TokenType::Hash
    DFA_Token::None         , // TokenType::DoubleHash
    DFA_Token::None         , // TokenType::At
    DFA_Token::None         , // TokenType::Dollar
    DFA_Token::None         , // TokenType::Backslash
    DFA_Token::None         , // TokenType::ASMPC
    DFA_Token::TK_PlusA     , // TokenType::PlusA
    DFA_Token::TK_PlusBC    , // TokenType::PlusBC
    DFA_Token::TK_PlusDE    , // TokenType::PlusDE
    DFA_Token::TK_PlusHL    , // TokenType::PlusHL
    DFA_Token::TK_PlusIX    , // TokenType::PlusIX
    DFA_Token::TK_PlusIY    , // TokenType::PlusIY
};

