//-----------------------------------------------------------------------------
// Z80 assembler
// Copyright (C) Paulo Custodio, 2011-2026
// License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
//-----------------------------------------------------------------------------

#pragma once

#include "const_symbols.h"
#include "file_mgr.h"
#include "lexer_tokens.h"
#include "source_loc.h"
#include "string_interner.h"
#include <deque>
#include <string_view>
#include <vector>

static const int MAX_EXPANSION_DEPTH = 1000;

struct Macro {
    StringInterner::Id name_id;                 // interned identifier
    SourceLoc loc;                              // where it was defined
    std::vector<Token> tokens;                  // object/function-like
    std::vector<LogicalLine> lines;             // classical multi-line
    std::vector<StringInterner::Id> params;     // interned identifiers
    std::vector<StringInterner::Id> locals;     // LOCAL label names
    bool is_function_like = false;
    bool is_multiline = false;
    bool has_parenthesized_params = false;      // defined with (p1,p2) vs p1,p2
};

class Preproc {
public:
    Preproc() = default;

    // copy defines from options, command line, or global scope
    void set_const_symbols(const ConstSymbols& defs);

    // main entry point: preprocess file and return vector of tokens
    // for assembler
    std::vector<LogicalLine> preprocess(std::string_view filename);

private:

    // ---------------------------------------------------------------------
    // Include stack: tracks nested file inclusion
    // ---------------------------------------------------------------------
    struct IncludeFrame {
        const SourceFile* file = nullptr;
        StringInterner::Id logical_file_id = 0;
        size_t current_line = 0;
        bool logical_line_fixed = false;        // for C_LINE
        ptrdiff_t logical_line_offset = 0;      // for LINE, C_LINE

        size_t logical_line() const {
            if (logical_line_fixed) {
                return logical_line_offset;
            }
            else if (file != nullptr) {
                return current_line + logical_line_offset + 1;
            }
            else {
                return 0;
            }
        }
    };

    std::vector<IncludeFrame> include_stack;

    // ---------------------------------------------------------------------
    // Macro table: object-like, function-like, classical multi-line
    // ---------------------------------------------------------------------
    std::unordered_map<StringInterner::Id, Macro> macros;

    // ---------------------------------------------------------------------
    // Preprocessor symbols: -DNAME=expr, EQU, IF expressions
    // ---------------------------------------------------------------------
    ConstSymbols const_symbols;

    // ---------------------------------------------------------------------
    // Conditional stack: IF / ELSEIF / ELSE / ENDIF
    // ---------------------------------------------------------------------
    struct ConditionalFrame {
        SourceLoc if_loc;           // location of the IF/ELIF/ELSE
        bool branch_active = false; // whether this level currently includes text
        bool any_taken = false;     // whether any previous branch in this chain matched
        bool seen_else = false;     // whether ELSE already occurred
    };

    std::vector<ConditionalFrame> cond_stack;

    bool is_cond_active() const;

    // ---------------------------------------------------------------------
    // Macro expansion stack:
    //
    // Each frame represents a block of lines produced by a macro
    // invocation (name_id != 0) or a directive like REPT/REPTI/REPTC/
    // BINARY (name_id == 0). Lines are consumed front-to-back.
    //
    // EXITM searches the stack top-down for the first frame with
    // name_id != 0 and sets its exited flag, which suppresses
    // non-conditional lines without aborting directive processing.
    // ---------------------------------------------------------------------
    struct MacroExpansionFrame {
        StringInterner::Id name_id = 0; // 0 = directive, != 0 = macro
        bool exited = false;            // set by EXITM
        std::deque<LogicalLine> lines;
    };

    std::vector<MacroExpansionFrame> macro_expansion_stack;

    // Helper: push lines into a new frame on the expansion stack
    void push_macro_expansion(StringInterner::Id name_id,
                              std::deque<LogicalLine> lines);

    // ---------------------------------------------------------------------
    // We also need a queue for lines generated by directives (e.g. DEFINE)
    // that must be passed to the output without macro expansion. This is
    // needed to support DEFINE X=1 creating DEFC X=1, where X cannot
    // be replaced by 1
    // ---------------------------------------------------------------------
    std::deque<LogicalLine> assembler_output_queue;

    // ---------------------------------------------------------------------
    // Dependency genration: set of logical file IDs encountered
    // during preprocessing
    // ---------------------------------------------------------------------
    std::vector<StringInterner::Id> dependency_files;

    // ---------------------------------------------------------------------
    // Methods
    // ---------------------------------------------------------------------

    // ---------------------------------------------------------------------
    // Logical line source interface: driver loop calls next_logical_line()
    // to get the next line from one of the sources (file stack,
    // macro feedback queue, assembler output queue)
    // ---------------------------------------------------------------------
    bool next_logical_line(LogicalLine& out);

    // Check if the current top of the macro expansion stack has been
    // exited (EXITM). Used by process_directive_line to suppress output.
    bool is_macro_exited() const;

    // ---------------------------------------------------------------------
    // Directive processing: classification and dispatch
    // ---------------------------------------------------------------------

    // dispatch tables for directive handlers
    using DirectiveHandler =
        void (Preproc::*)(const std::vector<Token>&, size_t&);
    static std::unordered_map<Keyword, DirectiveHandler> directive_handlers_;

    using NameDirectiveHandler =
        void (Preproc::*)(std::string_view, const SourceLoc&,
                          const std::vector<Token>&, size_t&);
    static std::unordered_map<Keyword, NameDirectiveHandler> name_directive_handlers_;

    // main driver for directive processing: classifies line and
    // dispatches to handlers
    enum class LineType {
        Normal,
        Skip,
        ControlOnly
    };
    LineType process_directive_line(const std::vector<Token>& input_line,
                                    LogicalLine& out_line
                                   );

    bool is_directive(const std::vector<Token>& input_line,
                      size_t& pos,
                      Keyword& out_kw,
                      std::string& out_name,
                      SourceLoc& out_name_loc);
    bool check_end_of_line(const std::vector<Token>& input_line,
                           size_t& pos,
                           std::string_view directive_name);
    bool parse_filename(const std::vector<Token>& input_line,
                        size_t& pos,
                        std::string_view directive_name,
                        std::string& out_filename,
                        bool& out_is_angle_bracket,
                        SourceLoc& out_filename_loc);
    bool parse_and_resolve_file(const std::vector<Token>& input_line,
                                size_t& pos,
                                std::string_view directive_name,
                                std::string& out_resolved,
                                SourceLoc& out_filename_loc);
    bool parse_LINE_args(const std::vector<Token>& input_line, size_t& pos,
                         std::string_view directive_name,
                         size_t& out_linenum, std::string& out_filename);
    bool parse_params(const std::vector<Token>& input_line,
                      size_t& pos,
                      std::vector<StringInterner::Id>& out_params,
                      bool& out_has_parens);
    bool read_macro_body(Keyword start_kw,
                         const SourceLoc& macro_loc,
                         std::vector<LogicalLine>& out_lines,
                         std::vector<StringInterner::Id>& out_locals);
    bool eval_if_expr(const std::vector<Token>& input_line, size_t& pos,
                      Keyword kw);

    void parse_asm_definitions(const std::vector<Token>& tokens);
    void rewrite_logical_line(LogicalLine& line);

    void process_INCLUDE(const std::vector<Token>& input_line, size_t& pos);
    void process_BINARY(const std::vector<Token>& input_line, size_t& pos);
    void process_LINE(const std::vector<Token>& input_line, size_t& pos);
    void process_C_LINE(const std::vector<Token>& input_line, size_t& pos);
    void process_DEFINE(const std::vector<Token>& input_line, size_t& pos);
    void process_name_DEFINE(std::string_view name, const SourceLoc& name_loc,
                             const std::vector<Token>& input_line, size_t& pos);
    void do_DEFINE(const Macro& macro,
                   const std::vector<Token>& input_line, size_t& pos);
    void process_UNDEF(const std::vector<Token>& input_line, size_t& pos);
    void process_name_UNDEF(std::string_view name, const SourceLoc& name_loc,
                            const std::vector<Token>& input_line, size_t& pos);
    void do_UNDEF(StringInterner::Id name_id);
    void process_DEFL(const std::vector<Token>& input_line, size_t& pos);
    void process_name_DEFL(std::string_view name, const SourceLoc& name_loc,
                           const std::vector<Token>& input_line, size_t& pos);
    void do_DEFL(const Macro& macro,
                 const std::vector<Token>& input_line, size_t& pos);
    void process_MACRO(const std::vector<Token>& input_line, size_t& pos);
    void process_name_MACRO(std::string_view name, const SourceLoc& name_loc,
                            const std::vector<Token>& input_line, size_t& pos);
    void do_MACRO(const Macro& macro, SourceLoc& kw_macro_loc);
    void process_ENDM(const std::vector<Token>& input_line, size_t& pos);
    void process_REPT(const std::vector<Token>& input_line, size_t& pos);
    void process_ENDR(const std::vector<Token>& input_line, size_t& pos);
    void process_REPTI(const std::vector<Token>& input_line, size_t& pos);
    void process_name_REPTI(std::string_view iter_name,
                            const SourceLoc& kw_loc,
                            const std::vector<Token>& input_line, size_t& pos);
    void do_REPTI(std::string_view iter_name, const SourceLoc& kw_loc,
                  const std::vector<Token>& input_line, size_t& pos);
    void process_REPTC(const std::vector<Token>& input_line, size_t& pos);
    void process_name_REPTC(std::string_view iter_name,
                            const SourceLoc& kw_loc,
                            const std::vector<Token>& input_line, size_t& pos);
    void do_REPTC(std::string_view iter_name, const SourceLoc& kw_loc,
                  const std::vector<Token>& input_line, size_t& pos);
    void process_LOCAL(const std::vector<Token>& input_line, size_t& pos);
    void process_name_LOCAL(std::string_view iter_name,
                            const SourceLoc& kw_loc,
                            const std::vector<Token>& input_line, size_t& pos);
    void process_EXITM(const std::vector<Token>& input_line, size_t& pos);
    void process_IF(const std::vector<Token>& input_line, size_t& pos);
    void process_ELSEIF(const std::vector<Token>& input_line, size_t& pos);
    void process_ELSE(const std::vector<Token>& input_line, size_t& pos);
    void process_ENDIF(const std::vector<Token>& input_line, size_t& pos);

    // ---------------------------------------------------------------------
    // Macro expansion: classification and dispatch
    // ---------------------------------------------------------------------

    bool collect_args_impl(const std::vector<Token>& tokens, size_t& pos,
                           std::vector<std::vector<Token>>& args,
                           bool parenthesized);
    bool collect_parens_args(const std::vector<Token>& tokens, size_t& pos,
                             std::vector<std::vector<Token>>& args);
    bool collect_bare_args(const std::vector<Token>& tokens, size_t& pos,
                           std::vector<std::vector<Token>>& args);
    std::vector<Token> substitute_params(const std::vector<Token>& body,
                                         const std::vector<StringInterner::Id>&
                                         params,
                                         const std::vector<std::vector<Token>>&
                                         args,
                                         const SourceLoc& call_loc,
                                         const std::vector<StringInterner::Id>&
                                         locals);

    // macro expansion: takes a logical line with macro invocation tokens and
    // expands it, pushing resulting lines to macro_work_queue
    void expand_line(const LogicalLine& in, std::vector<Token>& out_tokens);

    // ---------------------------------------------------------------------
    // helpers for dumping state
    // ---------------------------------------------------------------------

    void dump_logical_line(const LogicalLine& line,
                           StringInterner::Id& cur_file_id);
    void dump_macro(const Macro& macro,
                    StringInterner::Id& cur_file_id);
    void dump_macros();
    void dump_symbols();
};
