//-----------------------------------------------------------------------------
// Z80 assembler
// Copyright (C) Paulo Custodio, 2011-2026
// License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
//-----------------------------------------------------------------------------

#pragma once

#include "const_symbols.h"
#include "file_mgr.h"
#include "lexer_tokens.h"
#include "preproc.h"
#include "source_loc.h"
#include "string_interner.h"
#include <deque>
#include <string_view>
#include <vector>

static const int MAX_EXPANSION_DEPTH = 1000;

struct Macro {
    StringInterner::Id name_id;                 // interned identifier
    SourceLoc loc;                              // where it was defined
    std::vector<Token> tokens;                  // object/function-like
    std::vector<LogicalLine> lines;      		// classical multi-line
    std::vector<StringInterner::Id> params;     // interned identifiers
    bool is_function_like = false;
    bool is_multiline = false;
};

class Preproc {
public:
    Preproc() = default;

    // copy defines from options, command line, or global scope
    void set_const_symbols(const ConstSymbols& defs);

    // main entry point: preprocess file and return vector of tokens
    // for assembler
    std::vector<LogicalLine> preprocess(std::string_view filename);

private:

    // ---------------------------------------------------------------------
    // Include stack: tracks nested file inclusion
    // ---------------------------------------------------------------------
    struct IncludeFrame {
        const SourceFile* file = nullptr;
        StringInterner::Id logical_file_id = 0;
        size_t current_line = 0;
        bool logical_line_fixed = false;        // for C_LINE
        ptrdiff_t logical_line_offset = 0;      // for LINE, C_LINE

        size_t logical_line() const {
            if (logical_line_fixed) {
                return logical_line_offset;
            }
            else if (file != nullptr) {
                return current_line + logical_line_offset + 1;
            }
            else {
                return 0;
            }
        }
    };

    std::vector<IncludeFrame> include_stack;

    // ---------------------------------------------------------------------
    // Macro table: object-like, function-like, classical multi-line
    // ---------------------------------------------------------------------
    std::unordered_map<StringInterner::Id, Macro> macros;

    // ---------------------------------------------------------------------
    // Preprocessor symbols: -DNAME=expr, EQU, IF expressions
    // ---------------------------------------------------------------------
    ConstSymbols const_symbols;

    // ---------------------------------------------------------------------
    // Conditional stack: IF / ELSEIF / ELSE / ENDIF
    // ---------------------------------------------------------------------
    struct ConditionalFrame {
        bool parent_active = true;
        bool this_branch_taken = false;
        bool currently_active = true;
        SourceLoc if_loc;   // for error reporting
    };

    std::vector<ConditionalFrame> cond_stack;

    // ---------------------------------------------------------------------
    // Feedback loop queue:
    //
    // Classical macro expansion may emit directive lines (e.g. nested
    // MACRO/ENDM). These must be processed by the directive engine before
    // normal macro expansion continues. The driver pulls from this queue
    // before reading from include_stack.
    // ---------------------------------------------------------------------
    std::deque<LogicalLine> macro_work_queue;

    // ---------------------------------------------------------------------
    // We also need a queue for lines generated by directives (e.g. DEFINE)
    // that must be passed to the output without macro expansion. This is
    // needed to support DEFINE X=1 creating DEFC X=1, where X cannot
    // be replaced by 1
    // ---------------------------------------------------------------------
    std::deque<LogicalLine> assembler_output_queue;

    // ---------------------------------------------------------------------
    // Dependency genration: set of logical file IDs encountered
    // during preprocessing
    // ---------------------------------------------------------------------
    std::vector<StringInterner::Id> dependency_files;

    // ---------------------------------------------------------------------
    // Methods
    // ---------------------------------------------------------------------

    // ---------------------------------------------------------------------
    // Logical line source interface: driver loop calls next_logical_line()
    // to get the next line from one of the sources (file stack,
    // macro feedback queue, assembler output queue)
    // ---------------------------------------------------------------------
    bool next_logical_line(LogicalLine& out);

    // ---------------------------------------------------------------------
    // Directive processing: classification and dispatch
    // ---------------------------------------------------------------------

    // dispatch tables for directive handlers
    using DirectiveHandler =
        void (Preproc::*)(const std::vector<Token>&, size_t&);
    static std::unordered_map<Keyword, DirectiveHandler> directive_handlers_;

    using NameDirectiveHandler =
        void (Preproc::*)(std::string_view, const SourceLoc&,
                          const std::vector<Token>&, size_t&);
    static std::unordered_map<Keyword, NameDirectiveHandler> name_directive_handlers_;

    // main driver for directive processing: classifies line and
    // dispatches to handlers
    enum class LineType {
        Normal,
        Skip,
        ControlOnly
    };
    LineType process_directive_line(const std::vector<Token>& input_line,
                                    LogicalLine& out_line
                                   );

    void check_end_of_line(const std::vector<Token>& input_line,
                           size_t& pos,
                           std::string_view directive_name);
    bool parse_filename(const std::vector<Token>& input_line,
                        size_t& pos,
                        std::string_view directive_name,
                        std::string& out_filename,
                        bool& out_is_angle_bracket,
                        SourceLoc& out_filename_loc);
    bool parse_and_resolve_file(const std::vector<Token>& input_line,
                                size_t& pos,
                                std::string_view directive_name,
                                std::string& out_resolved,
                                SourceLoc& out_filename_loc);
    bool parse_LINE_args(const std::vector<Token>& input_line, size_t& pos,
                         std::string_view directive_name,
                         size_t& out_linenum, std::string& out_filename);
    bool parse_parameters(const std::vector<Token>& input_line, size_t& pos,
                          std::vector<StringInterner::Id>& out_params);
    bool collect_args(const std::vector<Token>& tokens, size_t& pos,
                      std::vector<std::vector<Token>>& args);
    std::vector<Token> substitute_params(
        const std::vector<Token>& body,
        const std::vector<StringInterner::Id>& params,
        const std::vector<std::vector<Token>>& args,
        const SourceLoc& call_loc);
    void parse_asm_definitions(const std::vector<Token>& tokens);
    void rewrite_logical_line(LogicalLine& line);

    void process_INCLUDE(const std::vector<Token>& input_line, size_t& pos);
    void process_BINARY(const std::vector<Token>& input_line, size_t& pos);
    void process_LINE(const std::vector<Token>& input_line, size_t& pos);
    void process_C_LINE(const std::vector<Token>& input_line, size_t& pos);
    void process_DEFINE(const std::vector<Token>& input_line, size_t& pos);
    void process_name_DEFINE(std::string_view name, const SourceLoc& name_loc,
                             const std::vector<Token>& input_line, size_t& pos);
    void do_DEFINE(const Macro& macro,
                   const std::vector<Token>& input_line, size_t& pos);
    void process_UNDEF(const std::vector<Token>& input_line, size_t& pos);
    void process_name_UNDEF(std::string_view name, const SourceLoc& name_loc,
                            const std::vector<Token>& input_line, size_t& pos);
    void do_UNDEF(StringInterner::Id name_id);
    void process_DEFL(const std::vector<Token>& input_line, size_t& pos);
    void process_name_DEFL(std::string_view name, const SourceLoc& name_loc,
                           const std::vector<Token>& input_line, size_t& pos);
    void do_DEFL(const Macro& macro,
                 const std::vector<Token>& input_line, size_t& pos);

    // ---------------------------------------------------------------------
    // Macro expansion: classification and dispatch
    // ---------------------------------------------------------------------

    // macro expansion: takes a logical line with macro invocation tokens and
    // expands it, pushing resulting lines to macro_work_queue
    void expand_line(const LogicalLine& in, std::vector<Token>& out_tokens);

    // ---------------------------------------------------------------------
    // helpers for dumping state
    // ---------------------------------------------------------------------

    void dump_logical_line(const LogicalLine& line,
                           StringInterner::Id& cur_file_id);
    void dump_macro(const Macro& macro,
                    StringInterner::Id& cur_file_id);
    void dump_macros();
    void dump_symbols();
};
