;
;	TI 82 Key Table
;

.TiKeyTab1

defb	$04	;Down
defb	10
defb	$02	;Left
defb	8
defb	$01	;Right
defb	9
defb	$03	;Up
defb	11
defb	$05	;ENTER
defb	13

defb	$7	;DEL
defb	12


defb	129; K_PLUS
defb	'+'
defb	130; K_MINUS
defb	'-'
defb	131
defb	'*'
defb	132
defb	'/'
defb	133
defb	'^'
defb	134
defb	'('
defb	135
defb	')'
defb	140
defb	','
defb	142
defb	'.'

defb	237
defb	'('
defb	238
defb	')'

defb	0



.TiKeyTab2

defb	$04	;Down
defb	10
defb	$02	;Left
defb	8
defb	$01	;Right
defb	9
defb	$03	;Up
defb	11
defb	$05	;ENTER
defb	13

defb	$7	;DEL
defb	12

defb	0
