#ifndef RSTHELPER_H
#define RSTHELPER_H

#include <inttypes.h>

#define F_SEQUENCE 1
#define F_END      2
#define F_LEN67    4
// One byte following (relative jumps + sam constants)
#define F_BYTE      8
#define F_WORD     16
#define F_5BYTES   32
#define F_nBYTES   64

typedef struct {
    uint8_t     rst;
    uint8_t     flags;
    int         length;
    uint8_t     bytes[10];
    char        *opcode;        // If null, then bytes printed as defb
    char        *api;
} rsthelper;


static rsthelper z88_helpers[] = {
    { .rst = 0xdf, .length = 0x01, .bytes = {0x21}, .opcode = "fpp", .api = "FP_AND" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x24}, .opcode = "fpp", .api = "FP_IDV" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x27}, .opcode = "fpp", .api = "FP_EOR" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x2A}, .opcode = "fpp", .api = "FP_MOD" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x2D}, .opcode = "fpp", .api = "FP_OR" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x30}, .opcode = "fpp", .api = "FP_ELQ" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x33}, .opcode = "fpp", .api = "FP_NEQ" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x36}, .opcode = "fpp", .api = "FP_GEQ" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x39}, .opcode = "fpp", .api = "FP_LT" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x3C}, .opcode = "fpp", .api = "FP_EQ" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x3F}, .opcode = "fpp", .api = "FP_MUL" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x42}, .opcode = "fpp", .api = "FP_ADD" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x45}, .opcode = "fpp", .api = "FP_GT" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x48}, .opcode = "fpp", .api = "FP_SUB" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x4B}, .opcode = "fpp", .api = "FP_PWR" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x4E}, .opcode = "fpp", .api = "FP_DIV" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x51}, .opcode = "fpp", .api = "FP_ABS" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x54}, .opcode = "fpp", .api = "FP_ACS" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x57}, .opcode = "fpp", .api = "FP_ASN" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x5A}, .opcode = "fpp", .api = "FP_ATN" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x5D}, .opcode = "fpp", .api = "FP_COS" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x60}, .opcode = "fpp", .api = "FP_DEG" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x63}, .opcode = "fpp", .api = "FP_EXP" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x66}, .opcode = "fpp", .api = "FP_INT" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x6C}, .opcode = "fpp", .api = "FP_LOG" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x6F}, .opcode = "fpp", .api = "FP_NOT" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x72}, .opcode = "fpp", .api = "FP_RAD" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x75}, .opcode = "fpp", .api = "FP_SGN" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x78}, .opcode = "fpp", .api = "FP_SIN" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x7B}, .opcode = "fpp", .api = "FP_SQR" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x7E}, .opcode = "fpp", .api = "FP_TAN" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x81}, .opcode = "fpp", .api = "FP_ZER" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x84}, .opcode = "fpp", .api = "FP_ONE" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x87}, .opcode = "fpp", .api = "FP_TRU" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x8A}, .opcode = "fpp", .api = "FP_PI" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x8D}, .opcode = "fpp", .api = "FP_VAL" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x90}, .opcode = "fpp", .api = "FP_STR" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x93}, .opcode = "fpp", .api = "FP_FIX" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x96}, .opcode = "fpp", .api = "FP_FLT" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x9C}, .opcode = "fpp", .api = "FP_CMP" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0x9F}, .opcode = "fpp", .api = "FP_NEG" },
    { .rst = 0xdf, .length = 0x01, .bytes = {0xA2}, .opcode = "fpp", .api = "FP_BAS" },

    { .rst = 0xe7, .length = 0x01, .bytes = {0x21}, .opcode = "call_oz",  .api = "OS_BYE" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x24}, .opcode = "call_oz",  .api = "OS_PRT" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x27}, .opcode = "call_oz",  .api = "OS_OUT" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x2A}, .opcode = "call_oz",  .api = "OS_IN" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x2D}, .opcode = "call_oz",  .api = "OS_TIN" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x30}, .opcode = "call_oz",  .api = "OS_XIN" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x33}, .opcode = "call_oz",  .api = "OS_PUR" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x36}, .opcode = "call_oz",  .api = "OS_UGB" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x39}, .opcode = "call_oz",  .api = "OS_GB" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x3C}, .opcode = "call_oz",  .api = "OS_PB" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x3F}, .opcode = "call_oz",  .api = "OS_GBT" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x42}, .opcode = "call_oz",  .api = "OS_PBT" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x45}, .opcode = "call_oz",  .api = "OS_MV" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x48}, .opcode = "call_oz",  .api = "OS_FRM" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x4B}, .opcode = "call_oz",  .api = "OS_FWM" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x4E}, .opcode = "call_oz",  .api = "OS_MOP" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x51}, .opcode = "call_oz",  .api = "OS_MCL" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x54}, .opcode = "call_oz",  .api = "OS_MAL" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x57}, .opcode = "call_oz",  .api = "OS_MFR" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x5A}, .opcode = "call_oz",  .api = "OS_MGB" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x5D}, .opcode = "call_oz",  .api = "OS_MPB" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x60}, .opcode = "call_oz",  .api = "OS_BIX" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x63}, .opcode = "call_oz",  .api = "OS_BOX" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x66}, .opcode = "call_oz",  .api = "OS_NQ" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x69}, .opcode = "call_oz",  .api = "OS_SP" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x6C}, .opcode = "call_oz",  .api = "OS_SR" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x6F}, .opcode = "call_oz",  .api = "OS_ESC" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x72}, .opcode = "call_oz",  .api = "OS_ERC" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x75}, .opcode = "call_oz",  .api = "OS_ERH" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x78}, .opcode = "call_oz",  .api = "OS_UST" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x7B}, .opcode = "call_oz",  .api = "OS_FN" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x7E}, .opcode = "call_oz",  .api = "OS_WAIT" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x81}, .opcode = "call_oz",  .api = "OS_ALM" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x84}, .opcode = "call_oz",  .api = "OS_CLI" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x87}, .opcode = "call_oz",  .api = "OS_DOR" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x8A}, .opcode = "call_oz",  .api = "OS_FC" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x8D}, .opcode = "call_oz",  .api = "OS_SI" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x90}, .opcode = "call_oz",  .api = "OS_BOUT" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x93}, .opcode = "call_oz",  .api = "OS_POUT" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x96}, .opcode = "call_oz",  .api = "OS_HOUT" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x99}, .opcode = "call_oz",  .api = "OS_SOUT" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x9C}, .opcode = "call_oz",  .api = "OS_KIN" },
    { .rst = 0xe7, .length = 0x01, .bytes = {0x9F}, .opcode = "call_oz",  .api = "OS_NLN" },

    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xBA}, .opcode = "call_oz",  .api = "OS_FDP" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xBC}, .opcode = "call_oz",  .api = "OS_WTS" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xC0}, .opcode = "call_oz",  .api = "OS_FXM" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xC2}, .opcode = "call_oz",  .api = "OS_AXM" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xC4}, .opcode = "call_oz",  .api = "OS_FMA" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xC6}, .opcode = "call_oz",  .api = "OS_PLOZ" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xC8}, .opcode = "call_oz",  .api = "OS_FEP" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xCA}, .opcode = "call_oz",  .api = "OS_WTB" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xCC}, .opcode = "call_oz",  .api = "OS_WRT" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xCE}, .opcode = "call_oz",  .api = "OS_WWQ" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xD0}, .opcode = "call_oz",  .api = "OS_ISQ" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xD2}, .opcode = "call_oz",  .api = "OS_AXP" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xD4}, .opcode = "call_oz",  .api = "OS_SCI" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xD6}, .opcode = "call_oz",  .api = "OS_DLY" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xD8}, .opcode = "call_oz",  .api = "OS_BLP" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xDA}, .opcode = "call_oz",  .api = "OS_BDE" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xDC}, .opcode = "call_oz",  .api = "OS_BHL" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xDE}, .opcode = "call_oz",  .api = "OS_FTH" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xE0}, .opcode = "call_oz",  .api = "OS_VTH" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xE2}, .opcode = "call_oz",  .api = "OS_GTH" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xE4}, .opcode = "call_oz",  .api = "OS_REN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xE6}, .opcode = "call_oz",  .api = "OS_DEL" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xE8}, .opcode = "call_oz",  .api = "OS_CL" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xEA}, .opcode = "call_oz",  .api = "OS_OP" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xEC}, .opcode = "call_oz",  .api = "OS_OFF" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xEE}, .opcode = "call_oz",  .api = "OS_USE" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xF0}, .opcode = "call_oz",  .api = "OS_EPR" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xF2}, .opcode = "call_oz",  .api = "OS_TH" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xF4}, .opcode = "call_oz",  .api = "OS_MAP" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xF6}, .opcode = "call_oz",  .api = "OS_EXIT" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xF8}, .opcode = "call_oz",  .api = "OS_STK" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xFC}, .opcode = "call_oz",  .api = "OS_POLL" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x06, 0xFE}, .opcode = "call_oz",  .api = "OS_DOM" },

    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x06}, .opcode = "call_oz",  .api = "GN_GDT" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x08}, .opcode = "call_oz",  .api = "GN_PDT" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x0A}, .opcode = "call_oz",  .api = "GN_GTM" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x0C}, .opcode = "call_oz",  .api = "GN_PTM" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x0E}, .opcode = "call_oz",  .api = "GN_SDO" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x10}, .opcode = "call_oz",  .api = "GN_GDN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x12}, .opcode = "call_oz",  .api = "GN_PDN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x14}, .opcode = "call_oz",  .api = "GN_DIE" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x16}, .opcode = "call_oz",  .api = "GN_DEI" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x18}, .opcode = "call_oz",  .api = "GN_GMD" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x1A}, .opcode = "call_oz",  .api = "GN_GMT" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x1C}, .opcode = "call_oz",  .api = "GN_PMD" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x1E}, .opcode = "call_oz",  .api = "GN_PMT" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x20}, .opcode = "call_oz",  .api = "GN_MSC" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x22}, .opcode = "call_oz",  .api = "GN_FLO" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x24}, .opcode = "call_oz",  .api = "GN_FLC" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x26}, .opcode = "call_oz",  .api = "GN_FLW" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x28}, .opcode = "call_oz",  .api = "GN_FLR" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x2A}, .opcode = "call_oz",  .api = "GN_FLF" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x2C}, .opcode = "call_oz",  .api = "GN_FPB" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x2E}, .opcode = "call_oz",  .api = "GN_NLN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x30}, .opcode = "call_oz",  .api = "GN_CLS" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x32}, .opcode = "call_oz",  .api = "GN_SKC" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x34}, .opcode = "call_oz",  .api = "GN_SKD" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x36}, .opcode = "call_oz",  .api = "GN_SKT" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x38}, .opcode = "call_oz",  .api = "GN_SIP" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x3A}, .opcode = "call_oz",  .api = "GN_SOP" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x3C}, .opcode = "call_oz",  .api = "GN_SOE" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x3E}, .opcode = "call_oz",  .api = "GN_RBE" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x40}, .opcode = "call_oz",  .api = "GN_WBE" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x42}, .opcode = "call_oz",  .api = "GN_CME" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x44}, .opcode = "call_oz",  .api = "GN_XNX" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x46}, .opcode = "call_oz",  .api = "GN_XIN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x48}, .opcode = "call_oz",  .api = "GN_XDL" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x4A}, .opcode = "call_oz",  .api = "GN_ERR" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x4C}, .opcode = "call_oz",  .api = "GN_ESP" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x4E}, .opcode = "call_oz",  .api = "GN_FCM" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x50}, .opcode = "call_oz",  .api = "GN_FEX" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x52}, .opcode = "call_oz",  .api = "GN_OPW" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x54}, .opcode = "call_oz",  .api = "GN_WCL" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x56}, .opcode = "call_oz",  .api = "GN_WFN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x58}, .opcode = "call_oz",  .api = "GN_PRS" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x5A}, .opcode = "call_oz",  .api = "GN_PFS" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x5C}, .opcode = "call_oz",  .api = "GN_WSM" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x5E}, .opcode = "call_oz",  .api = "GN_ESA" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x60}, .opcode = "call_oz",  .api = "GN_OPF" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x62}, .opcode = "call_oz",  .api = "GN_CL" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x64}, .opcode = "call_oz",  .api = "GN_DEL" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x66}, .opcode = "call_oz",  .api = "GN_REN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x68}, .opcode = "call_oz",  .api = "GN_AAB" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x6A}, .opcode = "call_oz",  .api = "GN_FAB" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x6C}, .opcode = "call_oz",  .api = "GN_LAB" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x6E}, .opcode = "call_oz",  .api = "GN_UAB" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x70}, .opcode = "call_oz",  .api = "GN_ALP" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x72}, .opcode = "call_oz",  .api = "GN_M16" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x74}, .opcode = "call_oz",  .api = "GN_D16" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x76}, .opcode = "call_oz",  .api = "GN_M24" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x78}, .opcode = "call_oz",  .api = "GN_D24" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x7A}, .opcode = "call_oz",  .api = "GN_WIN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x7C}, .opcode = "call_oz",  .api = "GN_CRC" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x7E}, .opcode = "call_oz",  .api = "GN_GAB" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x80}, .opcode = "call_oz",  .api = "GN_LDM" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x82}, .opcode = "call_oz",  .api = "GN_ELF" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x84}, .opcode = "call_oz",  .api = "GN_GHN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x86}, .opcode = "call_oz",  .api = "GN_PHN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x88}, .opcode = "call_oz",  .api = "GN_DIR" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x8A}, .opcode = "call_oz",  .api = "GN_MOV" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x8C}, .opcode = "call_oz",  .api = "GN_CPY" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x09, 0x8E}, .opcode = "call_oz",  .api = "GN_LUT" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x06}, .opcode = "call_oz",  .api = "DC_INI" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x08}, .opcode = "call_oz",  .api = "DC_BYE" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x0A}, .opcode = "call_oz",  .api = "DC_ENT" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x0C}, .opcode = "call_oz",  .api = "DC_NAM" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x0E}, .opcode = "call_oz",  .api = "DC_IN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x10}, .opcode = "call_oz",  .api = "DC_OUT" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x12}, .opcode = "call_oz",  .api = "DC_PRT" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x14}, .opcode = "call_oz",  .api = "DC_ICL" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x16}, .opcode = "call_oz",  .api = "DC_NQ" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x18}, .opcode = "call_oz",  .api = "DC_SP" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x1A}, .opcode = "call_oz",  .api = "DC_ALT" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x1C}, .opcode = "call_oz",  .api = "DC_RBD" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x1E}, .opcode = "call_oz",  .api = "DC_XIN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x20}, .opcode = "call_oz",  .api = "DC_GEN" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x22}, .opcode = "call_oz",  .api = "DC_POL" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x24}, .opcode = "call_oz",  .api = "DC_UPD" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x26}, .opcode = "call_oz",  .api = "DC_ELF" },
    { .rst = 0xe7, .length = 0x02, .bytes = {0x0C, 0x28}, .opcode = "call_oz",  .api = "DC_RTE" },
    { .length = -1 }
};

static rsthelper zx_helpers[] = {
    // Error codes
    { .rst = 0xcf, .length = 0x01, .bytes = { 0xff }, .api = "Ok" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x00 }, .api = "NEXT without FOR" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x01 }, .api = "Variable not found" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x02 }, .api = "Subscript wrong" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x03 }, .api = "Out of memory" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x04 }, .api = "Out of screen" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x05 }, .api = "Number too big" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x06 }, .api = "RETURN without GOSUB" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x07 }, .api = "End of file" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x08 }, .api = "STOP statement" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x09 }, .api = "Invalid argument" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x0a }, .api = "Integer out of range" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x0b }, .api = "Nonsense in BASIC" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x0c }, .api = "BREAK - CONT repeat" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x0d }, .api = "Out of DATA" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x0e }, .api = "Invalid file name" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x0f }, .api = "No room for line" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x10 }, .api = "STOP in INPUT" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x11 }, .api = "FOR without NEXT" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x12 }, .api = "Invalid I/O device" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x13 }, .api = "Invalid colour" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x14 }, .api = "BREAK into program" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x15 }, .api = "RAMTOP no good" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x16 }, .api = "Statement lost" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x17 }, .api = "Invalid stream" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x18 }, .api = "FN without DEF" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x19 }, .api = "Parameter error" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x1a }, .api = "Tape loading error" },
    
    // https://mdfs.net/Docs/Comp/Spectrum/Interface1/Hooks
    // +RAMSoft Disciple/+d technical guide
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x1b }, .api = "CONSIN (IF1+GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x1c }, .api = "CONSOUT (IF1+GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x1d }, .api = "IF1_serin (IF1)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x1e }, .api = "IF1_serout (IF1)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x1f }, .api = "PRTOUT (IF1+GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x20 }, .api = "KBDTST (IF1+GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x21 }, .api = "SELDRV (IF1+GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x22 }, .api = "OPTMPM (IF1+GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x23 }, .api = "CLOSEM (IF1+GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x24 }, .api = "ERASE (IF1+GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x25 }, .api = "RDSEQ (IF1+GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x26 }, .api = "WRREC (IF1+GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x27 }, .api = "IF1_read_rand (IF1)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x28 }, .api = "IF1_rd_sector (IF1)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x29 }, .api = "IF1_next (IF1)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x2a }, .api = "IF1_wr_sector (IF1)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x2b }, .api = "OPTMPM (IF1+GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x2c }, .api = "DELBUF (IF1+GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x2d }, .api = "IF1_open_n (IF1)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x2e }, .api = "IF1_close_n (IF1)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x2f }, .api = "IF1_read_n (IF1)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x30 }, .api = "IF1_write_n (IF1)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x31 }, .api = "IF1_newvars (IF1)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x32 }, .api = "IF1_shadow (IF1)" },
    //{ .rst = 0xcf, .length = 0x01, .bytes = { 0x33 }, .api = "IF1_rd_header" },
    //{ .rst = 0xcf, .length = 0x01, .bytes = { 0x34 }, .api = "IF1_open_b" },

    // +D/DISCiPLE hook codes
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x33 }, .api = "HXFER (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x34 }, .api = "OSFM (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x35 }, .api = "HOFLE (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x36 }, .api = "SBYT (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x37 }, .api = "HSVBK (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x38 }, .api = "CFSM (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x39 }, .api = "PNTP (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x3a }, .api = "COPS (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x3b }, .api = "HGFLE (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x3c }, .api = "LBYT (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x3d }, .api = "HLDBK (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x3e }, .api = "WSAD (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x3f }, .api = "RSAD (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x40 }, .api = "REST (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x41 }, .api = "HERAZ (GDOS)" },
    // 0x42 = large screen dump
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x43 }, .api = "PCAT (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x44 }, .api = "HRSAD (GDOS)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x45 }, .api = "HWSAD (GDOS)" },
    // 0x46 = streams?
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x47 }, .api = "PATCH (GDOS)" },

    // Unidos
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x48 }, .api = "UNI_load_file (Unidos)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x49 }, .api = "UNI_verify_file (Unidos)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x4a }, .api = "UNI_merge_file (Unidos)"  },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x4b }, .api = "UNI_save_file (Unidos)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x4c }, .api = "UNI_open_file (Unidos)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x4d }, .api = "UNI_point (Unidos)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x4e }, .api = "UNI_flush (Unidos)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x4f }, .api = "UNI_close_file (Unidos)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x50 }, .api = "UNI_clear_channels (Unidos)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x51 }, .api = "UNI_rename_file (Unidos)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x52 }, .api = "UNI_move_stream (Unidos)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x53 }, .api = "UNI_move_file (Unidos)" },
    { .rst = 0xcf, .length = 0x01, .bytes = { 0x54 }, .api = "UNI_chdir (Unidos)" },

    // ESXDOS
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x80, .api = "ESXDOS_SYS_DISK_STATUS" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x81, .api = "ESXDOS_SYS_DISK_READ" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x82, .api = "ESXDOS_SYS_DISK_WRITE" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x83, .api = "ESXDOS_SYS_DISK_IOCTL" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x84, .api = "ESXDOS_SYS_DISK_INFO" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x88, .api = "ESXDOS_SYS_M_DOSVERSION" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x89, .api = "ESXDOS_SYS_M_GETSETDRV" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x8a, .api = "ESXDOS_SYS_M_DRIVEINFO" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x8b, .api = "ESXDOS_SYS_M_TAPEIN" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x8c, .api = "ESXDOS_SYS_M_TAPEOUT" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x8d, .api = "ESXDOS_SYS_M_GETHANDLE" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x8e, .api = "ESXDOS_SYS_M_GETDATE" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x98, .api = "ESXDOS_SYS_F_MOUNT" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x99, .api = "ESXDOS_SYS_F_UMOUNT" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x9a, .api = "ESXDOS_SYS_F_OPEN" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x9b, .api = "ESXDOS_SYS_F_CLOSE" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x9c, .api = "ESXDOS_SYS_F_SYNC" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x9d, .api = "ESXDOS_SYS_F_READ" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x9e, .api = "ESXDOS_SYS_F_WRITE" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x9f, .api = "ESXDOS_SYS_F_SEEK" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xa0, .api = "ESXDOS_SYS_F_FGETPOS" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xa1, .api = "ESXDOS_SYS_F_FSTAT" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xa2, .api = "ESXDOS_SYS_F_FTRUNCATE" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xa3, .api = "ESXDOS_SYS_F_OPENDIR" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xa4, .api = "ESXDOS_SYS_F_READDIR" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xa5, .api = "ESXDOS_SYS_F_TELLDIR" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xa6, .api = "ESXDOS_SYS_F_SEEKDIR" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xa7, .api = "ESXDOS_SYS_F_REWINDDIR" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xa8, .api = "ESXDOS_SYS_F_GETCWD" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xa9, .api = "ESXDOS_SYS_F_CHDIR" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xaa, .api = "ESXDOS_SYS_F_MKDIR" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xab, .api = "ESXDOS_SYS_F_RMDIR" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xac, .api = "ESXDOS_SYS_F_STAT" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xad, .api = "ESXDOS_SYS_F_UNLINK" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xae, .api = "ESXDOS_SYS_F_TRUNCATE" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xaf, .api = "ESXDOS_SYS_F_CHMOD" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xb0, .api = "ESXDOS_SYS_F_RENAME" },
    { .rst = 0xcf, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xb1, .api = "ESXDOS_SYS_F_GETFREE" },



    // Floating point calculator
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_BYTE, .bytes = { 0x00 }, .api = "ZXFP_JUMP_TRUE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x01 }, .api = "ZXFP_EXCHANGE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x02 }, .api = "ZXFP_DELETE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x03 }, .api = "ZXFP_SUBTRACT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x04 }, .api = "ZXFP_MULTIPLY" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x05 }, .api = "ZXFP_DIVISION" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x06 }, .api = "ZXFP_TO_POWER" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x07 }, .api = "ZXFP_OR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x08 }, .api = "ZXFP_NO_AND_NO" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x09 }, .api = "ZXFP_NO_L_EQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x0a }, .api = "ZXFP_NO_GR_EQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x0b }, .api = "ZXFP_NOS_NEQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x0c }, .api = "ZXFP_NO_GRTR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x0d }, .api = "ZXFP_NO_LESS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x0e }, .api = "ZXFP_NOS_EQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x0f }, .api = "ZXFP_ADDITION" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x10 }, .api = "ZXFP_STR_AND_NO" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x11 }, .api = "ZXFP_STR_L_EQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x12 }, .api = "ZXFP_STR_GR_EQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x13 }, .api = "ZXFP_STRS_NEQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x14 }, .api = "ZXFP_STRS_GRTR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x15 }, .api = "ZXFP_STRS_LESS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x16 }, .api = "ZXFP_STRS_EQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x17 }, .api = "ZXFP_STRS_ADD" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x18 }, .api = "ZXFP_VAL_STR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x19 }, .api = "ZXFP_USR_STR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x1a }, .api = "ZXFP_READ_IN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x1b }, .api = "ZXFP_NEGATE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x1c }, .api = "ZXFP_CODE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x1d }, .api = "ZXFP_VAL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x1e }, .api = "ZXFP_LEN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x1f }, .api = "ZXFP_SIN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x20 }, .api = "ZXFP_COS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x21 }, .api = "ZXFP_TAN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x22 }, .api = "ZXFP_ASN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x23 }, .api = "ZXFP_ACS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x24 }, .api = "ZXFP_ATN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x25 }, .api = "ZXFP_LN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x26 }, .api = "ZXFP_EXP" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x27 }, .api = "ZXFP_INT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x28 }, .api = "ZXFP_SQR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x29 }, .api = "ZXFP_SGN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x2a }, .api = "ZXFP_ABS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x2b }, .api = "ZXFP_PEEK" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x2c }, .api = "ZXFP_IN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x2d }, .api = "ZXFP_USR_NO" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x2e }, .api = "ZXFP_STRS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x2f }, .api = "ZXFP_CHRS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x30 }, .api = "ZXFP_NOT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x31 }, .api = "ZXFP_DUPLICATE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x32 }, .api = "ZXFP_N_MOD_M" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_BYTE, .bytes = { 0x33 }, .api = "ZXFP_JUMP" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_LEN67, .bytes = { 0x34 }, .api = "ZXFP_STK_DATA" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x35 }, .api = "ZXFP_DEC_JR_NZ" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x36 }, .api = "ZXFP_LESS_0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x37 }, .api = "ZXFP_GREATER_0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_END, .bytes = { 0x38 }, .api = "ZXFP_END_CALC" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x39 }, .api = "ZXFP_GET_ARGT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x3a }, .api = "ZXFP_TRUNCATE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x3b }, .api = "ZXFP_FP_CALC_2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x3c }, .api = "ZXFP_E_TO_FP" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x3d }, .api = "ZXFP_RESTACK" },

    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x80 }, .api = "ZXFP_SERIES_06" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x90 }, .api = "ZXFP_SERIES_08" },


    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xa0 }, .api = "ZXFP_STK_ZERO" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xa1 }, .api = "ZXFP_STK_ONE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xa2 }, .api = "ZXFP_STK_HALF" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xa3 }, .api = "ZXFP_STK_PI_D_2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xa4 }, .api = "ZXFP_STK_TEN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xc0 }, .api = "ZXFP_ST_MEM_0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xc1 }, .api = "ZXFP_ST_MEM_1" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xc2 }, .api = "ZXFP_ST_MEM_2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xc3 }, .api = "ZXFP_ST_MEM_3" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xc4 }, .api = "ZXFP_ST_MEM_4" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xc5 }, .api = "ZXFP_ST_MEM_5" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xe0 }, .api = "ZXFP_GET_MEM_0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xe1 }, .api = "ZXFP_GET_MEM_1" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xe2 }, .api = "ZXFP_GET_MEM_2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xe3 }, .api = "ZXFP_GET_MEM_3" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xe4 }, .api = "ZXFP_GET_MEM_4" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xe5 }, .api = "ZXFP_GET_MEM_5" },


    { .length = -1 }
};

static rsthelper sam_helpers[] = {
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x00 }, .api = "SAMFP_MULT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x01 }, .api = "SAMFP_ADDN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x02 }, .api = "SAMFP_CONCAT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x03 }, .api = "SAMFP_SUBN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x04 }, .api = "SAMFP_POWER" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x05 }, .api = "SAMFP_DIVN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x06 }, .api = "SAMFP_SWOP" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x07 }, .api = "SAMFP_DROP" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x08 }, .api = "SAMFP_MOD" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x09 }, .api = "SAMFP_IDIV" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x0a }, .api = "SAMFP_BOR" },
    // 0x0b = reserved
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x0c }, .api = "SAMFP_BAND" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x0d }, .api = "SAMFP_NUOR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x0e }, .api = "SAMFP_NUAND" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0xf4 }, .api = "SAMFP_NOTE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x10 }, .api = "SAMFP_NLESE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x11 }, .api = "SAMFP_NGRTE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x12 }, .api = "SAMFP_NLESS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x13 }, .api = "SAMFP_NEQUAL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x14 }, .api = "SAMFP_NGRTR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x15 }, .api = "SAMFP_SAND" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x16 }, .api = "SAMFP_SNOTE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x17 }, .api = "SAMFP_SLESE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x18 }, .api = "SAMFP_SGRTE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x19 }, .api = "SAMFP_SLESS" },

    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x1a }, .api = "SAMFP_SEQUAL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x1b }, .api = "SAMFP_SGRTR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x1c }, .api = "SAMFP_SWOp13" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = { 0x1d }, .api = "SAMFP_SWOp23" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_BYTE, .bytes = { 0x1e }, .api = "SAMFP_JPTRUE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_BYTE, .bytes = { 0x1f }, .api = "SAMFP_JFFALSE" },


    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_BYTE, .bytes = { 0x20 }, .api = "SAMFP_JUMP" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_BYTE, .bytes = 0x21, .api = "SAMFP_LDBREG" },   // Just loads next byte
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_BYTE, .bytes = 0x22, .api = "SAMFP_DECB" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x23, .api = "SAMFP_STKBREG" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x24, .api = "SAMFP_USEB" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x25, .api = "SAMFP_DUP" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_BYTE, .bytes = 0x26, .api = "SAMFP_ONELIT" },     // 1 following
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_5BYTES, .bytes = 0x27, .api = "SAMFP_FIVELIT" },    // 5 following 
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_nBYTES, .bytes = 0x28, .api = "SAMFP_SOMELIT" },    // next bytes speciies how many
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_WORD, .bytes = 0x29, .api = "SAMFP_LKADDRB" },    // Reads next 2 bytes
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_WORD, .bytes = 0x2A, .api = "SAMFP_LKADDRW" },    // Reads next 2 bytes
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x2B, .api = "SAMFP_REDARG" }, 
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x2C, .api = "SAMFP_LESS0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x2D, .api = "SAMFP_LESE0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x2E, .api = "SAMFP_GRTR0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x2F, .api = "SAMFP_GRTE0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x30, .api = "SAMFP_TRUNC" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x31, .api = "SAMFP_RESTACK" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x32, .api = "SAMFP_POWR2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_END, .bytes = 0x33, .api = "SAMFP_EXIT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_END, .bytes = 0x34, .api = "SAMFP_EXIT2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x39, .api = "SAMFP_SIN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x3A, .api = "SAMFP_COS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x3B, .api = "SAMFP_TAN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x3C, .api = "SAMFP_ASN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x3D, .api = "SAMFP_ACS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x3E, .api = "SAMFP_ATN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x3F, .api = "SAMFP_LOGN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x40, .api = "SAMFP_EXP" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x41, .api = "SAMFP_ABS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x42, .api = "SAMFP_SQN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x43, .api = "SAMFP_SOR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x44, .api = "SAMFP_INT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x45, .api = "SAMFP_USR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x46, .api = "SAMFP_IN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x47, .api = "SAMFP_PEEK" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x48, .api = "SAMFP_DPEEK" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x49, .api = "SAMFP_DVAR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x4A, .api = "SAMFP_SVAR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x4B, .api = "SAMFP_BUTTON" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x4C, .api = "SAMFP_EOF" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x4D, .api = "SAMFP_PTR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x4F, .api = "SAMFP_UDG" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x50, .api = "SAMFP_NUMBER" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x51, .api = "SAMFP_LEN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x52, .api = "SAMFP_CODE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x53, .api = "SAMFP_VALDOLLAR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x54, .api = "SAMFP_VAL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x55, .api = "SAMFP_TRUNCDOLLAR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x56, .api = "SAMFP_CHR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x57, .api = "SAMFP_STR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x58, .api = "SAMFP_BIN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x59, .api = "SAMFP_HEX" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x5A, .api = "SAMFP_USRDOLLAR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x5B, .api = "SAMFP_INKEY" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x5C, .api = "SAMFP_NOT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x5D, .api = "SAMFP_NEGATE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xC8, .api = "SAMFP_STOD0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xC9, .api = "SAMFP_STOD1" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xCA, .api = "SAMFP_STOD2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xCB, .api = "SAMFP_STOD3" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xCC, .api = "SAMFP_STOD4" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xCD, .api = "SAMFP_STOD5" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xD0, .api = "SAMFP_STO0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xD1, .api = "SAMFP_STOl" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xD2, .api = "SAMFP_STO2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xD3, .api = "SAMFP_STO3" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xD4, .api = "SAMFP_STO4" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xD5, .api = "SAMFP_STO5" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xD8, .api = "SAMFP_RCL0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xD9, .api = "SAMFP_RCLl" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xDA, .api = "SAMFP_RCL2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xDB, .api = "SAMFP_RCL3" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xDC, .api = "SAMFP_RCL4" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xDD, .api = "SAMFP_RCL5" },

    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xe0, .api = "SAMFP_STKHALF" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xe1, .api = "SAMFP_STKZERO" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xe2, .api = "SAMFP_STX1SK" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xe8, .api = "SAMFP_STKFONE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xe9, .api = "SAMFP_STKONE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xec, .api = "SAMFP_STKTEN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xed, .api = "SAMFP_STKRALFPI" },

    { .length = -1 }


};

static rsthelper zx81_helpers[] = {
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_BYTE, .bytes = 0x00, .api = "ZXFP_JUMP_TRUE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x01, .api = "ZXFP_EXCHANGE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x02, .api = "ZXFP_DELETE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x03, .api = "ZXFP_SUBTRACT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x04, .api = "ZXFP_MULTIPLY" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x05, .api = "ZXFP_DIVISION" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x06, .api = "ZXFP_TO_POWER" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x07, .api = "ZXFP_OR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x08, .api = "ZXFP_NO_AND_NO" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x09, .api = "ZXFP_NO_L_EQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x0A, .api = "ZXFP_NO_GR_EQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x0B, .api = "ZXFP_NOS_NEQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x0C, .api = "ZXFP_NO_GRTR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x0D, .api = "ZXFP_NO_LESS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x0E, .api = "ZXFP_NOS_EQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x0F, .api = "ZXFP_ADDITION" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x10, .api = "ZXFP_STR_AND_NO" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x11, .api = "ZXFP_STR_L_EQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x12, .api = "ZXFP_STR_GR_EQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x13, .api = "ZXFP_STRS_NEQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x14, .api = "ZXFP_STRS_GRTR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x15, .api = "ZXFP_STRS_LESS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x16, .api = "ZXFP_STRS_EQL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x17, .api = "ZXFP_STRS_ADD" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x18, .api = "ZXFP_NEGATE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x19, .api = "ZXFP_CODE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x1A, .api = "ZXFP_VAL" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x1B, .api = "ZXFP_LEN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x1C, .api = "ZXFP_SIN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x1D, .api = "ZXFP_COS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x1E, .api = "ZXFP_TAN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x1F, .api = "ZXFP_ASN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x20, .api = "ZXFP_ACS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x21, .api = "ZXFP_ATN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x22, .api = "ZXFP_LN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x23, .api = "ZXFP_EXP" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x24, .api = "ZXFP_INT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x25, .api = "ZXFP_SQR" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x26, .api = "ZXFP_SGN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x27, .api = "ZXFP_ABS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x28, .api = "ZXFP_PEEK" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x29, .api = "ZXFP_USR_NO" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x2A, .api = "ZXFP_STRS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x2B, .api = "ZXFP_CHRS" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x2C, .api = "ZXFP_NOT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x2D, .api = "ZXFP_DUPLICATE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x2E, .api = "ZXFP_N_MOD_M" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_BYTE, .bytes = 0x2F, .api = "ZXFP_JUMP" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_LEN67, .bytes = 0x30, .api = "ZXFP_STK_DATA" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x31, .api = "ZXFP_DEC_JR_NZ" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x32, .api = "ZXFP_LESS_0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x33, .api = "ZXFP_GREATER_0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE|F_END, .bytes = 0x34, .api = "ZXFP_END_CALC" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x35, .api = "ZXFP_GET_ARGT" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x36, .api = "ZXFP_TRUNCATE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x37, .api = "ZXFP_FP_CALC_2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x38, .api = "ZXFP_E_TO_FP" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x80, .api = "ZXFP_SERIES_00" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x81, .api = "ZXFP_SERIES_01" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x82, .api = "ZXFP_SERIES_02" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x83, .api = "ZXFP_SERIES_03" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x84, .api = "ZXFP_SERIES_04" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x85, .api = "ZXFP_SERIES_05" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x86, .api = "ZXFP_SERIES_06" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x87, .api = "ZXFP_SERIES_07" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x88, .api = "ZXFP_SERIES_08" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x89, .api = "ZXFP_SERIES_09" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x8A, .api = "ZXFP_SERIES_0A" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x8B, .api = "ZXFP_SERIES_0B" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x8C, .api = "ZXFP_SERIES_0C" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x8D, .api = "ZXFP_SERIES_0D" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x8E, .api = "ZXFP_SERIES_0E" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0x8F, .api = "ZXFP_SERIES_0F" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xA0, .api = "ZXFP_STK_ZERO" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xA1, .api = "ZXFP_STK_ONE" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xA2, .api = "ZXFP_STK_HALF" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xA3, .api = "ZXFP_STK_PI_D_2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xA4, .api = "ZXFP_STK_TEN" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xC0, .api = "ZXFP_ST_MEM_0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xC1, .api = "ZXFP_ST_MEM_1" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xC2, .api = "ZXFP_ST_MEM_2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xC3, .api = "ZXFP_ST_MEM_3" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xC4, .api = "ZXFP_ST_MEM_4" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xC5, .api = "ZXFP_ST_MEM_5" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xE0, .api = "ZXFP_GET_MEM_0" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xE1, .api = "ZXFP_GET_MEM_1" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xE2, .api = "ZXFP_GET_MEM_2" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xE3, .api = "ZXFP_GET_MEM_3" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xE4, .api = "ZXFP_GET_MEM_4" },
    { .rst = 0xef, .length = 0x01, .flags = F_SEQUENCE, .bytes = 0xE5, .api = "ZXFP_GET_MEM_5" },
    { .length = -1 }
};



#endif