/* generated by make_init.pl memalloc.h strpool.h errors.h file.h codearea.h */

/* includes */
#include "memalloc.h"   			/* before any other include */

#include "init.h"
#undef main							/* define main only in user code */

/* declare functions */
extern int 	user_main(int argc, char *argv[]);
static void init();

/* initialize all modules */
static void init()
{

  
	init_memalloc();
  

  
	xatexit( fini_memalloc );
  

  
	init_strpool();
  

  
	xatexit( fini_strpool );
  

  
	init_errors();
  

  
	xatexit( fini_errors );
  

  
	init_codearea();
  

  
	xatexit( fini_codearea );
  

}

/* new main function to init and call user main */
int main(int argc, char *argv[])
{
    init();
    return user_main(argc, argv);
}