/* generated by make_init.pl memalloc.h strpool.h errors.h */

#include "memalloc.h"   /* before any other include */

#include <stdlib.h>
#include <stdio.h>
#include <glib.h>

#include "memalloc.h"
#include "strpool.h"
#include "errors.h"



/* register atexit(), die on error */
static void xatexit(void (*fini)(void))
{
	if (atexit(fini) ) {
		fprintf(stderr, "atexit() failed\n");
		exit(1);
	}
}

/* initialize all modules */
static void init()
{
	init_memalloc();
    xatexit(fini_memalloc);
    init_strpool();
    xatexit(fini_strpool);
    init_errors();
    xatexit(fini_errors);
}

/* new main function to init and call user main */
extern int user_main(int argc, char *argv[]);
int main(int argc, char *argv[])
{
    init();
    return user_main(argc, argv);
}

