/*
     ZZZZZZZZZZZZZZZZZZZZ    8888888888888       00000000000
   ZZZZZZZZZZZZZZZZZZZZ    88888888888888888    0000000000000
                ZZZZZ      888           888  0000         0000
              ZZZZZ        88888888888888888  0000         0000
            ZZZZZ            8888888888888    0000         0000       AAAAAA         SSSSSSSSSSS   MMMM       MMMM
          ZZZZZ            88888888888888888  0000         0000      AAAAAAAA      SSSS            MMMMMM   MMMMMM
        ZZZZZ              8888         8888  0000         0000     AAAA  AAAA     SSSSSSSSSSS     MMMMMMMMMMMMMMM
      ZZZZZ                8888         8888  0000         0000    AAAAAAAAAAAA      SSSSSSSSSSS   MMMM MMMMM MMMM
    ZZZZZZZZZZZZZZZZZZZZZ  88888888888888888    0000000000000     AAAA      AAAA           SSSSS   MMMM       MMMM
  ZZZZZZZZZZZZZZZZZZZZZ      8888888888888       00000000000     AAAA        AAAA  SSSSSSSSSSS     MMMM       MMMM

Copyright (C) Paulo Custodio, 2011-2014

Define ragel-based parser. 

$Header: /home/dom/z88dk-git/cvs/z88dk/src/z80asm/parse.c,v 1.9 2014-12-13 00:49:45 pauloscustodio Exp $ 
*/

#include "xmalloc.h"   /* before any other include */

#include "codearea.h"
#include "init.h"
#include "model.h"
#include "parse.h"
#include "scan.h"
#include "sym.h"
#include "symtab.h"

#define STRINGS_GROW	256
#define TOKENS_GROW		256
#define STACK_GROW		256

/*-----------------------------------------------------------------------------
* 	Static - current scan context
*----------------------------------------------------------------------------*/

typedef struct token_t {
	int		 tok;						/* token ID */
	char	*string;					/* string saved in strpool */
	int		 number;					/* number value */
} Token;

/* array of tokens in the current statement */
static Token *tokens, *p, *pe, *eof;
static int    tokens_len, tokens_size;

/* strings saved from the current statement */
static char *strings;
static int   strings_len, strings_size;

/* Ragel state variables */
static int cs;							/* current state */
static int *stack, top, stack_size;		/* stack of states */

/* Statement label, NULL if none */
static char *stmt_label;

/*-----------------------------------------------------------------------------
*   Cleanup memory at end
*----------------------------------------------------------------------------*/
DEFINE_init()
{
}

DEFINE_fini()
{
	xfree(tokens);
	xfree(strings);
}

/*-----------------------------------------------------------------------------
*   Import parser generated by ragel
*----------------------------------------------------------------------------*/
#include "parse_rules.h"

/*-----------------------------------------------------------------------------
*   String pool for the current statement
*----------------------------------------------------------------------------*/
static char *strings_add(char *str)
{
	int size;
	char *copy;

	if (!str || str[0] == '\0')		/* NULL or empty string */
		return "";

	size = strlen(str) + 1;
	while (strings_len + size >= strings_size)
	{
		strings_size += STRINGS_GROW;
		strings = xrealloc(strings, strings_size);
	}
	copy = strings + strings_len;
	memcpy(copy, str, size);
	strings_len += size;

	return copy;
}

/*-----------------------------------------------------------------------------
*   Read tokens from the current statement into tokensd[], to be parsed
*	by state machine
*----------------------------------------------------------------------------*/
static void read_tokens(void)
{
	int i;

	i = tokens_len;
	while (TRUE)
	{
		/* grow tokens[] if needed */
		if (i >= tokens_size)
		{
			tokens_size += TOKENS_GROW;
			tokens = xrealloc(tokens, tokens_size * sizeof(Token));
		}
		tokens[i].tok = sym.tok;
		tokens[i].string = strings_add(sym.string);
		tokens[i].number = sym.number;
		i++;
		tokens_len = i;

		if (sym.tok == TK_END || sym.tok == TK_NEWLINE)
			break;

		GetSym();
	}
}

static void free_tokens(void)
{
	tokens_len = 0;
	strings_len = 0;
}

/*-----------------------------------------------------------------------------
*   Parse one statement, if possible
*----------------------------------------------------------------------------*/
Bool parse_statement(Bool compile_active)
{
	Bool parse_ok;

	init();

	save_scan_state();
	
	read_tokens();
	stmt_label = NULL;
	parse_ok = _parse_statement(compile_active);
	free_tokens();

	if (!parse_ok)
		restore_scan_state();

	return parse_ok;
}
