/*
     ZZZZZZZZZZZZZZZZZZZZ    8888888888888       00000000000
   ZZZZZZZZZZZZZZZZZZZZ    88888888888888888    0000000000000
                ZZZZZ      888           888  0000         0000
              ZZZZZ        88888888888888888  0000         0000
            ZZZZZ            8888888888888    0000         0000       AAAAAA         SSSSSSSSSSS   MMMM       MMMM
          ZZZZZ            88888888888888888  0000         0000      AAAAAAAA      SSSS            MMMMMM   MMMMMM
        ZZZZZ              8888         8888  0000         0000     AAAA  AAAA     SSSSSSSSSSS     MMMMMMMMMMMMMMM
      ZZZZZ                8888         8888  0000         0000    AAAAAAAAAAAA      SSSSSSSSSSS   MMMM MMMMM MMMM
    ZZZZZZZZZZZZZZZZZZZZZ  88888888888888888    0000000000000     AAAA      AAAA           SSSSS   MMMM       MMMM
  ZZZZZZZZZZZZZZZZZZZZZ      8888888888888       00000000000     AAAA        AAAA  SSSSSSSSSSS     MMMM       MMMM

Copyright (C) Paulo Custodio, 2011-2014

Define ragel-based parser. 

$Header: /home/dom/z88dk-git/cvs/z88dk/src/z80asm/parse.c,v 1.11 2014-12-15 22:48:41 pauloscustodio Exp $ 
*/

#include "xmalloc.h"   /* before any other include */

#include "codearea.h"
#include "init.h"
#include "model.h"
#include "opcodes.h"
#include "parse.h"
#include "scan.h"
#include "sym.h"
#include "symtab.h"
#include "utarray.h"

/*-----------------------------------------------------------------------------
* 	Static - current scan context
*----------------------------------------------------------------------------*/

/* array of tokens in the current statement */
static Sym *p, *pe, *eof;
static UT_array *tokens;
static UT_icd ut_Sym_icd = { sizeof(Sym), NULL, NULL, NULL };

/* strings saved from the current statement */
static UT_array *token_strings;

/* Ragel state variables */
static int cs;							/* current state */

/* Ragel state stack */
static UT_array *state_stack;
static int *stack, top;

/* Statement label, NULL if none */
static char *stmt_label;

/*-----------------------------------------------------------------------------
*   Cleanup memory at end
*----------------------------------------------------------------------------*/
DEFINE_init()
{
	utarray_new(tokens, &ut_Sym_icd);
	utarray_new(token_strings, &ut_str_icd);
	utarray_new(state_stack, &ut_int_icd);
}

DEFINE_fini()
{
	utarray_free(tokens);
	utarray_free(token_strings);
	utarray_free(state_stack);
}

/*-----------------------------------------------------------------------------
*   Import parser generated by ragel
*----------------------------------------------------------------------------*/
#include "parse_rules.h"

/*-----------------------------------------------------------------------------
*   String pool for the current statement
*----------------------------------------------------------------------------*/
static char *token_strings_add(char *str)
{
	if (!str)		/* NULL string */
		return NULL;

	utarray_push_back(token_strings, &str);
	return *((char **)utarray_back(token_strings));
}

/*-----------------------------------------------------------------------------
*   Read tokens from the current statement into tokensd[], to be parsed
*	by state machine
*----------------------------------------------------------------------------*/
static void read_tokens(void)
{
	Sym sym_copy;

	while (TRUE)
	{
		sym_copy = sym;
		sym_copy.string = token_strings_add(sym.string);
		utarray_push_back(tokens, &sym_copy);

		if (sym.tok == TK_END || sym.tok == TK_NEWLINE)
			break;

		GetSym();
	}
}

static void free_tokens(void)
{
	utarray_clear(tokens);
	utarray_clear(token_strings);
}

/*-----------------------------------------------------------------------------
*   Parse one statement, if possible
*----------------------------------------------------------------------------*/
Bool parse_statement(Bool compile_active)
{
	Bool parse_ok;

	init();

	save_scan_state();
	
	read_tokens();
	stmt_label = NULL;
	parse_ok = _parse_statement(compile_active);
	free_tokens();

	if (!parse_ok)
		restore_scan_state();

	return parse_ok;
}
