/* generated by Template::Toolkit - do not edit */


#pragma once


#define _TK_END	0

#define _TK_NIL	1

#define _TK_NAME	2

#define _TK_LABEL	3

#define _TK_NUMBER	4

#define _TK_STRING	5

#define _TK_TERN_COND	6

#define _TK_NEWLINE	7

#define _TK_LOG_NOT	8

#define _TK_CONST_EXPR	9

#define _TK_MOD	10

#define _TK_BIN_AND	11

#define _TK_LOG_AND	12

#define _TK_LPAREN	13

#define _TK_RPAREN	14

#define _TK_MULTIPLY	15

#define _TK_PLUS	16

#define _TK_COMMA	17

#define _TK_MINUS	18

#define _TK_DOT	19

#define _TK_DIVIDE	20

#define _TK_COLON	21

#define _TK_LESS	22

#define _TK_LEFT_SHIFT	23

#define _TK_LESS_EQ	24

#define _TK_NOT_EQ	25

#define _TK_EQUAL	26

#define _TK_GREATER	27

#define _TK_RIGHT_SHIFT	28

#define _TK_GREATER_EQ	29

#define _TK_QUESTION	30

#define _TK_LSQUARE	31

#define _TK_RSQUARE	32

#define _TK_BIN_XOR	33

#define _TK_POWER	34

#define _TK_LCURLY	35

#define _TK_BIN_OR	36

#define _TK_LOG_OR	37

#define _TK_RCURLY	38

#define _TK_BIN_NOT	39

#define _TK_IND_C	40

#define _TK_IND_BC	41

#define _TK_IND_DE	42

#define _TK_IND_HL	43

#define _TK_IND_SP	44

#define _TK_IND_IX	45

#define _TK_IND_IY	46

#define _TK_IND_HLI	47

#define _TK_IND_HLD	48

#define _TK_ASMPC	49

#define _TK_NZ	50

#define _TK_Z	51

#define _TK_NC	52

#define _TK_C	53

#define _TK_PO	54

#define _TK_PE	55

#define _TK_P	56

#define _TK_M	57

#define _TK_LZ	58

#define _TK_LO	59

#define _TK_NV	60

#define _TK_V	61

#define _TK_B	62

#define _TK_D	63

#define _TK_E	64

#define _TK_H	65

#define _TK_L	66

#define _TK_A	67

#define _TK_F	68

#define _TK_I	69

#define _TK_R	70

#define _TK_IIR	71

#define _TK_EIR	72

#define _TK_XPC	73

#define _TK_IXH	74

#define _TK_IYH	75

#define _TK_IXL	76

#define _TK_IYL	77

#define _TK_X	78

#define _TK_BC	79

#define _TK_DE	80

#define _TK_HL	81

#define _TK_IX	82

#define _TK_IY	83

#define _TK_AF	84

#define _TK_SP	85

#define _TK_PSW	86

#define _TK_B1	87

#define _TK_C1	88

#define _TK_D1	89

#define _TK_E1	90

#define _TK_H1	91

#define _TK_L1	92

#define _TK_A1	93

#define _TK_F1	94

#define _TK_BC1	95

#define _TK_DE1	96

#define _TK_HL1	97

#define _TK_AF1	98

#define _TK_ALIGN	99

#define _TK_BINARY	100

#define _TK_BYTE	101

#define _TK_C_LINE	102

#define _TK_DB	103

#define _TK_DC	104

#define _TK_DDB	105

#define _TK_DEFB	106

#define _TK_DEFC	107

#define _TK_DEFDB	108

#define _TK_DEFGROUP	109

#define _TK_DEFINE	110

#define _TK_DEFM	111

#define _TK_DEFP	112

#define _TK_DEFQ	113

#define _TK_DEFS	114

#define _TK_DEFVARS	115

#define _TK_DEFW	116

#define _TK_DEPHASE	117

#define _TK_DM	118

#define _TK_DP	119

#define _TK_DQ	120

#define _TK_DS	121

#define _TK_DW	122

#define _TK_DWORD	123

#define _TK_ELIF	124

#define _TK_ELIFDEF	125

#define _TK_ELIFNDEF	126

#define _TK_ELSE	127

#define _TK_ENDIF	128

#define _TK_EXTERN	129

#define _TK_GLOBAL	130

#define _TK_IF	131

#define _TK_IFDEF	132

#define _TK_IFNDEF	133

#define _TK_INCLUDE	134

#define _TK_LIB	135

#define _TK_LINE	136

#define _TK_LSTOFF	137

#define _TK_LSTON	138

#define _TK_MODULE	139

#define _TK_ORG	140

#define _TK_PHASE	141

#define _TK_PTR	142

#define _TK_PUBLIC	143

#define _TK_SECTION	144

#define _TK_UNDEFINE	145

#define _TK_WORD	146

#define _TK_XDEF	147

#define _TK_XLIB	148

#define _TK_XREF	149

#define _TK_DS_B	150

#define _TK_DS_W	151

#define _TK_DS_P	152

#define _TK_DS_Q	153

#define _TK_ADC	154

#define _TK_ADD	155

#define _TK_AND	156

#define _TK_BIT	157

#define _TK_CALL	158

#define _TK_CCF	159

#define _TK_CCF1	160

#define _TK_CP	161

#define _TK_CPD	162

#define _TK_CPDR	163

#define _TK_CPI	164

#define _TK_CPIR	165

#define _TK_CPL	166

#define _TK_DAA	167

#define _TK_DEC	168

#define _TK_DI	169

#define _TK_DJNZ	170

#define _TK_EI	171

#define _TK_EX	172

#define _TK_EXX	173

#define _TK_HALT	174

#define _TK_IM	175

#define _TK_IN	176

#define _TK_INC	177

#define _TK_IND	178

#define _TK_INDR	179

#define _TK_INI	180

#define _TK_INIR	181

#define _TK_JP	182

#define _TK_JR	183

#define _TK_LD	184

#define _TK_LDH	185

#define _TK_LDHL	186

#define _TK_LDD	187

#define _TK_LDDR	188

#define _TK_LDI	189

#define _TK_LDIR	190

#define _TK_NEG	191

#define _TK_NOP	192

#define _TK_OR	193

#define _TK_OTDR	194

#define _TK_OTIR	195

#define _TK_OUT	196

#define _TK_OUTD	197

#define _TK_OUTI	198

#define _TK_POP	199

#define _TK_PUSH	200

#define _TK_RES	201

#define _TK_RET	202

#define _TK_RETI	203

#define _TK_RETN	204

#define _TK_RL	205

#define _TK_RLA	206

#define _TK_RLA1	207

#define _TK_RLC	208

#define _TK_RLCA	209

#define _TK_RLCA1	210

#define _TK_RLD	211

#define _TK_RR	212

#define _TK_RRA	213

#define _TK_RRA1	214

#define _TK_RRC	215

#define _TK_RRCA	216

#define _TK_RRCA1	217

#define _TK_RRD	218

#define _TK_RST	219

#define _TK_SBC	220

#define _TK_SCF	221

#define _TK_SCF1	222

#define _TK_SET	223

#define _TK_SLA	224

#define _TK_SLL	225

#define _TK_SLS	226

#define _TK_SLI	227

#define _TK_SRA	228

#define _TK_SRL	229

#define _TK_STOP	230

#define _TK_SUB	231

#define _TK_XOR	232

#define _TK_SWAPNIB	233

#define _TK_SWAP	234

#define _TK_OUTINB	235

#define _TK_LDIX	236

#define _TK_LDIRX	237

#define _TK_LDDX	238

#define _TK_LDDRX	239

#define _TK_LDIRSCALE	240

#define _TK_LDPIRX	241

#define _TK_LDWS	242

#define _TK_FILL	243

#define _TK_FILLDE	244

#define _TK_MIRROR	245

#define _TK_NEXTREG	246

#define _TK_PIXELDN	247

#define _TK_PIXELAD	248

#define _TK_SETAE	249

#define _TK_TEST	250

#define _TK_MMU	251

#define _TK_MMU0	252

#define _TK_MMU1	253

#define _TK_MMU2	254

#define _TK_MMU3	255

#define _TK_MMU4	256

#define _TK_MMU5	257

#define _TK_MMU6	258

#define _TK_MMU7	259

#define _TK_CU_WAIT	260

#define _TK_CU_MOVE	261

#define _TK_CU_STOP	262

#define _TK_CU_NOP	263

#define _TK_DMA_WR0	264

#define _TK_DMA_WR1	265

#define _TK_DMA_WR2	266

#define _TK_DMA_WR3	267

#define _TK_DMA_WR4	268

#define _TK_DMA_WR5	269

#define _TK_DMA_WR6	270

#define _TK_DMA_CMD	271

#define _TK_BSLA	272

#define _TK_BSRA	273

#define _TK_BSRL	274

#define _TK_BSRF	275

#define _TK_BRLC	276

#define _TK_SLP	277

#define _TK_MLT	278

#define _TK_IN0	279

#define _TK_OUT0	280

#define _TK_OTIM	281

#define _TK_OTIMR	282

#define _TK_OTDM	283

#define _TK_OTDMR	284

#define _TK_TST	285

#define _TK_TSTIO	286

#define _TK_ALTD	287

#define _TK_BOOL	288

#define _TK_IOE	289

#define _TK_IOI	290

#define _TK_IPRES	291

#define _TK_IPSET	292

#define _TK_IDET	293

#define _TK_LDDSR	294

#define _TK_LDISR	295

#define _TK_LDP	296

#define _TK_LSDR	297

#define _TK_LSIR	298

#define _TK_LSDDR	299

#define _TK_LSIDR	300

#define _TK_MUL	301

#define _TK_IP	302

#define _TK_SU	303

#define _TK_RDMODE	304

#define _TK_SETUSR	305

#define _TK_SURES	306

#define _TK_SYSCALL	307

#define _TK_UMA	308

#define _TK_UMS	309

#define _TK_CALL_OZ	310

#define _TK_CALL_PKG	311

#define _TK_FPP	312

#define _TK_INVOKE	313

#define _TK_MOV	314

#define _TK_MVI	315

#define _TK_LXI	316

#define _TK_LDA	317

#define _TK_STA	318

#define _TK_LHLD	319

#define _TK_SHLD	320

#define _TK_LDAX	321

#define _TK_STAX	322

#define _TK_XCHG	323

#define _TK_ADI	324

#define _TK_ACI	325

#define _TK_SUI	326

#define _TK_SBB	327

#define _TK_SBI	328

#define _TK_INR	329

#define _TK_DCR	330

#define _TK_INX	331

#define _TK_DCX	332

#define _TK_DAD	333

#define _TK_ANA	334

#define _TK_ANI	335

#define _TK_ORA	336

#define _TK_ORI	337

#define _TK_XRA	338

#define _TK_XRI	339

#define _TK_CMP	340

#define _TK_RAL	341

#define _TK_RAR	342

#define _TK_CMA	343

#define _TK_CMC	344

#define _TK_STC	345

#define _TK_JMP	346

#define _TK_JNC	347

#define _TK_JC	348

#define _TK_JNZ	349

#define _TK_JZ	350

#define _TK_JPO	351

#define _TK_JPE	352

#define _TK_JNV	353

#define _TK_JV	354

#define _TK_JLO	355

#define _TK_JLZ	356

#define _TK_JM	357

#define _TK_JK	358

#define _TK_JX5	359

#define _TK_JNK	360

#define _TK_JNX5	361

#define _TK_J_NC	362

#define _TK_J_C	363

#define _TK_J_NZ	364

#define _TK_J_Z	365

#define _TK_J_PO	366

#define _TK_J_PE	367

#define _TK_J_NV	368

#define _TK_J_V	369

#define _TK_J_LO	370

#define _TK_J_LZ	371

#define _TK_J_P	372

#define _TK_J_M	373

#define _TK_J_K	374

#define _TK_J_X5	375

#define _TK_J_NK	376

#define _TK_J_NX5	377

#define _TK_CNC	378

#define _TK_CC	379

#define _TK_CNZ	380

#define _TK_CZ	381

#define _TK_CPO	382

#define _TK_CPE	383

#define _TK_CNV	384

#define _TK_CV	385

#define _TK_CLO	386

#define _TK_CLZ	387

#define _TK_CM	388

#define _TK_C_NC	389

#define _TK_C_C	390

#define _TK_C_NZ	391

#define _TK_C_Z	392

#define _TK_C_PO	393

#define _TK_C_PE	394

#define _TK_C_NV	395

#define _TK_C_V	396

#define _TK_C_LO	397

#define _TK_C_LZ	398

#define _TK_C_P	399

#define _TK_C_M	400

#define _TK_RNC	401

#define _TK_RC	402

#define _TK_RNZ	403

#define _TK_RZ	404

#define _TK_RPO	405

#define _TK_RPE	406

#define _TK_RNV	407

#define _TK_RV	408

#define _TK_RLO	409

#define _TK_RLZ	410

#define _TK_RP	411

#define _TK_RM	412

#define _TK_R_NC	413

#define _TK_R_C	414

#define _TK_R_NZ	415

#define _TK_R_Z	416

#define _TK_R_PO	417

#define _TK_R_PE	418

#define _TK_R_NV	419

#define _TK_R_V	420

#define _TK_R_LO	421

#define _TK_R_LZ	422

#define _TK_R_P	423

#define _TK_R_M	424

#define _TK_PCHL	425

#define _TK_XTHL	426

#define _TK_SPHL	427

#define _TK_HLT	428

#define _TK_RIM	429

#define _TK_SIM	430

#define _TK_DSUB	431

#define _TK_ARHL	432

#define _TK_RRHL	433

#define _TK_RDEL	434

#define _TK_RLDE	435

#define _TK_LDHI	436

#define _TK_LDSI	437

#define _TK_RSTV	438

#define _TK_OVRST8	439

#define _TK_SHLX	440

#define _TK_SHLDE	441

#define _TK_LHLX	442

#define _TK_LHLDE	443


#ifndef NO_TOKEN_ENUM
typedef enum tokid_t
{

	TK_END	= 0,

	TK_NIL	= 1,

	TK_NAME	= 2,

	TK_LABEL	= 3,

	TK_NUMBER	= 4,

	TK_STRING	= 5,

	TK_TERN_COND	= 6,

	TK_NEWLINE	= 7,

	TK_LOG_NOT	= 8,

	TK_CONST_EXPR	= 9,

	TK_MOD	= 10,

	TK_BIN_AND	= 11,

	TK_LOG_AND	= 12,

	TK_LPAREN	= 13,

	TK_RPAREN	= 14,

	TK_MULTIPLY	= 15,

	TK_PLUS	= 16,

	TK_COMMA	= 17,

	TK_MINUS	= 18,

	TK_DOT	= 19,

	TK_DIVIDE	= 20,

	TK_COLON	= 21,

	TK_LESS	= 22,

	TK_LEFT_SHIFT	= 23,

	TK_LESS_EQ	= 24,

	TK_NOT_EQ	= 25,

	TK_EQUAL	= 26,

	TK_GREATER	= 27,

	TK_RIGHT_SHIFT	= 28,

	TK_GREATER_EQ	= 29,

	TK_QUESTION	= 30,

	TK_LSQUARE	= 31,

	TK_RSQUARE	= 32,

	TK_BIN_XOR	= 33,

	TK_POWER	= 34,

	TK_LCURLY	= 35,

	TK_BIN_OR	= 36,

	TK_LOG_OR	= 37,

	TK_RCURLY	= 38,

	TK_BIN_NOT	= 39,

	TK_IND_C	= 40,

	TK_IND_BC	= 41,

	TK_IND_DE	= 42,

	TK_IND_HL	= 43,

	TK_IND_SP	= 44,

	TK_IND_IX	= 45,

	TK_IND_IY	= 46,

	TK_IND_HLI	= 47,

	TK_IND_HLD	= 48,

	TK_ASMPC	= 49,

	TK_NZ	= 50,

	TK_Z	= 51,

	TK_NC	= 52,

	TK_C	= 53,

	TK_PO	= 54,

	TK_PE	= 55,

	TK_P	= 56,

	TK_M	= 57,

	TK_LZ	= 58,

	TK_LO	= 59,

	TK_NV	= 60,

	TK_V	= 61,

	TK_B	= 62,

	TK_D	= 63,

	TK_E	= 64,

	TK_H	= 65,

	TK_L	= 66,

	TK_A	= 67,

	TK_F	= 68,

	TK_I	= 69,

	TK_R	= 70,

	TK_IIR	= 71,

	TK_EIR	= 72,

	TK_XPC	= 73,

	TK_IXH	= 74,

	TK_IYH	= 75,

	TK_IXL	= 76,

	TK_IYL	= 77,

	TK_X	= 78,

	TK_BC	= 79,

	TK_DE	= 80,

	TK_HL	= 81,

	TK_IX	= 82,

	TK_IY	= 83,

	TK_AF	= 84,

	TK_SP	= 85,

	TK_PSW	= 86,

	TK_B1	= 87,

	TK_C1	= 88,

	TK_D1	= 89,

	TK_E1	= 90,

	TK_H1	= 91,

	TK_L1	= 92,

	TK_A1	= 93,

	TK_F1	= 94,

	TK_BC1	= 95,

	TK_DE1	= 96,

	TK_HL1	= 97,

	TK_AF1	= 98,

	TK_ALIGN	= 99,

	TK_BINARY	= 100,

	TK_BYTE	= 101,

	TK_C_LINE	= 102,

	TK_DB	= 103,

	TK_DC	= 104,

	TK_DDB	= 105,

	TK_DEFB	= 106,

	TK_DEFC	= 107,

	TK_DEFDB	= 108,

	TK_DEFGROUP	= 109,

	TK_DEFINE	= 110,

	TK_DEFM	= 111,

	TK_DEFP	= 112,

	TK_DEFQ	= 113,

	TK_DEFS	= 114,

	TK_DEFVARS	= 115,

	TK_DEFW	= 116,

	TK_DEPHASE	= 117,

	TK_DM	= 118,

	TK_DP	= 119,

	TK_DQ	= 120,

	TK_DS	= 121,

	TK_DW	= 122,

	TK_DWORD	= 123,

	TK_ELIF	= 124,

	TK_ELIFDEF	= 125,

	TK_ELIFNDEF	= 126,

	TK_ELSE	= 127,

	TK_ENDIF	= 128,

	TK_EXTERN	= 129,

	TK_GLOBAL	= 130,

	TK_IF	= 131,

	TK_IFDEF	= 132,

	TK_IFNDEF	= 133,

	TK_INCLUDE	= 134,

	TK_LIB	= 135,

	TK_LINE	= 136,

	TK_LSTOFF	= 137,

	TK_LSTON	= 138,

	TK_MODULE	= 139,

	TK_ORG	= 140,

	TK_PHASE	= 141,

	TK_PTR	= 142,

	TK_PUBLIC	= 143,

	TK_SECTION	= 144,

	TK_UNDEFINE	= 145,

	TK_WORD	= 146,

	TK_XDEF	= 147,

	TK_XLIB	= 148,

	TK_XREF	= 149,

	TK_DS_B	= 150,

	TK_DS_W	= 151,

	TK_DS_P	= 152,

	TK_DS_Q	= 153,

	TK_ADC	= 154,

	TK_ADD	= 155,

	TK_AND	= 156,

	TK_BIT	= 157,

	TK_CALL	= 158,

	TK_CCF	= 159,

	TK_CCF1	= 160,

	TK_CP	= 161,

	TK_CPD	= 162,

	TK_CPDR	= 163,

	TK_CPI	= 164,

	TK_CPIR	= 165,

	TK_CPL	= 166,

	TK_DAA	= 167,

	TK_DEC	= 168,

	TK_DI	= 169,

	TK_DJNZ	= 170,

	TK_EI	= 171,

	TK_EX	= 172,

	TK_EXX	= 173,

	TK_HALT	= 174,

	TK_IM	= 175,

	TK_IN	= 176,

	TK_INC	= 177,

	TK_IND	= 178,

	TK_INDR	= 179,

	TK_INI	= 180,

	TK_INIR	= 181,

	TK_JP	= 182,

	TK_JR	= 183,

	TK_LD	= 184,

	TK_LDH	= 185,

	TK_LDHL	= 186,

	TK_LDD	= 187,

	TK_LDDR	= 188,

	TK_LDI	= 189,

	TK_LDIR	= 190,

	TK_NEG	= 191,

	TK_NOP	= 192,

	TK_OR	= 193,

	TK_OTDR	= 194,

	TK_OTIR	= 195,

	TK_OUT	= 196,

	TK_OUTD	= 197,

	TK_OUTI	= 198,

	TK_POP	= 199,

	TK_PUSH	= 200,

	TK_RES	= 201,

	TK_RET	= 202,

	TK_RETI	= 203,

	TK_RETN	= 204,

	TK_RL	= 205,

	TK_RLA	= 206,

	TK_RLA1	= 207,

	TK_RLC	= 208,

	TK_RLCA	= 209,

	TK_RLCA1	= 210,

	TK_RLD	= 211,

	TK_RR	= 212,

	TK_RRA	= 213,

	TK_RRA1	= 214,

	TK_RRC	= 215,

	TK_RRCA	= 216,

	TK_RRCA1	= 217,

	TK_RRD	= 218,

	TK_RST	= 219,

	TK_SBC	= 220,

	TK_SCF	= 221,

	TK_SCF1	= 222,

	TK_SET	= 223,

	TK_SLA	= 224,

	TK_SLL	= 225,

	TK_SLS	= 226,

	TK_SLI	= 227,

	TK_SRA	= 228,

	TK_SRL	= 229,

	TK_STOP	= 230,

	TK_SUB	= 231,

	TK_XOR	= 232,

	TK_SWAPNIB	= 233,

	TK_SWAP	= 234,

	TK_OUTINB	= 235,

	TK_LDIX	= 236,

	TK_LDIRX	= 237,

	TK_LDDX	= 238,

	TK_LDDRX	= 239,

	TK_LDIRSCALE	= 240,

	TK_LDPIRX	= 241,

	TK_LDWS	= 242,

	TK_FILL	= 243,

	TK_FILLDE	= 244,

	TK_MIRROR	= 245,

	TK_NEXTREG	= 246,

	TK_PIXELDN	= 247,

	TK_PIXELAD	= 248,

	TK_SETAE	= 249,

	TK_TEST	= 250,

	TK_MMU	= 251,

	TK_MMU0	= 252,

	TK_MMU1	= 253,

	TK_MMU2	= 254,

	TK_MMU3	= 255,

	TK_MMU4	= 256,

	TK_MMU5	= 257,

	TK_MMU6	= 258,

	TK_MMU7	= 259,

	TK_CU_WAIT	= 260,

	TK_CU_MOVE	= 261,

	TK_CU_STOP	= 262,

	TK_CU_NOP	= 263,

	TK_DMA_WR0	= 264,

	TK_DMA_WR1	= 265,

	TK_DMA_WR2	= 266,

	TK_DMA_WR3	= 267,

	TK_DMA_WR4	= 268,

	TK_DMA_WR5	= 269,

	TK_DMA_WR6	= 270,

	TK_DMA_CMD	= 271,

	TK_BSLA	= 272,

	TK_BSRA	= 273,

	TK_BSRL	= 274,

	TK_BSRF	= 275,

	TK_BRLC	= 276,

	TK_SLP	= 277,

	TK_MLT	= 278,

	TK_IN0	= 279,

	TK_OUT0	= 280,

	TK_OTIM	= 281,

	TK_OTIMR	= 282,

	TK_OTDM	= 283,

	TK_OTDMR	= 284,

	TK_TST	= 285,

	TK_TSTIO	= 286,

	TK_ALTD	= 287,

	TK_BOOL	= 288,

	TK_IOE	= 289,

	TK_IOI	= 290,

	TK_IPRES	= 291,

	TK_IPSET	= 292,

	TK_IDET	= 293,

	TK_LDDSR	= 294,

	TK_LDISR	= 295,

	TK_LDP	= 296,

	TK_LSDR	= 297,

	TK_LSIR	= 298,

	TK_LSDDR	= 299,

	TK_LSIDR	= 300,

	TK_MUL	= 301,

	TK_IP	= 302,

	TK_SU	= 303,

	TK_RDMODE	= 304,

	TK_SETUSR	= 305,

	TK_SURES	= 306,

	TK_SYSCALL	= 307,

	TK_UMA	= 308,

	TK_UMS	= 309,

	TK_CALL_OZ	= 310,

	TK_CALL_PKG	= 311,

	TK_FPP	= 312,

	TK_INVOKE	= 313,

	TK_MOV	= 314,

	TK_MVI	= 315,

	TK_LXI	= 316,

	TK_LDA	= 317,

	TK_STA	= 318,

	TK_LHLD	= 319,

	TK_SHLD	= 320,

	TK_LDAX	= 321,

	TK_STAX	= 322,

	TK_XCHG	= 323,

	TK_ADI	= 324,

	TK_ACI	= 325,

	TK_SUI	= 326,

	TK_SBB	= 327,

	TK_SBI	= 328,

	TK_INR	= 329,

	TK_DCR	= 330,

	TK_INX	= 331,

	TK_DCX	= 332,

	TK_DAD	= 333,

	TK_ANA	= 334,

	TK_ANI	= 335,

	TK_ORA	= 336,

	TK_ORI	= 337,

	TK_XRA	= 338,

	TK_XRI	= 339,

	TK_CMP	= 340,

	TK_RAL	= 341,

	TK_RAR	= 342,

	TK_CMA	= 343,

	TK_CMC	= 344,

	TK_STC	= 345,

	TK_JMP	= 346,

	TK_JNC	= 347,

	TK_JC	= 348,

	TK_JNZ	= 349,

	TK_JZ	= 350,

	TK_JPO	= 351,

	TK_JPE	= 352,

	TK_JNV	= 353,

	TK_JV	= 354,

	TK_JLO	= 355,

	TK_JLZ	= 356,

	TK_JM	= 357,

	TK_JK	= 358,

	TK_JX5	= 359,

	TK_JNK	= 360,

	TK_JNX5	= 361,

	TK_J_NC	= 362,

	TK_J_C	= 363,

	TK_J_NZ	= 364,

	TK_J_Z	= 365,

	TK_J_PO	= 366,

	TK_J_PE	= 367,

	TK_J_NV	= 368,

	TK_J_V	= 369,

	TK_J_LO	= 370,

	TK_J_LZ	= 371,

	TK_J_P	= 372,

	TK_J_M	= 373,

	TK_J_K	= 374,

	TK_J_X5	= 375,

	TK_J_NK	= 376,

	TK_J_NX5	= 377,

	TK_CNC	= 378,

	TK_CC	= 379,

	TK_CNZ	= 380,

	TK_CZ	= 381,

	TK_CPO	= 382,

	TK_CPE	= 383,

	TK_CNV	= 384,

	TK_CV	= 385,

	TK_CLO	= 386,

	TK_CLZ	= 387,

	TK_CM	= 388,

	TK_C_NC	= 389,

	TK_C_C	= 390,

	TK_C_NZ	= 391,

	TK_C_Z	= 392,

	TK_C_PO	= 393,

	TK_C_PE	= 394,

	TK_C_NV	= 395,

	TK_C_V	= 396,

	TK_C_LO	= 397,

	TK_C_LZ	= 398,

	TK_C_P	= 399,

	TK_C_M	= 400,

	TK_RNC	= 401,

	TK_RC	= 402,

	TK_RNZ	= 403,

	TK_RZ	= 404,

	TK_RPO	= 405,

	TK_RPE	= 406,

	TK_RNV	= 407,

	TK_RV	= 408,

	TK_RLO	= 409,

	TK_RLZ	= 410,

	TK_RP	= 411,

	TK_RM	= 412,

	TK_R_NC	= 413,

	TK_R_C	= 414,

	TK_R_NZ	= 415,

	TK_R_Z	= 416,

	TK_R_PO	= 417,

	TK_R_PE	= 418,

	TK_R_NV	= 419,

	TK_R_V	= 420,

	TK_R_LO	= 421,

	TK_R_LZ	= 422,

	TK_R_P	= 423,

	TK_R_M	= 424,

	TK_PCHL	= 425,

	TK_XTHL	= 426,

	TK_SPHL	= 427,

	TK_HLT	= 428,

	TK_RIM	= 429,

	TK_SIM	= 430,

	TK_DSUB	= 431,

	TK_ARHL	= 432,

	TK_RRHL	= 433,

	TK_RDEL	= 434,

	TK_RLDE	= 435,

	TK_LDHI	= 436,

	TK_LDSI	= 437,

	TK_RSTV	= 438,

	TK_OVRST8	= 439,

	TK_SHLX	= 440,

	TK_SHLDE	= 441,

	TK_LHLX	= 442,

	TK_LHLDE	= 443,

} tokid_t;
#endif
