
// automatically generated by m4 from headers in proto subdir


#ifndef __ADT_BV_PRIORITY_QUEUE_H__
#define __ADT_BV_PRIORITY_QUEUE_H__

#include <stddef.h>

// DATA STRUCTURES

typedef struct bv_priority_queue_s
{

   void       *compar;
   void       *data;
   size_t      size;
   size_t      capacity;
   size_t      max_size;

} bv_priority_queue_t;

#ifdef __SCCZ80
extern size_t __LIB__ bv_priority_queue_capacity(bv_priority_queue_t *q) __SMALLC __z88dk_fastcall;
#else
extern size_t bv_priority_queue_capacity(bv_priority_queue_t *q)  __preserves_regs(b,c,d,e);
extern size_t bv_priority_queue_capacity_fastcall(bv_priority_queue_t *q) __preserves_regs(b,c,d,e) __z88dk_fastcall;
#define bv_priority_queue_capacity(a) bv_priority_queue_capacity_fastcall(a)
#endif


#ifdef __SCCZ80
extern void __LIB__ bv_priority_queue_clear(bv_priority_queue_t *q) __SMALLC __z88dk_fastcall;
#else
extern void bv_priority_queue_clear(bv_priority_queue_t *q)  __preserves_regs(b,c,d,e);
extern void bv_priority_queue_clear_fastcall(bv_priority_queue_t *q) __preserves_regs(a,b,c,d,e) __z88dk_fastcall;
#define bv_priority_queue_clear(a) bv_priority_queue_clear_fastcall(a)
#endif


#ifdef __SCCZ80
extern void __LIB__ *bv_priority_queue_data(bv_priority_queue_t *q) __SMALLC __z88dk_fastcall;
#else
extern void *bv_priority_queue_data(bv_priority_queue_t *q)  __preserves_regs(b,c,d,e);
extern void *bv_priority_queue_data_fastcall(bv_priority_queue_t *q) __preserves_regs(b,c,d,e) __z88dk_fastcall;
#define bv_priority_queue_data(a) bv_priority_queue_data_fastcall(a)
#endif


#ifdef __SCCZ80
extern void __LIB__ bv_priority_queue_destroy(bv_priority_queue_t *q) __SMALLC __z88dk_fastcall;
#else
extern void bv_priority_queue_destroy(bv_priority_queue_t *q)  __preserves_regs(b,c);
extern void bv_priority_queue_destroy_fastcall(bv_priority_queue_t *q) __preserves_regs(b,c) __z88dk_fastcall;
#define bv_priority_queue_destroy(a) bv_priority_queue_destroy_fastcall(a)
#endif


#ifdef __SCCZ80
extern int __LIB__ bv_priority_queue_empty(bv_priority_queue_t *q) __SMALLC __z88dk_fastcall;
#else
extern int bv_priority_queue_empty(bv_priority_queue_t *q)  __preserves_regs(b,c,d,e);
extern int bv_priority_queue_empty_fastcall(bv_priority_queue_t *q) __preserves_regs(b,c,d,e) __z88dk_fastcall;
#define bv_priority_queue_empty(a) bv_priority_queue_empty_fastcall(a)
#endif


extern bv_priority_queue_t __LIB__ *bv_priority_queue_init(void *p,size_t capacity,size_t max_size,void *compar) __SMALLC;
extern bv_priority_queue_t __LIB__ *bv_priority_queue_init_callee(void *p,size_t capacity,size_t max_size,void *compar) __SMALLC __z88dk_callee;
#define bv_priority_queue_init(a,b,c,d) bv_priority_queue_init_callee(a,b,c,d)


#ifdef __SCCZ80
extern size_t __LIB__ bv_priority_queue_max_size(bv_priority_queue_t *q) __SMALLC __z88dk_fastcall;
#else
extern size_t bv_priority_queue_max_size(bv_priority_queue_t *q)  __preserves_regs(b,c,d,e);
extern size_t bv_priority_queue_max_size_fastcall(bv_priority_queue_t *q) __preserves_regs(b,c,d,e) __z88dk_fastcall;
#define bv_priority_queue_max_size(a) bv_priority_queue_max_size_fastcall(a)
#endif


#ifdef __SCCZ80
extern int __LIB__ bv_priority_queue_pop(bv_priority_queue_t *q) __SMALLC __z88dk_fastcall;
#else
extern int bv_priority_queue_pop(bv_priority_queue_t *q);
extern int bv_priority_queue_pop_fastcall(bv_priority_queue_t *q) __z88dk_fastcall;
#define bv_priority_queue_pop(a) bv_priority_queue_pop_fastcall(a)
#endif


extern int __LIB__ bv_priority_queue_push(bv_priority_queue_t *q,int c) __SMALLC;
extern int __LIB__ bv_priority_queue_push_callee(bv_priority_queue_t *q,int c) __SMALLC __z88dk_callee;
#define bv_priority_queue_push(a,b) bv_priority_queue_push_callee(a,b)


extern int __LIB__ bv_priority_queue_reserve(bv_priority_queue_t *q,size_t n) __SMALLC;
extern int __LIB__ bv_priority_queue_reserve_callee(bv_priority_queue_t *q,size_t n) __SMALLC __z88dk_callee;
#define bv_priority_queue_reserve(a,b) bv_priority_queue_reserve_callee(a,b)


extern int __LIB__ bv_priority_queue_resize(bv_priority_queue_t *q,size_t n) __SMALLC;
extern int __LIB__ bv_priority_queue_resize_callee(bv_priority_queue_t *q,size_t n) __SMALLC __z88dk_callee;
#define bv_priority_queue_resize(a,b) bv_priority_queue_resize_callee(a,b)


#ifdef __SCCZ80
extern int __LIB__ bv_priority_queue_shrink_to_fit(bv_priority_queue_t *q) __SMALLC __z88dk_fastcall;
#else
extern int bv_priority_queue_shrink_to_fit(bv_priority_queue_t *q);
extern int bv_priority_queue_shrink_to_fit_fastcall(bv_priority_queue_t *q) __z88dk_fastcall;
#define bv_priority_queue_shrink_to_fit(a) bv_priority_queue_shrink_to_fit_fastcall(a)
#endif


#ifdef __SCCZ80
extern size_t __LIB__ bv_priority_queue_size(bv_priority_queue_t *q) __SMALLC __z88dk_fastcall;
#else
extern size_t bv_priority_queue_size(bv_priority_queue_t *q)  __preserves_regs(b,c,d,e);
extern size_t bv_priority_queue_size_fastcall(bv_priority_queue_t *q) __preserves_regs(b,c,d,e) __z88dk_fastcall;
#define bv_priority_queue_size(a) bv_priority_queue_size_fastcall(a)
#endif


#ifdef __SCCZ80
extern int __LIB__ bv_priority_queue_top(bv_priority_queue_t *q) __SMALLC __z88dk_fastcall;
#else
extern int bv_priority_queue_top(bv_priority_queue_t *q);
extern int bv_priority_queue_top_fastcall(bv_priority_queue_t *q) __z88dk_fastcall;
#define bv_priority_queue_top(a) bv_priority_queue_top_fastcall(a)
#endif



#endif
