c/rl_sdcc/b_vector_append
c/rl_sdcc/b_vector_append_block
c/rl_sdcc/b_vector_append_n
c/rl_sdcc/b_vector_at
c/rl_sdcc/b_vector_back
c/rl_sdcc/b_vector_destroy
c/rl_sdcc/b_vector_empty
c/rl_sdcc/b_vector_erase
c/rl_sdcc/b_vector_erase_block
c/rl_sdcc/b_vector_erase_range
c/rl_sdcc/b_vector_front
c/rl_sdcc/b_vector_init
c/rl_sdcc/b_vector_insert
c/rl_sdcc/b_vector_insert_block
c/rl_sdcc/b_vector_insert_n
c/rl_sdcc/b_vector_max_size
c/rl_sdcc/b_vector_pop_back
c/rl_sdcc/b_vector_push_back
c/rl_sdcc/b_vector_read_block
c/rl_sdcc/b_vector_reserve
c/rl_sdcc/b_vector_resize
c/rl_sdcc/b_vector_shrink_to_fit
c/rl_sdcc/b_vector_write_block
z80/__vector_at
z80/__vector_back
z80/__vector_make_room
z80/__vector_reserve
z80/__vector_resize
