#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.14 2006-12-19 10:06:57 aralbrec Exp $

include ../Make.config

default:
	$(LIBLINKER) -x../malloc @malllist

clean:
	$(RM) *.o* *.sym *.map *~ *.err zcc_opt.def *.i 

