/* generated by make_init.pl mod1.h mod2.h mod3.h */

#include <stdlib.h>
#include <stdio.h>
#include <glib.h>

#include "mod1.h"
#include "mod2.h"
#include "mod3.h"

struct Module1 * new_Module1(void)
{
	struct Module1 * self;
	
	self = g_slice_new0(struct Module1);
	struct_Module1_init(self);
	return self;
}


void delete_Module1(struct Module1 **pself)
{
	struct_Module1_fini(*pself);
	g_slice_free(struct Module1, *pself);
	*pself = NULL;
}


struct Module2 * new_Module2(void)
{
	struct Module2 * self;
	
	self = g_slice_new0(struct Module2);
	
	return self;
}


void delete_Module2(struct Module2 **pself)
{
	
	g_slice_free(struct Module2, *pself);
	*pself = NULL;
}


struct Module3 * new_Module3(void)
{
	struct Module3 * self;
	
	self = g_slice_new0(struct Module3);
	
	return self;
}


void delete_Module3(struct Module3 **pself)
{
	
	g_slice_free(struct Module3, *pself);
	*pself = NULL;
}



/* register atexit(), die on error */
static void xatexit(void (*fini)(void))
{
	if (atexit(fini) ) {
		fprintf(stderr, "atexit() failed\\n");
		exit(1);
	}
}

/* initialize all modules */
static void init()
{
	init_1();
    xatexit(fini_1);
    init_2();
    xatexit(fini_3);
}

/* new main function to init and call user main */
extern int user_main(int argc, char *argv[]);
int main(int argc, char *argv[])
{
    init();
    return user_main(argc, argv);
}

