#
# $Id: Makefile,v 1.2 2002-05-20 13:10:47 stefano Exp $

all:
	@echo ''
	@echo '---> Building +3 RS232 library <---'
	@echo ''
	cd plus3 ; make
	@echo ''
	@echo '---> Building Interface 1 RS232 library <---'
	@echo ''
	cd if1 ; make


clean:
	cd plus3 ; make clean
	cd if1 ; make clean
