
;; clib bss segments ;;;;;;;;;;

section bss_arch
section bss_alloc_balloc
section bss_alloc_malloc
section bss_compress_aplib
section bss_error
section bss_env
section bss_esxdos
section bss_fcntl
section bss_fp_am9511
section bss_fp_math48
section bss_fp_math32
section bss_fp_math16
section bss_fp_mbf32
section bss_input
section bss_PSGlib
section bss_SMSlib
section bss_sound_bit
section bss_sound_ay
section bss_stdio
section bss_stdlib
section bss_string

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
