#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.2 2001-04-18 14:59:40 stefano Exp $


all: 
	zcc -vn -make-lib strdup_far.c


clean:
	rm -f *.o* *.sym *.map *~ *.err zcc_opt.def
