//-----------------------------------------------------------------------------
// z80asm
// parser
// Copyright (C) Paulo Custodio, 2011-2022
// License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
//-----------------------------------------------------------------------------

#pragma once

#include "expr.h"
#include "scan.h"
#include "symtab.h"
#include "utils.h"
#include <deque>
using namespace std;

class Asm;
class Expr;

class Parser {
public:
	void clear();
	void parse();		// parse lines from g_preproc

private:
	enum class State { Main };

	ScannedLine m_line;						// line being parsed
	State	m_state{ State::Main };			// parser state
    deque<shared_ptr<Expr>> m_exprs;		// parsed expressions
    deque<int> m_const_exprs;               // evaluated constant expressions
    unsigned m_start_stmt{ 0 };             // position of start of line

    int start_stmt_index() const { return m_start_stmt - m_line.pos(); }

	void parse_line();
	void parse_line_main();
	string check_label();
	void parse_symbol_declare(Symbol::Scope scope);
    void parse_int8_data();
    void parse_int16_data();
    void parse_int16be_data();
    void parse_int24_data();
    void parse_int32_data();
    void do_defs_n();
    void do_defs_n_n();
    void do_defs_n_str(const string& filler);

	bool expr_in_parens();

    void add_label(const string& name);
	void add_opcode(unsigned bytes);
	void add_opcode_n(unsigned bytes);
	void add_opcode_s(unsigned bytes);
	void add_opcode_h(unsigned bytes);
	void add_opcode_n_0(unsigned bytes);
	void add_opcode_s_0(unsigned bytes);
    void add_opcode_nn(unsigned bytes, int target_offset = 0);
    void add_opcode_nnn(unsigned bytes, int target_offset = 0);
    void add_opcode_nnnn(unsigned bytes, int target_offset = 0);
	void add_opcode_NN(unsigned bytes);
	void add_opcode_idx(unsigned bytes);
	void add_opcode_idx_idx1(unsigned bytes0, unsigned bytes1);
	void add_opcode_idx_n(unsigned bytes);
	void add_opcode_n_n(unsigned bytes);
    void add_opcode_defb();

	void add_emul_call_flag(unsigned bytes_jump, unsigned bytes_call);
	void add_call_function(const string& function_name);
	void add_jump_relative(unsigned bytes);
	void add_jump_relative16(unsigned bytes);
	void add_z80n_mmu_n();
	void add_z80n_mmu_a();
	void add_restart();

    void error_syntax();
    void error_illegal_ident();
    void error_int_range(int n);
    void warn_if_expr_in_parens();
    void error_expr_not_in_parens();

	// generated by make_parser_code.pl
	void parse_main();
	void parse_main_action(int action);
#include "parse_main_action.h"
};
