

TARGETS = abc80 ace aquarius bee cpc gal mc1000 msx mtx mz nascom osca p2000 pc6001 \
	pps sam sc3000 svi ti82 ti83 ti85 ti86 ti8x ts2068 vz x1 z1013 z88 zx z9001


APPNAME = ansitest.bin
CFLAGS = -clib=ansi
LDFLAGS = -lndos

COMMON_SRCS := ansitest.c


include ../../support/multitarget_build/Makefile

