

TARGETS = abc80 ace alphatro aquarius bee cpc coleco fp1100 hemc hgmc kramermc laser500 mc1000  \
	nascom pmd85 pv1000 pps rx78 spc1000 srr super80 trs80 vg5k vz z1013 zx80 zx81 msx pv2000 \
	sc3000 svi m5 mtx multi8 z80tvgame z9001 homelab vector06c

APPNAME = world_conio.bin
CFLAGS = --generic-console

COMMON_SRCS := world_conio.c


include ../../support/multitarget_build/Makefile

