#
# $Id: Makefile,v 1.1 2012-03-08 07:16:46 stefano Exp $

all:
	@echo ''
	@echo '---> Building basic FLOS file library <---'
	@echo ''
	cd flos ; $(MAKE) ; cd ..

clean:
	cd flos ; $(MAKE) clean ; cd ..
