# $Id: Makefile,v 1.5 2008-06-03 12:07:50 stefano Exp $

lcpc:	
	cd cpc ; $(MAKE) ; cd ..

lzx:	
	cd spectrum ; $(MAKE) ; cd ..

lz88:
	cd z88 ; $(MAKE) ; cd ..

clean:
	cd cpc ; $(MAKE) clean ; cd ..
	cd z88 ; $(MAKE) clean ; cd ..
	cd spectrum ; $(MAKE) clean ; cd ..
