#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.2 2001-04-18 12:43:04 stefano Exp $

all:
	@echo "Nowt here, who's gonna write sommat?"


clean:
	rm -f *.o* *.sym *.map zcc_opt.def
