; size_t ba_priority_queue_capacity(ba_priority_queue_t *q)

SECTION code_clib
SECTION code_string

MODULE _ba_priority_queue_capacity_sdcc
GLOBAL _ba_priority_queue_capacity
GLOBAL ba_priority_queue_capacity

defc _ba_priority_queue_capacity = ba_priority_queue_capacity

