; int ba_priority_queue_resize(ba_priority_queue_t *q, size_t n)

SECTION code_clib
SECTION code_string

MODULE _ba_priority_queue_resize_callee_sdcc
GLOBAL _ba_priority_queue_resize_callee
GLOBAL ba_priority_queue_resize_callee

defc _ba_priority_queue_resize_callee = ba_priority_queue_resize_callee

