; size_t bv_priority_queue_capacity(bv_priority_queue_t *q)

SECTION code_clib
SECTION code_string

MODULE _bv_priority_queue_capacity_sdcc
GLOBAL _bv_priority_queue_capacity
GLOBAL bv_priority_queue_capacity

defc _bv_priority_queue_capacity = bv_priority_queue_capacity

