; int bv_priority_queue_resize(bv_priority_queue_t *q, size_t n)

SECTION code_clib
SECTION code_string

MODULE _bv_priority_queue_resize_callee_sdcc
GLOBAL _bv_priority_queue_resize_callee
GLOBAL bv_priority_queue_resize_callee

defc _bv_priority_queue_resize_callee = bv_priority_queue_resize_callee

