; size_t bv_priority_queue_max_size(bv_priority_queue_t *q)

SECTION code_clib
SECTION code_string

MODULE _bv_priority_queue_max_size_sdcc
GLOBAL _bv_priority_queue_max_size
GLOBAL bv_priority_queue_max_size

defc _bv_priority_queue_max_size = bv_priority_queue_max_size

