; int bv_priority_queue_shrink_to_fit(bv_priority_queue_t *q)

SECTION code_clib
SECTION code_string

MODULE _bv_priority_queue_shrink_to_fit_sdcc
GLOBAL _bv_priority_queue_shrink_to_fit
GLOBAL bv_priority_queue_shrink_to_fit

defc _bv_priority_queue_shrink_to_fit = bv_priority_queue_shrink_to_fit

