; void *p_forward_list_alt_remove_after(p_forward_list_alt_t *list, void *list_item)

SECTION code_clib
SECTION code_string

MODULE _p_forward_list_alt_remove_after_sdcc
GLOBAL _p_forward_list_alt_remove_after
GLOBAL p_forward_list_alt_remove_after

defc _p_forward_list_alt_remove_after = p_forward_list_alt_remove_after

