; void *p_forward_list_alt_insert_after(p_forward_list_alt_t *list, void *list_item, void *item)

SECTION code_clib
SECTION code_string

MODULE _p_forward_list_alt_insert_after_callee_sdcc
GLOBAL _p_forward_list_alt_insert_after_callee
GLOBAL p_forward_list_alt_insert_after_callee

defc _p_forward_list_alt_insert_after_callee = p_forward_list_alt_insert_after_callee

