; void p_forward_list_alt_push_front(p_forward_list_alt_t *list, void *item)

SECTION code_clib
SECTION code_string

MODULE _p_forward_list_alt_push_front_callee_sdcc
GLOBAL _p_forward_list_alt_push_front_callee
GLOBAL p_forward_list_alt_push_front_callee

defc _p_forward_list_alt_push_front_callee = p_forward_list_alt_push_front_callee

