; void *p_forward_list_alt_pop_front(p_forward_list_alt_t *list)

SECTION code_clib
SECTION code_string

MODULE _p_forward_list_alt_pop_front_sdcc
GLOBAL _p_forward_list_alt_pop_front
GLOBAL p_forward_list_alt_pop_front

defc _p_forward_list_alt_pop_front = p_forward_list_alt_pop_front

