; size_t wa_priority_queue_capacity(wa_priority_queue_t *q)

SECTION code_clib
SECTION code_string

MODULE _wa_priority_queue_capacity_sdcc
GLOBAL _wa_priority_queue_capacity
GLOBAL wa_priority_queue_capacity

defc _wa_priority_queue_capacity = wa_priority_queue_capacity

