; int wa_priority_queue_resize(wa_priority_queue_t *q, size_t n)

SECTION code_clib
SECTION code_string

MODULE _wa_priority_queue_resize_callee_sdcc
GLOBAL _wa_priority_queue_resize_callee
GLOBAL wa_priority_queue_resize_callee

defc _wa_priority_queue_resize_callee = wa_priority_queue_resize_callee

