; size_t wv_priority_queue_max_size(wv_priority_queue_t *q)

SECTION code_clib
SECTION code_string

MODULE _wv_priority_queue_max_size_sdcc
GLOBAL _wv_priority_queue_max_size
GLOBAL wv_priority_queue_max_size

defc _wv_priority_queue_max_size = wv_priority_queue_max_size

