; size_t wv_priority_queue_capacity(wv_priority_queue_t *q)

SECTION code_clib
SECTION code_string

MODULE _wv_priority_queue_capacity_sdcc
GLOBAL _wv_priority_queue_capacity
GLOBAL wv_priority_queue_capacity

defc _wv_priority_queue_capacity = wv_priority_queue_capacity

