; int wv_priority_queue_resize(wv_priority_queue_t *q, size_t n)

SECTION code_clib
SECTION code_string

MODULE _wv_priority_queue_resize_callee_sdcc
GLOBAL _wv_priority_queue_resize_callee
GLOBAL wv_priority_queue_resize_callee

defc _wv_priority_queue_resize_callee = wv_priority_queue_resize_callee

