; int wv_priority_queue_shrink_to_fit(wv_priority_queue_t *q)

SECTION code_clib
SECTION code_string

MODULE _wv_priority_queue_shrink_to_fit_sdcc
GLOBAL _wv_priority_queue_shrink_to_fit
GLOBAL wv_priority_queue_shrink_to_fit

defc _wv_priority_queue_shrink_to_fit = wv_priority_queue_shrink_to_fit

