; int wv_priority_queue_reserve(wv_priority_queue_t *q, size_t n)

SECTION code_clib
SECTION code_string

MODULE _wv_priority_queue_reserve_callee_sdcc
GLOBAL _wv_priority_queue_reserve_callee
GLOBAL wv_priority_queue_reserve_callee

defc _wv_priority_queue_reserve_callee = wv_priority_queue_reserve_callee

