
// automatically generated by m4 from headers in proto subdir


#ifndef _INTRINSIC_H
#define _INTRINSIC_H

extern void __LIB__ intrinsic_di(void);


extern void __LIB__ intrinsic_ei(void);


extern void __LIB__ intrinsic_halt(void);



#endif
