
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; ADT.LIB CODE SECTIONS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

SECTION seg_code_b_array
SECTION seg_code_b_vector
SECTION seg_code_ba_priority_queue
SECTION seg_code_ba_stack
SECTION seg_code_bv_priority_queue
SECTION seg_code_bv_stack
SECTION seg_code_p_forward_list
SECTION seg_code_p_forward_list_alt
SECTION seg_code_p_list
SECTION seg_code_p_queue
SECTION seg_code_p_stack
SECTION seg_code_w_array
SECTION seg_code_w_vector
SECTION seg_code_wa_priority_queue
SECTION seg_code_wa_stack
SECTION seg_code_wv_priority_queue
SECTION seg_code_wv_stack
