
// automatically generated by m4 from headers in proto subdir


#ifndef _SMS_PSGLIB_H
#define _SMS_PSGLIB_H

/* **************************************************
   PSGlib - C programming library for the SEGA PSG
   ( part of devkitSMS - github.com/sverx/devkitSMS )
   Synchronized March 29, 2017
   ************************************************** */

#define PSG_STOPPED         0
#define PSG_PLAYING         1

#define SFX_CHANNEL2        0x01
#define SFX_CHANNEL3        0x02
#define SFX_CHANNELS2AND3   SFX_CHANNEL2|SFX_CHANNEL3

extern void PSGPlay(void *song);
extern void PSGPlay_fastcall(void *song) __z88dk_fastcall;
#define PSGPlay(a) PSGPlay_fastcall(a)


extern void PSGCancelLoop(void);

extern void PSGPlayNoRepeat(void *song);
extern void PSGPlayNoRepeat_fastcall(void *song) __z88dk_fastcall;
#define PSGPlayNoRepeat(a) PSGPlayNoRepeat_fastcall(a)


extern void PSGStop(void);

extern unsigned char PSGGetStatus(void);

extern void PSGSetMusicVolumeAttenuation(unsigned char attenuation);
extern void PSGSetMusicVolumeAttenuation_fastcall(unsigned char attenuation) __z88dk_fastcall;
#define PSGSetMusicVolumeAttenuation(a) PSGSetMusicVolumeAttenuation_fastcall(a)



extern void PSGSFXPlay(void *sfx,unsigned char channels);
extern void PSGSFXPlay_callee(void *sfx,unsigned char channels) __z88dk_callee;
#define PSGSFXPlay(a,b) PSGSFXPlay_callee(a,b)


extern void PSGSFXPlayLoop(void *sfx,unsigned char channels);
extern void PSGSFXPlayLoop_callee(void *sfx,unsigned char channels) __z88dk_callee;
#define PSGSFXPlayLoop(a,b) PSGSFXPlayLoop_callee(a,b)


extern void PSGSFXCancelLoop(void);

extern void PSGSFXStop(void);

extern unsigned char PSGSFXGetStatus(void);


extern void PSGSilenceChannels(void);

extern void PSGRestoreVolumes(void);


extern void PSGFrame(void);

extern void PSGSFXFrame(void);


#endif
