
;; clib code segments ;;;;;;;;;

section code_adt_b_array
section code_adt_b_vector
section code_adt_ba_priority_queue
section code_adt_ba_stack
section code_adt_bv_priority_queue
section code_adt_bv_stack
section code_adt_p_forward_list
section code_adt_p_forward_list_alt
section code_adt_p_list
section code_adt_p_queue
section code_adt_p_stack
section code_adt_w_array
section code_adt_w_vector
section code_adt_wa_priority_queue
section code_adt_wa_stack
section code_adt_wv_priority_queue
section code_adt_wv_stack
section code_alloc_balloc
section code_alloc_malloc
section code_alloc_obstack
section code_arch
section code_compress_zx7
section code_ctype
section code_error
section code_fcntl
section code_font_fzx
section code_input
section code_l
section code_l_sccz80
section code_l_sdcc
section code_locale
section code_math
section code_sound_bit
section code_stdio
section code_stdlib
section code_string
section code_temp_sp1
section code_threads_mutex
section code_z80

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
