#!/usr/bin/env perl

#------------------------------------------------------------------------------
# Z80 assembler
# Copyright (C) Paulo Custodio, 2011-2026
# License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
#------------------------------------------------------------------------------

use Data::Dump 'dump';
use FindBin;
use lib "$FindBin::Bin";    # adjust to find modules
use List::MoreUtils 'indexes';
use Modern::Perl;
use Trie;
use warnings FATAL => 'uninitialized';

@ARGV == 3
    or die "usage: $0 opcodes.dat opcodes_trie_token.h output_basename\n";
my ( $opcodes_dat, $opcodes_trie_token_h, $output_basename ) = @ARGV;

my $trie = Trie->new;
$trie->read_token_id($opcodes_trie_token_h);

open( my $in, "<", $opcodes_dat ) or die "open $opcodes_dat: $!";
chomp( my $title = <$in> );
$title eq "asm|cpu|synth|const|ops"
    or die
"invalid $opcodes_dat: expected title 'asm|cpu|synth|const|ops', got '$title'\n";

while (<$in>) {
    chomp;
    my ( $asm, $cpu, $synth, $const, $ops ) = split( /\|/, $_, 5 );
    next if $synth =~ /x/i;        # skip synthetic instructions
    $cpu =~ s/^80/i80/
        ;    # CPU name cannot start with a digit, so 8080 is renamed to i8080
    $trie->add( $asm, $cpu, "$const|$ops|$cpu" );
}

$trie->make_table;
build_actions($trie);

open( my $out_h, ">", "../$output_basename.h" )
    or die "write ../$output_basename.h: $!\n";
say $out_h "// generated by $0";
say $out_h "#pragma once";
say $out_h "#include \"opcodes.h\"";
say $out_h "#include \"parser.h\"";
say $out_h "";
say $out_h $trie->output_h($output_basename);
say $out_h output_h($output_basename);

open( my $out_cpp, ">", "../$output_basename.cpp" )
    or die "write ../$output_basename.cpp: $!\n";
say $out_cpp "// generated by $0";
say $out_cpp "#include \"$output_basename.h\"";
say $out_cpp "#include \"opcodes.h\"";
say $out_cpp "#include \"opcodes_trie_token.h\"";
say $out_cpp "#include \"parser.h\"";
say $out_cpp "#include <cstdint>";
say $out_cpp "";
say $out_cpp $trie->output_cpp($output_basename);
say $out_cpp output_cpp($output_basename);

#dump $trie;

sub build_actions {
    my ($trie) = @_;
    for my $value ( @{ $trie->values } ) {
        my $id  = $value->{id};
        my $asm = $value->{_asm};
        my $cpu = $value->{_cpu};
        my ( $const, $ops, $cpu_ ) = split( /\|/, $value->{value}, 3 );
        $cpu eq $cpu_
            or die
"CPU mismatch in value for asm '$asm': expected '$cpu', got '$cpu_'\n"
            . dump($value);

        # get ops with expressions
        my @ops = map { s/^([0-9a-fA-F]+)$/hex($1)/er } split( /\s+|;/, $ops );

        # map parsed expressions
        my @asm_tokens = Trie->lex( $asm, undef );
        my @asm_exprs;
        for (@asm_tokens) {
            my ( $token, $token_value ) = @$_;
            if (   $token eq "TrieToken::Expr"
                || $token eq "TrieToken::DispExpr" )
            {
                if ( $token_value eq '%c' ) {
                    $const ne ""
                        or die
                        "missing const value for token '$token' in asm '$asm'\n"
                        . dump($value);
                    my @values = split( /,/, $const );

                    # %c is expected in an expression in @ops, and only once
                    my @indexes = indexes { /%c/ } @ops;
                    @indexes <= 1
                        or die
"unexpected number of '%c' tokens in ops for asm '$asm'\n"
                        . dump($value);
                    if ( @indexes == 0 ) {
                        my %expr = (
                            type    => 'const',
                            values  => \@values,
                            formula => "",
                            offset  => 0,
                            size    => 0
                        );
                        push @asm_exprs, \%expr;
                    }
                    else {
                        my $op     = $ops[ $indexes[0] ];
                        my @params = parse_percent_c_expr($op);
                        my %expr   = (
                            type   => 'const',
                            values => \@values,
                            offset => $indexes[0],
                            size   => 1,
                            @params
                        );
                        push @asm_exprs, \%expr;
                        $ops[ $indexes[0] ] = 0;    # write placeholder
                    }

                    # no further %c are expected
                    @indexes = indexes { /%c/ } @ops;
                    @indexes == 0
                        or die
"unexpected number of '%c' tokens in ops for asm '$asm'\n"
                        . dump($value);
                }
                elsif ( $token_value eq '%n' ) {

                    # multiple %n may appear in @ops, one per expression in asm
                    my @indexes = indexes { $_ eq '%n' } @ops;
                    @indexes >= 1
                        or die
"unexpected number of '%n' tokens in ops for asm '$asm'\n"
                        . dump($value);
                    my %expr = (
                        type       => 'patch',
                        offset     => $indexes[0],
                        size       => 1,
                        patch_type => 'PatchType::Unsigned',
                    );
                    push @asm_exprs, \%expr;
                    $ops[ $indexes[0] ] = 0;    # write placeholder
                }
                elsif ( $token_value eq '%m' || $token_value eq '%x' ) {

# only one %m/%x in asm, N x %m/%x in @ops, where N is the size of the expression
                    my @indexes = indexes { $_ eq $token_value } @ops;
                    @indexes >= 1
                        or die
"unexpected number of '$token_value' tokens in ops for asm '$asm'\n"
                        . dump($value);
                    my %expr = (
                        type       => 'patch',
                        offset     => $indexes[0],
                        size       => scalar(@indexes),
                        patch_type => 'PatchType::Unsigned',
                    );
                    push @asm_exprs, \%expr;
                    for (@indexes) {
                        $ops[$_] = 0;    # write placeholder
                    }
                }
                elsif ( $token_value eq '%M' ) {

     # only one %M in asm, N x %M in @ops, where N is the size of the expression
                    my @indexes = indexes { $_ eq $token_value } @ops;
                    @indexes >= 1
                        or die
"unexpected number of '$token_value' tokens in ops for asm '$asm'\n"
                        . dump($value);
                    my %expr = (
                        type       => 'patch',
                        offset     => $indexes[0],
                        size       => scalar(@indexes),
                        patch_type => 'PatchType::BigEndian',
                    );
                    push @asm_exprs, \%expr;
                    for (@indexes) {
                        $ops[$_] = 0;    # write placeholder
                    }
                }
                elsif ( $token_value eq '%d' ) {

                    # only one %d in asm and one %d in @ops
                    my @indexes = indexes { $_ eq '%d' } @ops;
                    @indexes == 1
                        or die
"unexpected number of '%d' tokens in ops for asm '$asm'\n"
                        . dump($value);
                    my %expr = (
                        type       => 'patch',
                        offset     => $indexes[0],
                        size       => 1,
                        patch_type => 'PatchType::Signed',
                    );
                    push @asm_exprs, \%expr;
                    $ops[ $indexes[0] ] = 0;    # write placeholder
                }
                elsif ( $token_value eq '%h' ) {

                    # only one %h in asm and one %h in @ops
                    my @indexes = indexes { $_ eq $token_value } @ops;
                    @indexes == 1
                        or die
"unexpected number of '$token_value' tokens in ops for asm '$asm'\n"
                        . dump($value);
                    my %expr = (
                        type       => 'patch',
                        offset     => $indexes[0],
                        size       => 1,
                        patch_type => 'PatchType::HighByte',
                    );
                    push @asm_exprs, \%expr;
                    $ops[ $indexes[0] ] = 0;    # write placeholder
                }
                elsif ( $token_value eq '%j' ) {

                    my @indexes = indexes { $_ eq $token_value } @ops;
                    @indexes == 1
                        or die
"unexpected number of '$token_value' tokens in ops for asm '$asm'\n"
                        . dump($value);
                    my ( $alt_offset, $alt_size, @alt_ops ) =
                        get_jp_ops( $asm, $cpu );    # JR to JP conversion
                    my %expr = (
                        type       => 'patch',
                        offset     => $indexes[0],
                        size       => scalar(@indexes),
                        patch_type => 'PatchType::PCrelative',
                        alt_offset => $alt_offset,
                        alt_size   => $alt_size,
                        alt_ops    => \@alt_ops,
                    );
                    push @asm_exprs, \%expr;
                    for (@indexes) {
                        $ops[$_] = 0;    # write placeholder
                    }
                }
                elsif ( $token_value eq '%J' ) {

                    my @indexes = indexes { $_ eq $token_value } @ops;
                    @indexes == 2
                        or die
"unexpected number of '$token_value' tokens in ops for asm '$asm'\n"
                        . dump($value);
                    my %expr = (
                        type       => 'patch',
                        offset     => $indexes[0],
                        size       => scalar(@indexes),
                        patch_type => 'PatchType::PCrelative',
                    );
                    push @asm_exprs, \%expr;
                    for (@indexes) {
                        $ops[$_] = 0;    # write placeholder
                    }
                }
                else {
                    die dump($value);
                }
            }
        }

  # all expressions should have been mapped, only numbers should remoain in @ops
        my @indexes = indexes { !/^\d+$/ } @ops;
        @indexes == 0
            or die "unexpected tokens in ops for asm '$asm': "
            . join( ", ", @ops ) . "\n"
            . dump($value);

        $value->{asm_tokens} = \@asm_tokens;
        $value->{asm_exprs}  = \@asm_exprs;
        $value->{ops}        = \@ops;

        # build bytecode for this action
        my $start_bytecode_index = scalar( @{ $trie->bytecode } );

        # literal bytes
        push @{ $trie->bytecode },
            { op => "static_cast<uint8_t>(OpcodesOp::Bytes)" };
        push @{ $trie->bytecode }, { op => scalar(@ops) . " /* bytes size */" };
        for my $op (@ops) {
            push @{ $trie->bytecode }, { op => fhex($op) };
        }

        # expressions
        for my $id ( 0 .. $#{ $value->{asm_exprs} } ) {
            my $expr = $value->{asm_exprs}[$id];

            if ( $expr->{type} eq "const" ) {
                push @{ $trie->bytecode },
                    { op => "static_cast<uint8_t>(OpcodesOp::ExprConst) "
                        . "/* start expression $id */" };
                push @{ $trie->bytecode },
                    { op => "$expr->{offset} /* offset */" };
                push @{ $trie->bytecode }, { op => "$expr->{size} /* size */" };

                my $validation = validation_const( @{ $expr->{values} } );
                push @{ $trie->bytecode },
                    { op => "static_cast<uint8_t>($validation)" };

                my $formula = patch_formula( $expr->{formula} );
                push @{ $trie->bytecode },
                    { op => "static_cast<uint8_t>($formula)" };
                if ( $formula =~ /None/ ) {

                }
                elsif ( $formula =~ /ScaleBelowThreshold/ ) {
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{A} ) . " /* A */" };
                }
                elsif ( $formula =~ /AddScaled/ ) {
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{A} ) . " /* A */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{B} ) . " /* B */" };
                }
                elsif ( $formula =~ /SelectOrAdd/ ) {
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{A} ) . " /* A */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{B} ) . " /* B */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{C} ) . " /* C */" };
                }
                elsif ( $formula =~ /Select2/ ) {
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{A} ) . " /* A */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{B} ) . " /* B */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{C} ) . " /* C */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{D} ) . " /* E */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{E} ) . " /* E */" };
                }
                elsif ( $formula =~ /Select3/ ) {
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{A} ) . " /* A */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{B} ) . " /* B */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{C} ) . " /* C */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{D} ) . " /* E */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{E} ) . " /* E */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{F} ) . " /* F */" };
                    push @{ $trie->bytecode },
                        { op => fhex( $expr->{G} ) . " /* G */" };
                }
            }
            elsif ( $expr->{type} eq "patch" ) {
                push @{ $trie->bytecode },
                    { op => "static_cast<uint8_t>(OpcodesOp::ExprPatch) "
                        . "/* start expression $id */" };
                push @{ $trie->bytecode },
                    { op => "$expr->{offset} /* offset */" };
                push @{ $trie->bytecode }, { op => "$expr->{size} /* size */" };
                push @{ $trie->bytecode },
                    { op => "static_cast<uint8_t>($expr->{patch_type})" };

               # if this a JR instruction, output the alternative JP instruction
                if (   $expr->{patch_type} eq 'PatchType::PCrelative'
                    && $expr->{size} == 1 )
                {
                    my @alt_ops = @{ $expr->{alt_ops} };
                    push @{ $trie->bytecode },
                        { op =>
                            "static_cast<uint8_t>(OpcodesOp::AltJpOpcode)" };
                    push @{ $trie->bytecode },
                        { op => scalar(@alt_ops) . " /* alt-bytes size */" };
                    for my $op (@alt_ops) {
                        push @{ $trie->bytecode }, { op => fhex($op) };
                    }
                    push @{ $trie->bytecode },
                        { op => "$expr->{alt_offset} /* alt-offset */" };
                    push @{ $trie->bytecode },
                        { op => "$expr->{alt_size} /* alt-size */" };
                }
            }
            else {
                die "invalid expression type $expr->{type}\n" . dump($value);
            }
        }

        my $end_bytecode_index = scalar( @{ $trie->bytecode } );

        $value->{bytecode_index}  = $start_bytecode_index;
        $value->{bytecode_length} = $end_bytecode_index - $start_bytecode_index;
        $trie->bytecode->[$start_bytecode_index]{id}    = $start_bytecode_index;
        $trie->bytecode->[$start_bytecode_index]{asm}   = $asm;
        $trie->bytecode->[$start_bytecode_index]{cpu}   = $cpu;
        $trie->bytecode->[$start_bytecode_index]{value} = $value->{value};
    }
}

sub parse_percent_c_expr {
    my ($expr) = @_;
    $expr =~ s/\s+//g;    # remove whitespace
    my $num = qr/\d+|0x[0-9a-fA-F]+/;

    # 80 + %c
    if ( $expr =~ /^($num)\+\%c$/ ) {
        return ( formula => "A+B*%c", A => dec($1), B => 1 );
    }

    # 70 + 8 * %c
    if ( $expr =~ /^($num)\+($num)\*\%c$/ ) {
        return ( formula => "A+B*%c", A => dec($1), B => dec($2) );
    }

    # 104 + %c - 1
    if ( $expr =~ /^($num)\+\%c-($num)$/ ) {
        return ( formula => "A+B*%c", A => dec($1) - dec($2), B => 1 );
    }

    # %c == 8 ? 79 : 72 + %c - 1
    if ( $expr =~ /^\%c==($num)\?($num):($num)\+\%c-($num)$/ ) {
        return (
            formula => "%c==A?B:C+%c",
            A       => dec($1),
            B       => dec($2),
            C       => dec($3) - dec($4)
        );
    }

    # %c == 0 ? 0x46 : %c == 1 ? 0x56 : 0x5E
    if ( $expr =~ /^\%c==($num)\?($num):\%c==($num)\?($num):($num)$/ ) {
        return (
            formula => "%c==A?B:%c==C?D:E",
            A       => dec($1),
            B       => dec($2),
            C       => dec($3),
            D       => dec($4),
            E       => dec($5)
        );
    }

    # %c == 0 ? 0x46 : %c == 1 ? 0x56 : %c == 2 ? 0x5E : 0x4E
    if ( $expr =~
        /^\%c==($num)\?($num):\%c==($num)\?($num):\%c==($num)\?($num):($num)$/ )
    {
        return (
            formula => "%c==A?B:%c==C?D:%c==E?F:G",
            A       => dec($1),
            B       => dec($2),
            C       => dec($3),
            D       => dec($4),
            E       => dec($5),
            F       => dec($6),
            G       => dec($7)
        );
    }

    # 199 + ( %c < 8 ? %c * 8 : %c )
    if ( $expr =~ /^($num)\+\(\%c<8\?\%c\*8:\%c\)$/ ) {
        return ( formula => "A+(%c<8?%c*8:%c)", A => dec($1) );
    }

    die "unexpected format for '%c' expression: '$expr'\n";
}

sub dec {
    my ($num) = @_;
    if ( $num =~ /^\d+$/ ) {
        return $num + 0;
    }
    else {
        return oct($num);
    }
}

sub fhex {
    my ($value) = @_;
    return sprintf( "0x%02X", $value );
}

sub validation_const {
    my (@values) = @_;
    return "CheckRange::Is_" . join( "_", map { sprintf "%X", $_ } @values );
}

sub patch_formula {
    my ($formula) = @_;
    if ( $formula eq "" ) {
        return "ExprFormula::None";
    }
    if ( $formula eq "A+B*%c" ) {
        return "ExprFormula::AddScaled";
    }
    if ( $formula eq "%c==A?B:C+%c" ) {
        return "ExprFormula::SelectOrAdd";
    }
    if ( $formula eq "%c==A?B:%c==C?D:E" ) {
        return "ExprFormula::Select2";
    }
    if ( $formula eq "%c==A?B:%c==C?D:%c==E?F:G" ) {
        return "ExprFormula::Select3";
    }
    if ( $formula eq "A+(%c<8?%c*8:%c)" ) {
        return "ExprFormula::ScaleBelowThreshold";
    }
    die "Invalid formula $formula";
}

# convesion of JR to JP
sub get_jp_ops {
    my ( $asm, $cpu ) = @_;
    if ( $asm =~ /^ (.*) (djnz|dwjnz) \s* (:? (\w+.*) ,)? \s* %j $/x ) {

        # decode instruction
        my ( $prefix, $op, $reg ) = ( $1, $2 );
        if ( !$reg ) {
            $reg = $op eq 'djnz' ? 'b' : 'bc';
        }

        # get opcodes of alternative instructions
        my @ops = lookup_opcode_ops( $prefix . "dec $reg", $cpu );
        push @ops, lookup_opcode_ops( "jp nz, %m", $cpu );

        # get index and offset of placeholders
        my @indexes = indexes { /%m/ } @ops;
        @indexes or die "%m not found in @ops";
        for my $i (@indexes) {
            $ops[$i] = 0;    # placeholder
        }
        return ( $indexes[0], scalar(@indexes), @ops );
    }
    elsif ( $asm =~ /^ (.*) jr \s+ ( (?: \w+ ,)? ) \s* %j $/x ) {

        # decode instruction
        my ( $prefix, $flag ) = ( $1, $2 );

        # get opcodes of alternative instructions
        my @ops = lookup_opcode_ops( $prefix . "jp $flag" . "%m", $cpu );

        # get index and offset of placeholders
        my @indexes = indexes { /%m/ } @ops;
        @indexes or die "%m not found in @ops";
        for my $i (@indexes) {
            $ops[$i] = 0;    # placeholder
        }
        return ( $indexes[0], scalar(@indexes), @ops );
    }
    else {
        my @ops = lookup_opcode_ops( $asm, $cpu );
        return ( 0, 0, @ops );
    }
}

sub lookup_opcode_ops {
    my ( $asm, $cpu ) = @_;

    # tokenize instruction
    my @asm_tokens = Trie->lex( $asm, $cpu );

    # navigate trie
    my $node = $trie->trie;
    for (@asm_tokens) {
        my ( $token, $token_value ) = @$_;
        ref($node) eq 'HASH' && ref( $node->{$token} ) eq 'HASH'
            or die "cannot parse $asm, $cpu, node:\n" . dump($node);
        $node = $node->{$token};
    }

    # extract result
    my $value_id = $node->{_value}
        or die "cannot parse $asm, $cpu, node:\n" . dump($node);
    my $value = $trie->values->[$value_id]
        or die "cannot parse $asm, $cpu, node:\n" . dump($node);

    # decode ops
    my ( $const, $ops, $cpu_ ) = split( /\|/, $value->{value}, 3 );
    $cpu eq $cpu_
        or die
        "CPU mismatch in value for asm '$asm': expected '$cpu', got '$cpu_'\n"
        . dump($value);
    my @ops = map { s/^([0-9a-fA-F]+)$/hex($1)/er } split( /\s+|;/, $ops );

    return @ops;
}

sub output_h {
    my ($basename) = @_;
    my $h = "extern TrieAction ${basename}_actions[];\n";
    $h .= "extern uint8_t ${basename}_bytecode[];\n";
    return $h;
}

sub output_cpp {
    my ($basename) = @_;
    my $cpp =
          "TrieAction ${basename}_actions["
        . scalar( @{ $trie->values } )
        . "] = {\n";
    for my $value ( @{ $trie->values } ) {
        $cpp .=
              "    /* action $value->{id} */ "
            . "{ $value->{bytecode_index}, $value->{bytecode_length} }, "
            . "// $value->{_cpu}, $value->{_asm} => $value->{value}\n";
    }
    $cpp .= "};\n\n";

    $cpp .=
          "uint8_t ${basename}_bytecode["
        . scalar( @{ $trie->bytecode } )
        . "] = {\n";
    for my $id ( 0 .. $#{ $trie->bytecode } ) {
        my $bytecode = $trie->bytecode->[$id];
        if ( exists $bytecode->{id} ) {
            $cpp .=
"\n    /* $bytecode->{cpu}, $bytecode->{asm} => $bytecode->{value} */\n";
        }
        $cpp .= "    /* bytecode $id */ $bytecode->{op},\n";
    }
    $cpp .= "};\n\n";
    return $cpp;
}
