#!/usr/bin/env perl

#------------------------------------------------------------------------------
# Z80 assembler
# Copyright (C) Paulo Custodio, 2011-2026
# License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
#------------------------------------------------------------------------------

use Modern::Perl;

@ARGV==1 or die "usage: $0 output_basename\n";
my $output_basename = shift;

open(my $out_h, ">", "../$output_basename.h") or die "write ../$output_basename.h: $!\n";
say $out_h "// generated by $0";
say $out_h "#pragma once";
say $out_h "#include \"cpu.h\"";
say $out_h "#include \"lexer_keywords.h\"";
say $out_h "#include \"lexer_tokens.h\"";
say $out_h "#include <cstdint>";
say $out_h "#include <unordered_map>";

open(my $out_cpp, ">", "../$output_basename.cpp") or die "write ../$output_basename.cpp: $!\n";
say $out_cpp "// generated by $0";
say $out_cpp "#include \"$output_basename.h\"";
say $out_cpp "#include \"cpu.h\"";
say $out_cpp "#include \"lexer_keywords.h\"";
say $out_cpp "#include \"lexer_tokens.h\"";
say $out_cpp "#include <unordered_map>";

# read CPUs
my @cpus;
open(my $fh, "<", "../cpu.def") or die "open ../cpu.def: $!";
while (<$fh>) {
	/^\s* X \( \s* (\d+) \s* , \s* (\w+)/x or next;
	my($id, $cpu) = ($1, $2);
	$cpus[$id] = $2;
}

# read TokenTypes
my @token_types;
open($fh, "<", "../lexer_tokens.def") or die "open ../lexer_tokens.def: $!";
while (<$fh>) {
	/^\s* X \( \s* (\w+)/x or next;
	push @token_types, $1;
}

# read Keywords
my @keywords;
open($fh, "<", "../lexer_keywords.def") or die "open ../lexer_keywords.def: $!";
while (<$fh>) {
	/^\s* X \( \s* (\w+)/x or next;
	push @keywords, $1;
}

# make union of three structures
my @TrieToken = ("None", "Expr");
my %TrieMap = (None => 0, Expr => 1);

for my $cpu (@cpus) {
	next if $cpu eq 'none';
	my $id = scalar(@TrieToken);
	my $trie = "cpu_".$cpu;
	push @TrieToken, $trie;
	$TrieMap{$trie} = $id;
}

for my $token_type (@token_types) {
	next if $token_type eq 'None';
	my $id = scalar(@TrieToken);
	my $trie = "TK_".$token_type;
	push @TrieToken, $trie;
	$TrieMap{$trie} = $id;
}

for my $keyword (@keywords) {
	next if $keyword eq 'None';
	my $id = scalar(@TrieToken);
	my $trie = "KW_".$keyword;
	push @TrieToken, $trie;
	$TrieMap{$trie} = $id;
}

# output enum class TrieToken
say $out_h "enum class TrieToken : uint16_t {";
for my $trie (@TrieToken) {
	say $out_h "    ", $trie, " = ", $TrieMap{$trie}, ", ";
}
say $out_h "};";

# output TrieToken get_trie_token(CPU cpu_id);
say $out_h "extern const std::unordered_map<CPU, TrieToken> ".
		   "cpu_to_trie_token_lu;";
say $out_cpp "const std::unordered_map<CPU, TrieToken> ".
			 "cpu_to_trie_token_lu = {";
for my $cpu (@cpus) {
	next if $cpu eq 'none';
	my $trie = "cpu_".$cpu;
	say $out_cpp "    { CPU::$cpu, TrieToken::$trie },";
}
say $out_cpp "};";

# output TrieToken get_to_trie_token(TokenType tt);
say $out_h "extern const std::unordered_map<TokenType, TrieToken> ".
		   "token_type_to_trie_token_lu;";
say $out_cpp "const std::unordered_map<TokenType, TrieToken> ".
			 "token_type_to_trie_token_lu = {";
for my $token_type (@token_types) {
	next if $token_type eq 'None';
	my $trie = "TK_".$token_type;
	say $out_cpp "    { TokenType::$token_type, TrieToken::$trie },";
}
say $out_cpp "};";

# output TrieToken get_trie_token(Keyword kw);
say $out_h "extern const std::unordered_map<Keyword, TrieToken> ".
		   "keyword_to_trie_token_lu;";
say $out_cpp "const std::unordered_map<Keyword, TrieToken> ".
			 "keyword_to_trie_token_lu = {";
for my $keyword (@keywords) {
	next if $keyword eq 'None';
	my $trie = "KW_".$keyword;
	say $out_cpp "    { Keyword::$keyword, TrieToken::$trie },";
}
say $out_cpp "};";
