#!/usr/bin/env perl

#------------------------------------------------------------------------------
# Z80 assembler
# Copyright (C) Paulo Custodio, 2011-2026
# License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
#------------------------------------------------------------------------------

use Modern::Perl;
use FindBin;
use lib "$FindBin::Bin";    # adjust to find modules
use Opcodes;

@ARGV == 1 or die "usage: $0 output_basename\n";
my $output_basename = shift;

open( my $out_h, ">", "../$output_basename.h" ) or die "write ../$output_basename.h: $!\n";
say $out_h "// generated by $0";
say $out_h "#pragma once";

open( my $out_cpp, ">", "../$output_basename.cpp" ) or die "write ../$output_basename.cpp: $!\n";
say $out_cpp "// generated by $0";
say $out_cpp "#include \"$output_basename.h\"";

