#!/usr/bin/env perl

#------------------------------------------------------------------------------
# Z80 assembler
# Copyright (C) Paulo Custodio, 2011-2026
# License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
#------------------------------------------------------------------------------

use Modern::Perl;
use Data::Dump 'dump';
use FindBin;
use lib "$FindBin::Bin";    # adjust to find modules
use Trie;
use warnings FATAL => 'uninitialized';

@ARGV == 3
    or die "usage: $0 synthetic.dat opcodes_trie_token.h output_basename\n";
my ( $synthetic_dat, $opcodes_trie_token_h, $output_basename ) = @ARGV;

my $trie = Trie->new;
$trie->read_token_id($opcodes_trie_token_h);

open( my $in, "<", $synthetic_dat ) or die "open $synthetic_dat: $!";
chomp( my $title = <$in> );
$title eq "asm|cpu|synth"
    or die "invalid $synthetic_dat: expected title 'asm|cpu|synth', got '$title'\n";

while (<$in>) {
    chomp;
    my ( $asm, $cpu, $synth ) = split( /\|/, $_, 3 );
    $cpu =~ s/^80/i80/;    # CPU name cannot start with a digit, so 8080 is renamed to i8080
    $trie->add( $asm, $cpu, $synth );
}

$trie->make_table;
build_actions($trie);

open( my $out_h, ">", "../$output_basename.h" ) or die "write ../$output_basename.h: $!\n";
say $out_h "// generated by $0";
say $out_h "#pragma once";
say $out_h "#include \"opcodes.h\"";
say $out_h $trie->output_h($output_basename);
say $out_h output_h($output_basename);

open( my $out_cpp, ">", "../$output_basename.cpp" ) or die "write ../$output_basename.cpp: $!\n";
say $out_cpp "// generated by $0";
say $out_cpp "#include \"$output_basename.h\"";
say $out_cpp "#include \"opcodes.h\"";
say $out_cpp "#include \"opcodes_trie_token.h\"";
say $out_cpp "#include <cstdint>";
say $out_cpp $trie->output_cpp($output_basename);
say $out_cpp output_cpp($output_basename);

sub build_actions {
    my ($trie) = @_;
    for my $value ( @{ $trie->values } ) {
        my $id    = $value->{id};
        my $asm   = $value->{_asm};
        my $cpu   = $value->{_cpu};
        my $synth = $value->{value};

        # tokenize input and extract expressions indexes
        my @asm_tokens = Trie->lex( $asm, undef );
        my @asm_exprs;
        my %asm_exprs;
        for (@asm_tokens) {
            my ( $token, $token_value ) = @$_;
            if ( $token eq "TrieToken::Expr" || $token eq "TrieToken::DispExpr" ) {

                # expressions must be unique
                if ( exists $asm_exprs{$token_value} ) {
                    die "duplicate expression '$token_value' in asm for value ID $id:\n"
                        . "asm:   $asm\n"
                        . "synth: $synth\n";
                }
                my $index = scalar(@asm_exprs);
                push @asm_exprs, { id => $index, value => $token_value };
                $asm_exprs{$token_value} = $index;
            }
        }
        $value->{asm_tokens} = \@asm_tokens;
        $value->{asm_exprs}  = \@asm_exprs;

        # tokenize synth and extract labels indexes
        my @synth_tokens = Trie->lex( $synth, undef );
        my @synth_labels;
        my %synth_labels;
        for (@synth_tokens) {
            my ( $token, $token_value ) = @$_;
            if ( $token eq "TrieToken::Label" ) {

                # labels will appear more than once
                if ( !exists $synth_labels{$token_value} ) {
                    my $index = scalar(@synth_labels);
                    push @synth_labels, { id => $index, value => $token_value };
                    $synth_labels{$token_value} = $index;
                }
            }
        }
        $value->{synth_tokens} = \@synth_tokens;
        $value->{synth_labels} = \@synth_labels;

        # build bytecode for this action
        my $start_bytecode_index = scalar( @{ $trie->bytecode } );
        for (@synth_tokens) {
            my ( $token, $token_value ) = @$_;

            if ( $token eq "TrieToken::TK_EndOfLine" ) {
                push @{ $trie->bytecode }, { op => "SynthOp::EmitLineBreak", value => 0 };
            }
            elsif ( $token eq "TrieToken::TK_Integer" ) {
                push @{ $trie->bytecode }, { op => "SynthOp::EmitInteger", value => $token_value };
            }
            elsif ( $token eq "TrieToken::Expr" ) {
                my $expr_index = $asm_exprs{$token_value};
                push @{ $trie->bytecode }, { op => "SynthOp::EmitExprRef", value => $expr_index };
            }
            elsif ( $token eq "TrieToken::DispExpr" ) {
                my $expr_index = $asm_exprs{$token_value};
                push @{ $trie->bytecode },
                    { op => "SynthOp::EmitDispExprRef", value => $expr_index };
            }
            elsif ( $token eq "TrieToken::Label" ) {
                my $label_index = $synth_labels{$token_value};
                push @{ $trie->bytecode }, { op => "SynthOp::EmitLabelRef", value => $label_index };
            }
            else {
                push @{ $trie->bytecode },
                    {
                    op    => "SynthOp::EmitToken",
                    value => "static_cast<uint16_t>($token)"
                    };
            }
        }
        my $end_bytecode_index = scalar( @{ $trie->bytecode } );
        $value->{bytecode_index}                     = $start_bytecode_index;
        $value->{bytecode_length}                    = $end_bytecode_index - $start_bytecode_index;
        $trie->bytecode->[$start_bytecode_index]{id} = $start_bytecode_index;
        $trie->bytecode->[$start_bytecode_index]{synth} = $synth;
    }
}

sub output_h {
    my ($basename) = @_;
    my $h = "extern SynthTrieAction ${basename}_actions[];\n";
    $h .= "extern SynthBytecode ${basename}_bytecode[];\n";
    return $h;
}

sub output_cpp {
    my ($basename) = @_;
    my $cpp = "SynthTrieAction ${basename}_actions[" . scalar( @{ $trie->values } ) . "] = {\n";
    for my $value ( @{ $trie->values } ) {
        $cpp .=
              "    { $value->{bytecode_index}, $value->{bytecode_length} }, "
            . "// action $value->{id} bytecode $value->{bytecode_index} "
            . "$value->{_asm} => $value->{value}\n";
    }
    $cpp .= "};\n";

    $cpp .= "SynthBytecode ${basename}_bytecode[" . scalar( @{ $trie->bytecode } ) . "] = {\n";
    for my $bytecode ( @{ $trie->bytecode } ) {
        if ( exists $bytecode->{id} ) {
            $cpp .= "    // bytecode $bytecode->{id}: $bytecode->{synth}\n";
        }
        $cpp .= "    { $bytecode->{op}, $bytecode->{value} },\n";
    }
    $cpp .= "};\n";
    return $cpp;
}
