#!/usr/bin/env perl

#------------------------------------------------------------------------------
# Z80 assembler
# Copyright (C) Paulo Custodio, 2011-2026
# License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
#------------------------------------------------------------------------------

use Modern::Perl;

@ARGV == 1 or die "usage: $0 output_basename\n";
my $output_basename = shift;

open( my $out_h, ">", "../$output_basename.h" )
    or die "write ../$output_basename.h: $!\n";
say $out_h "// generated by $0";
say $out_h "#pragma once";
say $out_h "#include \"cpu.h\"";
say $out_h "#include \"lexer_keywords.h\"";
say $out_h "#include \"lexer_tokens.h\"";
say $out_h "#include <cstdint>";
say $out_h "";

open( my $out_cpp, ">", "../$output_basename.cpp" )
    or die "write ../$output_basename.cpp: $!\n";
say $out_cpp "// generated by $0";
say $out_cpp "#include \"$output_basename.h\"";
say $out_cpp "#include \"cpu.h\"";
say $out_cpp "#include \"lexer_keywords.h\"";
say $out_cpp "#include \"lexer_tokens.h\"";
say $out_cpp "";

# read CPUs
my @cpus;
open( my $fh, "<", "../cpu.def" ) or die "open ../cpu.def: $!";
while (<$fh>) {
    /^\s* X \( \s* (\d+) \s* , \s* (\w+)/x or next;
    my ( $id, $cpu ) = ( $1, $2 );
    $cpus[$id] = $2;
}

# read TokenTypes
my @token_types;
open( $fh, "<", "../lexer_tokens.def" ) or die "open ../lexer_tokens.def: $!";
while (<$fh>) {
    /^\s* X \( \s* (\w+)/x or next;
    push @token_types, $1;
}

# read Keywords
my @keywords;
open( $fh, "<", "../lexer_keywords.def" )
    or die "open ../lexer_keywords.def: $!";
while (<$fh>) {
    /^\s* X \( \s* (\w+)/x or next;
    push @keywords, $1;
}

# make union of three structures
my @TrieToken;
my %TrieMap;

for my $trie (qw( None Expr DispExpr Label )) {
    my $id = scalar(@TrieToken);
    push @TrieToken, $trie;
    $TrieMap{$trie} = $id;
}

for my $cpu (@cpus) {
    next if $cpu eq 'none';
    my $id   = scalar(@TrieToken);
    my $trie = "cpu_" . $cpu;
    push @TrieToken, $trie;
    $TrieMap{$trie} = $id;
}

for my $token_type (@token_types) {
    next if $token_type eq 'None';
    my $id   = scalar(@TrieToken);
    my $trie = "TK_" . $token_type;
    push @TrieToken, $trie;
    $TrieMap{$trie} = $id;
}

for my $keyword (@keywords) {
    next if $keyword eq 'None';
    my $id   = scalar(@TrieToken);
    my $trie = "KW_" . $keyword;
    push @TrieToken, $trie;
    $TrieMap{$trie} = $id;
}

# output enum class TrieToken
say $out_h "enum class TrieToken : uint16_t {";
for my $trie (@TrieToken) {
    say $out_h "    ", $trie, " = ", $TrieMap{$trie}, ",";
}
say $out_h "};\n";

# output CPU conversion functions
my $num_cpus = scalar(@cpus);
say $out_h "extern TrieToken to_trie_token(CPU cpu);";
say $out_cpp "TrieToken to_trie_token(CPU cpu) {";
say $out_cpp "    static constexpr TrieToken lut[$num_cpus] = {";
for my $cpu_id ( 0 .. $num_cpus - 1 ) {
    my $trie = "TrieToken::None";
    if ( $cpus[$cpu_id] ne 'none' ) {
        $trie = "TrieToken::cpu_" . $cpus[$cpu_id];
    }
    say $out_cpp "        $trie, // CPU::$cpus[$cpu_id] = $cpu_id";
}
say $out_cpp "    };";
say $out_cpp "    return lut[static_cast<size_t>(cpu)];";
say $out_cpp "}\n";

my $num_trie_tokens = scalar(@TrieToken);
say $out_h "extern CPU to_cpu(TrieToken trie_token);";
say $out_cpp "CPU to_cpu(TrieToken trie_token) {";
say $out_cpp "    static constexpr CPU lut[$num_trie_tokens] = {";
for my $trie_id ( 0 .. $num_trie_tokens - 1 ) {
    my $trie = $TrieToken[$trie_id];
    my $cpu  = "CPU::none";
    if ( $trie =~ /^cpu_(\w+)/ ) {
        $cpu = "CPU::$1";
    }
    say $out_cpp "        $cpu, // TrieToken::$trie = $TrieMap{$trie}";
}
say $out_cpp "    };";
say $out_cpp "    return lut[static_cast<size_t>(trie_token)];";
say $out_cpp "}\n";

# output TokenType conversion functions
my $num_token_types = scalar(@token_types);
say $out_h "extern TrieToken to_trie_token(TokenType token_type);";
say $out_cpp "TrieToken to_trie_token(TokenType token_type) {";
say $out_cpp "    static constexpr TrieToken lut[$num_token_types] = {";
for my $token_type_id ( 0 .. $num_token_types - 1 ) {
    my $trie = "TrieToken::None";
    if ( $token_types[$token_type_id] ne 'None' ) {
        $trie = "TrieToken::TK_" . $token_types[$token_type_id];
    }
    say $out_cpp
"        $trie, // TokenType::$token_types[$token_type_id] = $token_type_id";
}
say $out_cpp "    };";
say $out_cpp "    return lut[static_cast<size_t>(token_type)];";
say $out_cpp "}\n";

say $out_h "extern TokenType to_token_type(TrieToken trie_token);";
say $out_cpp "TokenType to_token_type(TrieToken trie_token) {";
say $out_cpp "    static constexpr TokenType lut[$num_trie_tokens] = {";
for my $trie_id ( 0 .. $num_trie_tokens - 1 ) {
    my $trie       = $TrieToken[$trie_id];
    my $token_type = "TokenType::None";
    if ( $trie =~ /^TK_(\w+)/ ) {
        $token_type = "TokenType::$1";
    }
    say $out_cpp "        $token_type, // TrieToken::$trie = $TrieMap{$trie}";
}
say $out_cpp "    };";
say $out_cpp "    return lut[static_cast<size_t>(trie_token)];";
say $out_cpp "}\n";

# output Keyword conversion functions
my $num_keywords = scalar(@keywords);
say $out_h "extern TrieToken to_trie_token(Keyword keyword);";
say $out_cpp "TrieToken to_trie_token(Keyword keyword) {";
say $out_cpp "    static constexpr TrieToken lut[$num_keywords] = {";
for my $keyword_id ( 0 .. $num_keywords - 1 ) {
    my $trie = "TrieToken::None";
    if ( $keywords[$keyword_id] ne 'None' ) {
        $trie = "TrieToken::KW_" . $keywords[$keyword_id];
    }
    say $out_cpp
        "        $trie, // Keyword::$keywords[$keyword_id] = $keyword_id";
}
say $out_cpp "    };";
say $out_cpp "    return lut[static_cast<size_t>(keyword)];";
say $out_cpp "}\n";

say $out_h "extern Keyword to_keyword(TrieToken trie_token);";
say $out_cpp "Keyword to_keyword(TrieToken trie_token) {";
say $out_cpp "    static constexpr Keyword lut[$num_trie_tokens] = {";
for my $trie_id ( 0 .. $num_trie_tokens - 1 ) {
    my $trie    = $TrieToken[$trie_id];
    my $keyword = "Keyword::None";
    if ( $trie =~ /^KW_(\w+)/ ) {
        $keyword = "Keyword::$1";
    }
    say $out_cpp "        $keyword, // TrieToken::$trie = $TrieMap{$trie}";
}
say $out_cpp "    };";
say $out_cpp "    return lut[static_cast<size_t>(trie_token)];";
say $out_cpp "}\n";
