#!/usr/bin/env perl

#------------------------------------------------------------------------------
# Z80 assembler
# Copyright (C) Paulo Custodio, 2011-2026
# License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
#------------------------------------------------------------------------------

# generate the test driver data

use Modern::Perl;
use Path::Tiny;

@ARGV == 2 or die "usage: $0 DIR OUTPUT.DEF\n";
my ( $dir, $output_def ) = @ARGV;

my @tests  = collect_tests($dir);
my $x_list = make_x_list( sort @tests );
path($output_def)->spew($x_list);
exit;

sub collect_tests {
    my ($dir) = @_;
    my @tests;
    for my $cpp_file ( path($dir)->children(qr/\.cpp$/) ) {
        for my $line ( $cpp_file->lines ) {
            if ( $line =~ /^ \s* void \s+ (test_\w+) \s* \( /x ) {
                push @tests, $1;
            }
        }
    }
    return @tests;
}

sub make_x_list {
    my (@tests) = @_;
    my $x_list = "// generated by $0\n";
    for my $test (@tests) {
        $x_list .= "X($test)\n";
    }
    return $x_list;
}
