#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.2 2001-04-18 12:40:07 stefano Exp $

all:
	@echo ''
	@echo 'Nowt todo here (clock is asm)'
	@echo ''
	@echo ''

clean:
	rm -f *.o* *.i *.sym *.map zcc_opt.def
