
// automatically generated by m4 from headers in proto subdir


#ifndef __ARCH_YAZ180_H__
#define __ARCH_YAZ180_H__

#include <arch.h>

// provide the asci1 input and output stream instantiation
// note that asci0 is attached to stdin and stdout

extern FILE *linein;
extern FILE *lineout;

// Halt the YAZ180 with single step hardware.

#define __BREAK  __BREAK_HELPER()
extern void __BREAK_HELPER(void);



#endif
