
// automatically generated by m4 from headers in proto subdir


#ifndef __ARCH_YAZ180_H__
#define __ARCH_YAZ180_H__

#include <arch.h>

// Halt the YAZ180 with single step hardware.

#define __BREAK  __BREAK_HELPER()
extern void __BREAK_HELPER(void);



#endif
