# $Id: Makefile,v 1.14 2005-09-07 01:30:33 aralbrec Exp $

lcpc:
	cd cpc ; $(MAKE) ; cd ..

lz88:
	cd z88 ; $(MAKE) z88_fcntl ; cd ..

lzx:	
	cd spectrum ; $(MAKE) ; cd ..
	cd dummy    ; $(MAKE) ; cd ..

lcpm:
	cd cpm ; $(MAKE) ; cd ..

lpps:
	cd sprinter ; $(MAKE) ; cd ..

lzxvgs:
	cd zxvgs; $(MAKE) ; cd ..

lcpcold:
	cd cpc ; $(MAKE) ; cd ..
	cd dummy    ; $(MAKE) ; cd ..

clean:
	cd cpm ; $(MAKE) clean ; cd ..
	cd dummy ; $(MAKE) clean ; cd ..
	cd spectrum ; $(MAKE) clean ; cd ..
	cd sprinter ; $(MAKE) clean ; cd ..
	cd z88 ; $(MAKE) clean ; cd ..
	cd zxvgs ; $(MAKE) clean ; cd ..
	cd cpc ; $(MAKE) clean ; cd ..
