//-----------------------------------------------------------------------------
// z80asm
// parser
// Copyright (C) Paulo Custodio, 2011-2022
// License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
//-----------------------------------------------------------------------------

#pragma once

#include "expr.h"
#include "lex.h"
#include "symtab.h"
#include "utils.h"
#include <deque>
using namespace std;

class Asm;
class Expr;

class Parser {
public:
	void clear();
	bool parse();		// parse lines from g_preproc

private:
	enum class State { Main };

	Lexer	m_lexer;						// line being parsed
	State	m_state{ State::Main };			// parser state
	deque<shared_ptr<Expr>> m_exprs;		// parsed expressions

	void parse_line();
	void parse_line_main();
	string check_label();
	void parse_symbol_declare(Symbol::Scope scope);

	bool expr_in_parens();
	void add_emul_call_flag(unsigned bytes_jump, unsigned bytes_call);
	void add_call_function(const string& function_name);
	void add_jump_relative(unsigned bytes);
	void add_z80n_mmu_n();
	void add_z80n_mmu_a();
	void add_restart();
	void add_opcode(unsigned bytes);
	void add_opcode_n(unsigned bytes);
	void add_opcode_s(unsigned bytes);
	void add_opcode_h(unsigned bytes);
	void add_opcode_n_0(unsigned bytes);
	void add_opcode_s_0(unsigned bytes);
	void add_opcode_nn(unsigned bytes);
	void add_opcode_NN(unsigned bytes);
	void add_opcode_idx(unsigned bytes);
	void add_opcode_idx_n(unsigned bytes);
	void add_opcode_n_n(unsigned bytes);

	// generated by make_parser_code.pl
	void parse_main1();
	void parse_main1_action(int action);
};
