#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.4 2001-04-18 12:43:04 stefano Exp $


all:
	zcc  -Wn43 -D__Z88__ -vn -make-lib atol.c


clean:
	rm -f *.o* *.sym *.map zcc_opt.def
