#
# Makefile for OZ-7xx specific libraries - ozinput
#
# $Id: Makefile,v 1.4 2008-03-14 12:23:59 stefano Exp $

include ../../Make.config

all:	
	zcc +ozansi $(CFLAGS) *.c

clean:
	$(RM) *.o* zcc_opt.def
