#
# Makefile for OZ-7xx specific libraries - ozinput
#
# $Id: Makefile,v 1.5 2014-06-02 09:59:20 stefano Exp $

include ../../Make.config

all:	
	zcc +test $(CFLAGS) *.c

clean:
	$(RM) *.o* zcc_opt.def
