#
# Wahey, a messed up makefile for building libraries!
#



all:
	zcc -vn -Wn43 -make-lib itou.c
	zcc -vn -Wn43 -make-lib utoi.c
	zcc -vn -Wn43 -make-lib printf.c
	zcc -vn -Wn43 -make-lib sprintf.c
	zcc -vn -Wn43 -make-lib fprintf.c
	zcc -vn -Wn43 -make-lib vfprintf_comp.c
	zcc -vn -Wn43 -make-lib vsprintf.c
	zcc -vn -Wn43 -make-lib scanf.c
	zcc -vn -Wn43 -make-lib sscanf.c
	zcc -vn -Wn43 -make-lib fscanf.c
	zcc -vn -Wn43 -make-lib vfscanf.c
	zcc -vn -Wn43 -make-lib vsscanf.c


clean:
	rm -f *.err *.o* *.sym *.map zcc_opt.def
