#
# $Id: Makefile,v 1.1 2008-06-03 12:07:50 stefano Exp $

all:
	@echo ''
	@echo '---> Building CPC RS232 library (STI) <---'
	@echo ''
	cd sti ; $(MAKE) ; cd ..


clean:
	cd sti ; $(MAKE) clean ; cd ..
