






defc __R2KA = 0x00

defc __R2KA_IQ2T = 0x00
defc __R2KA_IQ3T = 0x01
defc __R2KA_IQ4T = 0x02
defc __R2KA_IQ5T = 0x03

defc __IO_GCSR = 0x00

defc __IO_RTCCR = 0x01
defc __IO_RTC0R = 0x02
defc __IO_RTC1R = 0x03
defc __IO_RTC2R = 0x04
defc __IO_RTC3R = 0x05
defc __IO_RTC4R = 0x06
defc __IO_RTC5R = 0x07

defc __IO_WDTCR = 0x08
defc __IO_WDTTR = 0x09

defc __IO_GCM0R = 0x0A
defc __IO_GCM1R = 0x0B
defc __IO_GOCR = 0x0E
defc __IO_GCDR = 0x0F

defc __IO_MMIDR = 0x10
defc __IO_STACKSEG = 0x11
defc __IO_DATASEG = 0x12
defc __IO_SEGSIZE = 0x13
defc __IO_MB0CR = 0x14
defc __IO_MB1CR = 0x15
defc __IO_MB2CR = 0x16
defc __IO_MB3CR = 0x17

defc __IO_MTCR = 0x19

defc __IO_SPD0R = 0x20
defc __IO_SPD1R = 0x21
defc __IO_SPD2R = 0x22
defc __IO_SPSR = 0x23
defc __IO_SPCR = 0x24

defc __IO_GROM = 0x2C
defc __IO_GRAM = 0x2D
defc __IO_GCPU = 0x2E
defc __IO_GREV = 0x2F

defc __IO_PADR = 0x30

defc __IO_PBDR = 0x40
defc __IO_PBDDR = 0x47

defc __IO_PCDR = 0x50
defc __IO_PCFR = 0x55

defc __IO_PDDR = 0x60
defc __IO_PDCR = 0x64
defc __IO_PDFR = 0x65
defc __IO_PDDCR = 0x66
defc __IO_PDDDR = 0x67
defc __IO_PDB0R = 0x68
defc __IO_PDB1R = 0x69
defc __IO_PDB2R = 0x6A
defc __IO_PDB3R = 0x6B
defc __IO_PDB4R = 0x6C
defc __IO_PDB5R = 0x6D
defc __IO_PDB6R = 0x6E
defc __IO_PDB7R = 0x6F

defc __IO_PEDR = 0x70
defc __IO_PECR = 0x74
defc __IO_PEFR = 0x75
defc __IO_PEDCR = 0x76
defc __IO_PEDDR = 0x77
defc __IO_PEB0R = 0x78
defc __IO_PEB1R = 0x79
defc __IO_PEB2R = 0x7A
defc __IO_PEB3R = 0x7B
defc __IO_PEB4R = 0x7C
defc __IO_PEB5R = 0x7D
defc __IO_PEB6R = 0x7E
defc __IO_PEB7R = 0x7F

defc __IO_IB0CR = 0x80
defc __IO_IB1CR = 0x81
defc __IO_IB2CR = 0x82
defc __IO_IB3CR = 0x83
defc __IO_IB4CR = 0x84
defc __IO_IB5CR = 0x85
defc __IO_IB6CR = 0x86
defc __IO_IB7CR = 0x87

defc __IO_I0CR = 0x98
defc __IO_I1CR = 0x99

defc __IO_TACSR = 0xA0
defc __IO_TAPR = 0xA1
defc __IO_TAT1R = 0xA3
defc __IO_TACR = 0xA4
defc __IO_TAT2R = 0xA5
defc __IO_TAT8R = 0xA6
defc __IO_TAT3R = 0xA7
defc __IO_TAT9R = 0xA8
defc __IO_TAT4R = 0xA9
defc __IO_TAT10R = 0xAA
defc __IO_TAT5R = 0xAB
defc __IO_TAT6R = 0xAD
defc __IO_TAT7R = 0xAF

defc __IO_TBCSR = 0xB0
defc __IO_TBCR = 0xB1
defc __IO_TBM1R = 0xB2
defc __IO_TBL1R = 0xB3
defc __IO_TBM2R = 0xB4
defc __IO_TBL2R = 0xB5
defc __IO_TBCMR = 0xBE
defc __IO_TBCLR = 0xBF

defc __IO_SADR = 0xC0
defc __IO_SAAR = 0xC1
defc __IO_SALR = 0xC2
defc __IO_SASR = 0xC3
defc __IO_SACR = 0xC4

defc __IO_SBDR = 0xD0
defc __IO_SBAR = 0xD1
defc __IO_SBLR = 0xD2
defc __IO_SBSR = 0xD3
defc __IO_SBCR = 0xD4

defc __IO_SCDR = 0xE0
defc __IO_SCAR = 0xE1
defc __IO_SCLR = 0xE2
defc __IO_SCSR = 0xE3
defc __IO_SCCR = 0xE4

defc __IO_SDDR = 0xF0
defc __IO_SDAR = 0xF1
defc __IO_SDLR = 0xF2
defc __IO_SDSR = 0xF3
defc __IO_SDCR = 0xF4




