#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.9 2007-10-02 14:13:48 stefano Exp $


all: 
	@echo 'All in asm'

clean:
	cd .. ; $(MAKE) gfxdeps ; cd graphics
	$(RM) abc80/*.o
	$(RM) aquarius/*.o
	$(RM) c128/*.o
	$(RM) cpc/*.o
	$(RM) mz/*.o
	$(RM) nascom/*.o
	$(RM) oz/*.o
	$(RM) gray/*.o
	$(RM) gray/ticalc/*.o
	$(RM) gray/cpc/*.o
