INCLUDE "config_private.inc"

SECTION code_arch

PUBLIC _SYSVAR_SWAP
defc _SYSVAR_SWAP = __SYSVAR_SWAP

PUBLIC _SYSVAR_STOO
defc _SYSVAR_STOO = __SYSVAR_STOO

PUBLIC _SYSVAR_YOUNGER
defc _SYSVAR_YOUNGER = __SYSVAR_YOUNGER

PUBLIC _SYSVAR_REGNUOY
defc _SYSVAR_REGNUOY = __SYSVAR_REGNUOY

PUBLIC _SYSVAR_ONERR
defc _SYSVAR_ONERR = __SYSVAR_ONERR

PUBLIC _SYSVAR_OLDHL
defc _SYSVAR_OLDHL = __SYSVAR_OLDHL

PUBLIC _SYSVAR_OLDBC
defc _SYSVAR_OLDBC = __SYSVAR_OLDBC

PUBLIC _SYSVAR_OLDAF
defc _SYSVAR_OLDAF = __SYSVAR_OLDAF

PUBLIC _SYSVAR_TARGET
defc _SYSVAR_TARGET = __SYSVAR_TARGET

PUBLIC _SYSVAR_RETADDR
defc _SYSVAR_RETADDR = __SYSVAR_RETADDR

PUBLIC _SYSVAR_BANKM
defc _SYSVAR_BANKM = __SYSVAR_BANKM

PUBLIC _SYSVAR_RAMRST
defc _SYSVAR_RAMRST = __SYSVAR_RAMRST

PUBLIC _SYSVAR_RAMERR
defc _SYSVAR_RAMERR = __SYSVAR_RAMERR

PUBLIC _SYSVAR_BAUD
defc _SYSVAR_BAUD = __SYSVAR_BAUD

PUBLIC _SYSVAR_SERFL
defc _SYSVAR_SERFL = __SYSVAR_SERFL

PUBLIC _SYSVAR_COL
defc _SYSVAR_COL = __SYSVAR_COL

PUBLIC _SYSVAR_WIDTH
defc _SYSVAR_WIDTH = __SYSVAR_WIDTH

PUBLIC _SYSVAR_TVPARS
defc _SYSVAR_TVPARS = __SYSVAR_TVPARS

PUBLIC _SYSVAR_FLAGS3
defc _SYSVAR_FLAGS3 = __SYSVAR_FLAGS3

PUBLIC _SYSVAR_BANK678
defc _SYSVAR_BANK678 = __SYSVAR_BANK678

PUBLIC _SYSVAR_XLOC
defc _SYSVAR_XLOC = __SYSVAR_XLOC

PUBLIC _SYSVAR_YLOC
defc _SYSVAR_YLOC = __SYSVAR_YLOC

PUBLIC _SYSVAR_OLDSP
defc _SYSVAR_OLDSP = __SYSVAR_OLDSP

PUBLIC _SYSVAR_SYNRET
defc _SYSVAR_SYNRET = __SYSVAR_SYNRET

PUBLIC _SYSVAR_LASTV
defc _SYSVAR_LASTV = __SYSVAR_LASTV

PUBLIC _SYSVAR_RCLINE
defc _SYSVAR_RCLINE = __SYSVAR_RCLINE

PUBLIC _SYSVAR_RCSTART
defc _SYSVAR_RCSTART = __SYSVAR_RCSTART

PUBLIC _SYSVAR_RCSTEP
defc _SYSVAR_RCSTEP = __SYSVAR_RCSTEP

PUBLIC _SYSVAR_LODDRV
defc _SYSVAR_LODDRV = __SYSVAR_LODDRV

PUBLIC _SYSVAR_SAVDRV
defc _SYSVAR_SAVDRV = __SYSVAR_SAVDRV

PUBLIC _SYSVAR_DUMPLF
defc _SYSVAR_DUMPLF = __SYSVAR_DUMPLF

PUBLIC _SYSVAR_STRIP1
defc _SYSVAR_STRIP1 = __SYSVAR_STRIP1

PUBLIC _SYSVAR_STRIP2
defc _SYSVAR_STRIP2 = __SYSVAR_STRIP2

PUBLIC _SYSVAR_TSTACK
defc _SYSVAR_TSTACK = __SYSVAR_TSTACK


PUBLIC _SYSVAR_KSTATE
defc _SYSVAR_KSTATE = __SYSVAR_KSTATE

PUBLIC _SYSVAR_LASTK
defc _SYSVAR_LASTK = __SYSVAR_LASTK

PUBLIC _SYSVAR_REPDEL
defc _SYSVAR_REPDEL = __SYSVAR_REPDEL

PUBLIC _SYSVAR_REPPER
defc _SYSVAR_REPPER = __SYSVAR_REPPER

PUBLIC _SYSVAR_DEFADD
defc _SYSVAR_DEFADD = __SYSVAR_DEFADD

PUBLIC _SYSVAR_K_DATA
defc _SYSVAR_K_DATA = __SYSVAR_K_DATA

PUBLIC _SYSVAR_TVDATA
defc _SYSVAR_TVDATA = __SYSVAR_TVDATA

PUBLIC _SYSVAR_STRMS
defc _SYSVAR_STRMS = __SYSVAR_STRMS

PUBLIC _SYSVAR_CHARS
defc _SYSVAR_CHARS = __SYSVAR_CHARS

PUBLIC _SYSVAR_RASP
defc _SYSVAR_RASP = __SYSVAR_RASP

PUBLIC _SYSVAR_PIP
defc _SYSVAR_PIP = __SYSVAR_PIP

PUBLIC _SYSVAR_ERRNR
defc _SYSVAR_ERRNR = __SYSVAR_ERRNR

PUBLIC _SYSVAR_FLAGS
defc _SYSVAR_FLAGS = __SYSVAR_FLAGS

PUBLIC _SYSVAR_TVFLAG
defc _SYSVAR_TVFLAG = __SYSVAR_TVFLAG

PUBLIC _SYSVAR_ERRSP
defc _SYSVAR_ERRSP = __SYSVAR_ERRSP

PUBLIC _SYSVAR_LISTSP
defc _SYSVAR_LISTSP = __SYSVAR_LISTSP

PUBLIC _SYSVAR_MODE
defc _SYSVAR_MODE = __SYSVAR_MODE

PUBLIC _SYSVAR_NEWPPC
defc _SYSVAR_NEWPPC = __SYSVAR_NEWPPC

PUBLIC _SYSVAR_NSPPC
defc _SYSVAR_NSPPC = __SYSVAR_NSPPC

PUBLIC _SYSVAR_PPC
defc _SYSVAR_PPC = __SYSVAR_PPC

PUBLIC _SYSVAR_SUBPPC
defc _SYSVAR_SUBPPC = __SYSVAR_SUBPPC

PUBLIC _SYSVAR_BORDCR
defc _SYSVAR_BORDCR = __SYSVAR_BORDCR

PUBLIC _SYSVAR_E_PPC
defc _SYSVAR_E_PPC = __SYSVAR_E_PPC

PUBLIC _SYSVAR_VARS
defc _SYSVAR_VARS = __SYSVAR_VARS

PUBLIC _SYSVAR_DEST
defc _SYSVAR_DEST = __SYSVAR_DEST

PUBLIC _SYSVAR_CHANS
defc _SYSVAR_CHANS = __SYSVAR_CHANS

PUBLIC _SYSVAR_CURCHL
defc _SYSVAR_CURCHL = __SYSVAR_CURCHL

PUBLIC _SYSVAR_PROG
defc _SYSVAR_PROG = __SYSVAR_PROG

PUBLIC _SYSVAR_NXTLIN
defc _SYSVAR_NXTLIN = __SYSVAR_NXTLIN

PUBLIC _SYSVAR_DATADD
defc _SYSVAR_DATADD = __SYSVAR_DATADD

PUBLIC _SYSVAR_E_LINE
defc _SYSVAR_E_LINE = __SYSVAR_E_LINE

PUBLIC _SYSVAR_K_CUR
defc _SYSVAR_K_CUR = __SYSVAR_K_CUR

PUBLIC _SYSVAR_CH_ADD
defc _SYSVAR_CH_ADD = __SYSVAR_CH_ADD

PUBLIC _SYSVAR_X_PTR
defc _SYSVAR_X_PTR = __SYSVAR_X_PTR

PUBLIC _SYSVAR_WORKSP
defc _SYSVAR_WORKSP = __SYSVAR_WORKSP

PUBLIC _SYSVAR_STKBOT
defc _SYSVAR_STKBOT = __SYSVAR_STKBOT

PUBLIC _SYSVAR_STKEND
defc _SYSVAR_STKEND = __SYSVAR_STKEND

PUBLIC _SYSVAR_BREG
defc _SYSVAR_BREG = __SYSVAR_BREG

PUBLIC _SYSVAR_MEM
defc _SYSVAR_MEM = __SYSVAR_MEM

PUBLIC _SYSVAR_FLAGS2
defc _SYSVAR_FLAGS2 = __SYSVAR_FLAGS2

PUBLIC _SYSVAR_DF_SZ
defc _SYSVAR_DF_SZ = __SYSVAR_DF_SZ

PUBLIC _SYSVAR_S_TOP
defc _SYSVAR_S_TOP = __SYSVAR_S_TOP

PUBLIC _SYSVAR_OLDPPC
defc _SYSVAR_OLDPPC = __SYSVAR_OLDPPC

PUBLIC _SYSVAR_OSPPC
defc _SYSVAR_OSPPC = __SYSVAR_OSPPC

PUBLIC _SYSVAR_FLAGX
defc _SYSVAR_FLAGX = __SYSVAR_FLAGX

PUBLIC _SYSVAR_STRLEN
defc _SYSVAR_STRLEN = __SYSVAR_STRLEN

PUBLIC _SYSVAR_T_ADDR
defc _SYSVAR_T_ADDR = __SYSVAR_T_ADDR

PUBLIC _SYSVAR_SEED
defc _SYSVAR_SEED = __SYSVAR_SEED

PUBLIC _SYSVAR_FRAMES
defc _SYSVAR_FRAMES = __SYSVAR_FRAMES

PUBLIC _SYSVAR_UDG
defc _SYSVAR_UDG = __SYSVAR_UDG

PUBLIC _SYSVAR_COORDS
defc _SYSVAR_COORDS = __SYSVAR_COORDS

PUBLIC _SYSVAR_P_POSN
defc _SYSVAR_P_POSN = __SYSVAR_P_POSN

PUBLIC _SYSVAR_PRCC
defc _SYSVAR_PRCC = __SYSVAR_PRCC

PUBLIC _SYSVAR_ECHO_E
defc _SYSVAR_ECHO_E = __SYSVAR_ECHO_E

PUBLIC _SYSVAR_DF_CC
defc _SYSVAR_DF_CC = __SYSVAR_DF_CC

PUBLIC _SYSVAR_DF_CCL
defc _SYSVAR_DF_CCL = __SYSVAR_DF_CCL

PUBLIC _SYSVAR_S_POSN
defc _SYSVAR_S_POSN = __SYSVAR_S_POSN

PUBLIC _SYSVAR_SPOSNL
defc _SYSVAR_SPOSNL = __SYSVAR_SPOSNL

PUBLIC _SYSVAR_SCR_CT
defc _SYSVAR_SCR_CT = __SYSVAR_SCR_CT

PUBLIC _SYSVAR_ATTR_P
defc _SYSVAR_ATTR_P = __SYSVAR_ATTR_P

PUBLIC _SYSVAR_MASK_P
defc _SYSVAR_MASK_P = __SYSVAR_MASK_P

PUBLIC _SYSVAR_ATTR_T
defc _SYSVAR_ATTR_T = __SYSVAR_ATTR_T

PUBLIC _SYSVAR_MASK_T
defc _SYSVAR_MASK_T = __SYSVAR_MASK_T

PUBLIC _SYSVAR_P_FLAG
defc _SYSVAR_P_FLAG = __SYSVAR_P_FLAG

PUBLIC _SYSVAR_MEMBOT
defc _SYSVAR_MEMBOT = __SYSVAR_MEMBOT

PUBLIC _SYSVAR_NMIADD
defc _SYSVAR_NMIADD = __SYSVAR_NMIADD

PUBLIC _SYSVAR_RAMTOP
defc _SYSVAR_RAMTOP = __SYSVAR_RAMTOP

PUBLIC _SYSVAR_P_RAMT
defc _SYSVAR_P_RAMT = __SYSVAR_P_RAMT
