#
# Wahey, a messed up makefile for building libraries!
#
# $Id: Makefile,v 1.4 2001-04-18 12:40:07 stefano Exp $



all:
	zcc +z88 -vn -make-lib clock.c
	zcc +z88 -vn -make-lib time.c

clean:
	rm -f *.o* *.i *.sym *.map zcc_opt.def
