#
# Wahey, a messed up makefile for building libraries!
#



all:
	zcc -vn -make-lib clock.c
	zcc -vn -make-lib gtoy.c
	zcc -vn -make-lib doepoch.c
	zcc -vn -make-lib get1970.c

clean:
	rm -f *.o* *.i *.sym *.map zcc_opt.def
