name: z88dk
base: core24
summary: Development kit for Z80 machiens
adopt-info: part-z88dk

description: |
  C compiler, assembler and libraries for over 100 z80 family machines.
  
  Z88DK is a collection of software development tools that targets the
  8080 and z80 family of machines. It allows development of programs in C,
  assembly language or any mixture of the two. What makes z88dk unique is 
  its ease of use, built-in support for many z80 machines and its extensive 
  set of assembly language library subroutines implementing the C standard 
  and extensions.

grade: stable 
confinement: strict


parts:
  part-z88dk:
    plugin: make
    source-type: git
    source: https://github.com/z88dk/z88dk.git
    override-pull: |
      snapcraftctl pull
      version="$(git rev-list --count HEAD)-$(git rev-parse --short HEAD)-$(date +%Y%m%d)"
      snapcraftctl set-version "$version"
    build-environment:
      - BUILD_SDCC: "1"
      - BUILD_SDCC_HTTP: "1"
    override-build: |
      eval $(perl -I $SNAPCRAFT_PART_INSTALL/perl5/lib/perl5/ -Mlocal::lib=$SNAPCRAFT_PART_INSTALL/perl5)
      cpanm -n Path::Tiny App::Prove Capture::Tiny CPU::Z80::Assembler Data::Dump Data::HexDump File::Path List::Uniq Modern::Perl Object::Tiny::RW Regexp::Common Test::Harness Text::Diff Text::Table YAML::Tiny Test::HexDifferences
      ./build.sh -t -e -i $SNAP
      make DESTDIR=$SNAPCRAFT_PART_INSTALL PREFIX= install
    build-packages:
      - cpanminus
      - build-essential
      - dos2unix
      - libboost-all-dev
      - texinfo
      - texi2html
      - libxml2-dev
      - subversion
      - bison
      - flex
      - zlib1g-dev
      - m4
      - curl
      - ragel
      - re2c
      - libmodern-perl-perl
      - libtemplate-perl
      - libtemplate-plugin-yaml-perl
      - libyaml-perl 
      - liblocal-lib-perl 
      - libpath-tiny-perl 
      - libtest-differences-perl 
      - libtext-table-perl 
      - libdata-hexdump-perl
      - libclone-perl
      - libfile-slurp-perl
      - libyaml-tiny-perl
      - libgmp3-dev
      - pkg-config
    stage-packages:
      - libregexp-common-perl
      - libcapture-tiny-perl
      - libicu74
      - perl-modules-5.38
      - libperl5.38
      - libxml2
      - m4

apps:
  zcc:
    command: bin/zcc
    environment:
      ZCCCFG: "$SNAP/share/z88dk/lib/config"
    plugs: [home, removable-media]
  z88dk-appmake:
    command: bin/z88dk-appmake
    plugs: [home, removable-media]
  z88dk-z80asm:
    command: bin/z88dk-z80asm
    plugs: [home, removable-media]
  z88dk-dis:
    command: bin/z88dk-dis
    plugs: [home, removable-media]
  z88dk-ticks:
    command: bin/z88dk-ticks
    plugs: [home, removable-media]
  z88dk-zx0:
    command: bin/z88dk-zx0
    plugs: [home, removable-media]
  z88dk-dzx0:
    command: bin/z88dk-dzx0
    plugs: [home, removable-media]
  z88dk-zx7:
    command: bin/z88dk-zx7
    plugs: [home, removable-media]
  z88dk-dzx7:
    command: bin/z88dk-dzx7
    plugs: [home, removable-media]
  z88dk-lib:
    command: bin/z88dk-lib
    plugs: [home, removable-media]
  z88dk-z80nm:
    command: bin/z88dk-z80nm
    plugs: [home, removable-media]
  z88dk-zobjcopy:
    command: bin/z88dk-zobjcopy
    plugs: [home, removable-media]
  z88dk-basck:
    command: bin/z88dk-basck
    plugs: [home, removable-media]
  z88dk-z80svg:
    command: bin/z88dk-z80svg
    plugs: [home, removable-media]
  z88dk-font2pv1000:
    command: bin/z88dk-font2pv1000
    plugs: [home, removable-media]
  z88dk-asmpp:
    environment:
      PERL5LIB: "$SNAP/perl5/lib/perl5:$SNAP/usr/share/perl5:$SNAP/usr/share/perl/5.30:$SNAP/usr/lib/x86_64-linux-gnu/perl/5.30"
    command: bin/z88dk-asmpp
    plugs: [home, removable-media]
  z88dk-asmstyle:
    environment:
      PERL5LIB: "$SNAP/perl5/lib/perl5:$SNAP/usr/share/perl/5.30:$SNAP/usr/lib/x86_64-linux-gnu/perl/5.30"
    command: bin/z88dk-asmstyle
    plugs: [home, removable-media]


