#
# Makefile for platform specific input routines
#
# $Id: Makefile,v 1.3 2013-11-16 10:27:48 stefano Exp $

include ../Make.config

clean:
	$(RM) spectrum/*.o*
	$(RM) zx81/*.o*
	$(RM) x1/*.o*
